In [1]:
import os
import pandas as pd

In [2]:
posts = pd.read_csv("/Users/aishwaryagupta/Desktop/Btp feature creation/project data/datasets_2012_final_CombinedCSV/Posts_2012_SO.csv")
posts

/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Id,PostTypeId,ParentID,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditorDisplayName,LastEditDate,LastActivityDate,CommunityOwnedDate,ClosedDate,Title,Tags,AnswerCount,CommentCount
0,0,4,1,NaN,7.0,2008-07-31T21:42:52.667,139,9959.0,I'm new to C# and I want to use a track-bar t...,8.0,1039608.0,Rich B,2012-05-04T08:55:46.677,2012-07-24T16:45:40.937,NaN,NaN,<c#><winforms><forms><type-conversion><opacity>,13.0,19.0,14.0
1,1,6,1,NaN,31.0,2008-07-31T22:08:08.620,43,3582.0,I have an absolutely positioned containin...,9.0,483731.0,Rich B,2012-02-26T13:47:20.073,2012-06-04T23:35:58.177,NaN,NaN,<html><css><css3><internet-explorer-7>,5.0,5.0,3.0
2,2,7,2,NaN,NaN,2008-07-31T22:17:57.883,127,NaN,An explicit cast to double isn't necessary. \...,9.0,1.0,NaN,2010-02-02T19:38:14.493,2010-02-02T19:38:14.493,NaN,NaN,NaN,NaN,2.0,NaN
3,3,8,1,NaN,162.0,2008-07-31T23:33:19.290,20,1619.0,Are there any conversion tools for porting V...,9.0,1039608.0,Rich B,2012-05-04T08:56:59.720,2012-05-08T19:00:36.850,NaN,NaN,<c#><j#><visualj#>,4.0,0.0,1.0
4,4,9,1,NaN,1404.0,2008-07-31T23:40:59.743,330,87531.0,"Given a representing their birthday, how ...",1.0,861565.0,Rich B,2012-07-30T12:23:37.267,2012-07-30T12:23:37.267,2011-08-16T19:40:43.080,NaN,<c#><.net><datetime>,33.0,5.0,148.0
5,5,11,1,NaN,1248.0,2008-07-31T23:55:37.967,388,37203.0,"Given a specific value, how do I display ...",1.0,1039608.0,Rich B,2012-05-04T08:57:39.843,2012-05-27T17:30:29.780,2009-09-04T13:15:59.820,NaN,<c#><.net><datetime><timespan>,32.0,10.0,277.0
6,6,12,2,NaN,NaN,2008-07-31T23:56:41.303,113,NaN,"Well, here's how we do it on Stack Overflow. ...",1.0,159270.0,GateKiller,2011-08-08T01:14:13.453,2011-08-08T01:14:13.453,2009-09-04T13:15:59.820,NaN,NaN,NaN,9.0,NaN
7,7,13,1,NaN,357.0,2008-08-01T00:42:38.903,157,39565.0,Is there a standard way for a Web Server to d...,9.0,1039608.0,Rich B,2012-05-04T08:58:19.547,2012-07-30T08:08:44.750,NaN,NaN,<html><browser><timezone><timezoneoffset>,19.0,2.0,66.0
8,8,14,1,NaN,NaN,2008-08-01T00:59:11.177,106,24965.0,What is the difference between and ...,11.0,1039608.0,Rich B,2012-05-04T09:00:49.407,2012-06-07T18:15:14.220,NaN,NaN,<.net><math>,5.0,1.0,17.0
9,9,16,1,NaN,12446.0,2008-08-01T04:59:33.643,23,29386.0,How do you expose a LINQ query as an ASMX ...,2.0,1039608.0,Chris Fournier,2012-05-04T09:01:26.053,2012-05-25T20:48:38.330,NaN,NaN,<c#><linq><web-services><.net-3.5>,5.0,0.0,6.0
10,10,17,1,NaN,26.0,2008-08-01T05:09:55.993,33,4746.0,How do I store binary data in MySQL ? \r\r\n,2.0,546051.0,NaN,2011-10-21T21:29:17.160,2012-06-11T15:07:58.813,NaN,NaN,<mysql><database><binary-data><data-storage>,8.0,0.0,3.0
11,11,18,2,NaN,NaN,2008-08-01T05:12:44.193,11,NaN,For a table like this: \r\r\n\r\r\n \r\r\...,NaN,6068.0,Jeff Atwood,2009-05-28T11:40:35.210,2009-05-28T11:40:35.210,NaN,NaN,NaN,NaN,2.0,NaN
12,12,19,1,NaN,NaN,2008-08-01T05:21:22.257,101,12386.0,Solutions welcome in any language. :-) I'm lo...,13.0,13.0,Chris Jester-Young,2009-08-07T11:45:50.333,2012-07-04T09:04:48.477,2009-02-26T19:22:22.320,NaN,<performance><algorithm><language-agnostic><un...,22.0,9.0,39.0
13,13,20,2,NaN,NaN,2008-08-01T07:25:22.443,4,NaN,I've used the JLCA (Java Language Conversion...,5.0,NaN,NaN,NaN,2008-08-01T07:25:22.443,NaN,NaN,NaN,NaN,0.0,NaN
14,14,21,2,NaN,NaN,2008-08-01T08:57:27.280,5,NaN,"Many years ago, to provide an age calculator...",13.0,13.0,Chris Jester-Young,2008-08-01T12:35:11.707,2008-08-01T12:35:11.707,2011-08-16T19:40:43.080,NaN,NaN,NaN,0.0,NaN
15,15,22,2,NaN,NaN,2008-08-01T12:07:19.500,2,NaN,The best way that I know of because of leap y...,17.0,17.0,Nick,2008-08-01T15:26:37.087,2008-08-01T15:26:37.087,2011-08-16T19:40:43.080,NaN,NaN,NaN,1.0,NaN
16,16,23,1,NaN,156.0,2008-08-01T12:09:41.947,23,1013.0,I'm trying to track the progress of PHP 5.3 a...,48.0,367456.0,Mat Scales,2012-06-02T17:39:22.287,2012-06-02T17:39:22.287,NaN,2012-05-18T11:12:42.583,<php>,8.0,0.0,5.0
17,17,24,1,NaN,49.0,2008-08-01T12:12:19.350,24,7722.0,If I have a trigger before the update on a ...,22.0,63550.0,Jim Anderson,2012-05-25T20:50:23.130,2012-06-14T04:32:17.193,NaN,NaN,<mysql><database><triggers>,3.0,0.0,3.0
18,18,25,1,NaN,1443907.0,2008-08-01T12:13:50.207,30,3565.0,I've been having issues getting the C sockets...,23.0,13531.0,NaN,2012-05-25T21:48:23.387,2012-05-25T21:48:23.387,NaN,NaN,<c++><c><sockets><mainframe><zos>,10.0,0.0,0.0
19,19,26,2,NaN,NaN,2008-08-01T12:16:22.167,27,NaN,The answer by phpguy is correct but I think t...,48.0,48.0,Geoff Dalgas,2012-06-11T15:07:58.813,2012-06-11T15:07:58.813,NaN,NaN,NaN,NaN,3.0,NaN
20,20,27,2,NaN,NaN,2008-08-01T12:17:19.357,7,NaN,@jeff \r\r\r\n\r\r\r\n IMHO yours seems a lit...,17.0,17.0,Nick Berardi,2008-08-01T13:16:49.127,2008-08-01T13:16:49.127,2009-09-04T13:15:59.820,NaN,NaN,NaN,1.0,NaN
21,21,29,2,NaN,NaN,2008-08-01T12:19:17.417,8,NaN,There are no HTTP headers that will report th...,19.0,NaN,NaN,NaN,2008-08-01T12:19:17.417,NaN,NaN,NaN,NaN,0.0,NaN
22,22,30,2,NaN,NaN,2008-08-01T12:22:40.797,4,NaN,I've had no trouble using the BSD sockets API...,13.0,NaN,NaN,NaN,2008-08-01T12:22:40.797,NaN,NaN,NaN,NaN,1.0,NaN
23,23,31,2,NaN,NaN,2008-08-01T12:22:51.593,23,NaN,Does the parent have a defined either...,NaN,842480.0,NaN,2012-06-04T23:35:58.177,2012-06-04T23:35:58.177,NaN,NaN,NaN,NaN,0.0,NaN
24,24,33,2,NaN,NaN,2008-08-01T12:26:39.773,172,NaN,"rounds down, rounds up, and round...",13.0,13.0,NaN,2009-10-14T02:09:03.030,2009-10-14T02:09:03.030,NaN,NaN,NaN,NaN,5.0,NaN
25,25,34,1,NaN,NaN,2008-08-01T12:30:57.630,16,4179.0,How do I forcefully unload a from memory ...,NaN,63550.0,NaN,2012-05-25T21:06:10.223,2012-05-25T21:06:10.223,NaN,NaN,<flex><actionscript-3>,7.0,NaN,0.0
26,26,36,1,NaN,352.0,2008-08-01T12:35:56.917,32,10439.0,How can I monitor an SQL Server database for ...,32.0,419.0,Mark Harrison,2012-05-25T23:43:47.697,2012-05-25T23:43:47.697,NaN,NaN,<sql-server><datatable><rdbms>,8.0,0.0,6.0
27,27,37,2,NaN,NaN,2008-08-01T12:36:00.957,4,NaN,Sure I can post a test app. \r\r\r\n\r\r\r\n ...,23.0,23.0,Jax,2008-08-01T12:42:32.113,2008-08-01T12:42:32.113,NaN,NaN,NaN,NaN,0.0,NaN
28,28,39,1,NaN,45.0,2008-08-01T12:43:11.503,11,2080.0,I am aware that in .NET there are three tim...,33.0,63550.0,Jim Anderson,2012-05-25T20:55:43.157,2012-05-25T20:55:43.157,NaN,NaN,<c#><.net><vb.net><timer>,2.0,NaN,1.0
29,29,41,2,NaN,NaN,2008-08-01T12:49:12.413,8,NaN,Your best bet are probably these meeting note...,34.0,31671.0,NaN,2010-02-20T23:26:24.063,2010-02-20T23:26:24.063,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10338331,10338331,11750729,1,NaN,11750757.0,2012-07-31T23:55:24.683,0,43.0,I'm working on a winform application which cr...,731901.0,731901.0,NaN,2012-08-01T00:24:12.690,2012-08-01T00:24:12.690,NaN,NaN,<c#><winforms>,2.0,2.0,NaN
10338332,10338332,11750730,2,NaN,NaN,2012-07-31T23:55:26.770,0,NaN,I know of no solution using font-size to modi...,1330275.0,NaN,NaN,NaN,2012-07-31T23:55:26.770,NaN,NaN,NaN,NaN,NaN,NaN
10338333,10338333,11750731,2,NaN,NaN,2012-07-31T23:55:29.207,2,NaN,The simple answer is you can't. But let me e...,409167.0,NaN,NaN,NaN,2012-07-31T23:55:29.207,NaN,NaN,NaN,NaN,NaN,NaN
10338334,10338334,11750732,1,NaN,NaN,2012-07-31T23:55:30.050,0,13.0,"Bear with me please, I'm a new programmer. (t...",1318705.0,1318705.0,NaN,2012-08-01T00:02:53.887,2012-08-01T00:02:53.887,NaN,NaN,<ios><json>,NaN,6.0,NaN
10338335,10338335,11750733,1,NaN,NaN,2012-07-31T23:55:35.260,0,20.0,I have a codebase that deals with angles quit...,770038.0,NaN,NaN,NaN,2012-08-01T00:25:46.087,NaN,NaN,<oop><design-patterns>,2.0,1.0,NaN
10338336,10338336,11750735,2,NaN,NaN,2012-07-31T23:55:48.533,0,NaN,The short answer to this question is that EF4...,984335.0,NaN,NaN,NaN,2012-07-31T23:55:48.533,NaN,NaN,NaN,NaN,NaN,NaN
10338337,10338337,11750736,2,NaN,NaN,2012-07-31T23:55:52.110,2,NaN,The is purely the runtime environment nee...,1398245.0,NaN,NaN,NaN,2012-07-31T23:55:52.110,NaN,NaN,NaN,NaN,1.0,NaN
10338338,10338338,11750738,1,NaN,NaN,2012-07-31T23:56:18.193,0,17.0,I've been trying to uncrush PNG's extracted f...,900747.0,NaN,NaN,NaN,2012-08-01T00:08:32.853,NaN,NaN,<iphone><ios><ipad><ipa><pngcrush>,1.0,NaN,NaN
10338339,10338339,11750739,1,NaN,NaN,2012-07-31T23:56:24.543,-6,27.0,Sorry for this not exactly being a coding rel...,1261355.0,NaN,NaN,NaN,2012-07-31T23:56:24.543,NaN,NaN,<android><free><ads><paid><monetization>,NaN,1.0,NaN
10338340,10338340,11750740,1,NaN,NaN,2012-07-31T23:56:54.217,0,9.0,"According to this: ""Important: OAuth 1.0 has ...",841626.0,NaN,NaN,NaN,2012-07-31T23:56:54.217,NaN,NaN,<api><google><oauth><google-api><deprecated>,NaN,1.0,NaN
10338341,10338341,11750741,1,NaN,11751189.0,2012-07-31T23:56:58.567,0,17.0,Sorry for my bad english \r\r\n\r\r\n i searc...,1472467.0,NaN,NaN,NaN,2012-08-01T01:00:47.150,NaN,NaN,<objective-c><arrays><cocos2d-iphone><cocos2d>...,1.0,NaN,NaN
10338342,10338342,11750742,1,NaN,11751053.0,2012-07-31T23:57:18.710,0,14.0,Using PunBB on Forumotion the idea was to use...,1567186.0,NaN,NaN,NaN,2012-08-01T00:40:30.840,NaN,NaN,<javascript><jquery><string><replace><punbb>,2.0,2.0,NaN
10338343,10338343,11750743,1,NaN,NaN,2012-07-31T23:57:30.063,0,20.0,The basic idea of the application I've been w...,539273.0,NaN,NaN,NaN,2012-08-01T00:46:01.187,NaN,NaN,<ruby-on-rails><ios><design-patterns><design><...,1.0,NaN,NaN
10338344,10338344,11750744,2,NaN,NaN,2012-07-31T23:57:56.600,1,NaN,"No, this will not work. To have cron execute ...",491094.0,NaN,NaN,NaN,2012-07-31T23:57:56.600,NaN,NaN,NaN,NaN,1.0,NaN
10338345,10338345,11750745,2,NaN,NaN,2012-07-31T23:58:02.943,0,NaN,"When displaying your results with MessageBox,...",1504644.0,NaN,NaN,NaN,2012-07-31T23:58:02.943,NaN,NaN,NaN,NaN,NaN,NaN
10338346,10338346,11750746,1,NaN,11750810.0,2012-07-31T23:58:04.573,0,20.0,I've created an XNA application that utilizes...,595437.0,NaN,NaN,NaN,2012-08-01T00:05:59.343,NaN,NaN,<.net><xna><lua><extension-methods>,2.0,NaN,NaN
10338347,10338347,11750747,1,NaN,NaN,2012-07-31T23:58:07.160,0,39.0,After looking over several articles in intern...,1567194.0,1567194.0,NaN,2012-08-01T02:11:19.287,2012-08-01T02:11:19.287,NaN,NaN,<vb.net>,1.0,9.0,NaN
10338348,10338348,11750748,2,NaN,NaN,2012-07-31T23:58:11.440,0,NaN,I execute scripts as part of an iOS project. ...,775184.0,NaN,NaN,NaN,2012-07-31T23:58:11.440,NaN,NaN,NaN,NaN,NaN,NaN
10338349,10338349,11750749,2,NaN,NaN,2012-07-31T23:58:50.220,0,NaN,Always check your model functions if they ret...,686733.0,NaN,NaN,NaN,2012-07-31T23:58:50.220,NaN,NaN,NaN,NaN,1.0,NaN
10338350,10338350,11750750,2,NaN,NaN,2012-07-31T23:58:56.213,0,NaN,"ah, actually that did work, the complex excep...",517781.0,NaN,NaN,NaN,2012-07-31T23:58:56.213,NaN,NaN,NaN,NaN,NaN,NaN
10338351,10338351,11750751,2,NaN,NaN,2012-07-31T23:59:03.527,0,NaN,\r\r\n\r\r\n or rather just \r\r\n\r\r\n ...,898266.0,898266.0,NaN,2012-08-01T00:13:55.030,2012-08-01T00:13:55.030,NaN,NaN,NaN,NaN,2.0,NaN
10338352,10338352,11750752,2,NaN,NaN,2012-07-31T23:59:12.620,0,NaN,Maybe this can help: \r\r\n\r\r\n \r\r\n\...,1478722.0,NaN,NaN,NaN,2012-07-31T23:59:12.620,NaN,NaN,NaN,NaN,NaN,NaN
10338353,10338353,11750753,2,NaN,NaN,2012-07-31T23:59:25.083,1,NaN,GetLanguagesForTranslate() returns the set of...,1567202.0,NaN,NaN,NaN,2012-07-31T23:59:25.083,NaN,NaN,NaN,NaN,NaN,NaN
10338354,10338354,11750755,1,NaN,NaN,2012-07-31T23:59:26.430,0,12.0,"I have a table, and here are the relevant...",173630.0,NaN,NaN,NaN,2012-08-01T03:30:16.943,NaN,NaN,<sql><postgresql><plpgsql><postgresql-9.1>,2.0,NaN,NaN
10338355,10338355,11750756,2,NaN,NaN,2012-07-31T23:59:29.873,1,NaN,The full error reads \r\r\n\r\r\n \r\r\n\...,582.0,NaN,NaN,NaN,2012-07-31T23:59:29.873,NaN,NaN,NaN,NaN,NaN,NaN
10338356,10338356,11750757,2,NaN,NaN,2012-07-31T23:59:38.263,0,NaN,You need elevated permissions only to copy to...,141172.0,NaN,NaN,NaN,2012-07-31T23:59:38.263,NaN,NaN,NaN,NaN,3.0,NaN
10338357,10338357,11750758,2,NaN,NaN,2012-07-31T23:59:41.953,1,NaN,CodePlex offers free TFS hosting with a featu...,729881.0,NaN,NaN,NaN,2012-07-31T23:59:41.953,NaN,NaN,NaN,NaN,1.0,NaN
10338358,10338358,11750759,1,NaN,11750812.0,2012-07-31T23:59:41.970,0,9.0,i have a database with 16 fields and i just w...,1492051.0,NaN,NaN,NaN,2012-08-01T00:14:18.913,NaN,NaN,<vb.net>,1.0,1.0,NaN
10338359,10338359,11750760,2,NaN,NaN,2012-07-31T23:59:49.843,0,NaN,Passing it through your compiler with full wa...,898258.0,NaN,NaN,NaN,2012-07-31T23:59:49.843,NaN,NaN,NaN,NaN,NaN,NaN
10338360,10338360,11750761,1,NaN,NaN,2012-07-31T23:59:57.380,0,3.0,I cant find any examples online on how to u...,1513192.0,NaN,NaN,NaN,2012-07-31T23:59:57.380,NaN,NaN,<python><wxpython><wxwidgets><wx><wxruby>,NaN,NaN,NaN

In [3]:
cols = [0]
posts.drop(posts.columns[cols],axis=1,inplace=True)
posts

,Id,PostTypeId,ParentID,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditorDisplayName,LastEditDate,LastActivityDate,CommunityOwnedDate,ClosedDate,Title,Tags,AnswerCount,CommentCount
0,4,1,NaN,7.0,2008-07-31T21:42:52.667,139,9959.0,I'm new to C# and I want to use a track-bar t...,8.0,1039608.0,Rich B,2012-05-04T08:55:46.677,2012-07-24T16:45:40.937,NaN,NaN,<c#><winforms><forms><type-conversion><opacity>,13.0,19.0,14.0
1,6,1,NaN,31.0,2008-07-31T22:08:08.620,43,3582.0,I have an absolutely positioned containin...,9.0,483731.0,Rich B,2012-02-26T13:47:20.073,2012-06-04T23:35:58.177,NaN,NaN,<html><css><css3><internet-explorer-7>,5.0,5.0,3.0
2,7,2,NaN,NaN,2008-07-31T22:17:57.883,127,NaN,An explicit cast to double isn't necessary. \...,9.0,1.0,NaN,2010-02-02T19:38:14.493,2010-02-02T19:38:14.493,NaN,NaN,NaN,NaN,2.0,NaN
3,8,1,NaN,162.0,2008-07-31T23:33:19.290,20,1619.0,Are there any conversion tools for porting V...,9.0,1039608.0,Rich B,2012-05-04T08:56:59.720,2012-05-08T19:00:36.850,NaN,NaN,<c#><j#><visualj#>,4.0,0.0,1.0
4,9,1,NaN,1404.0,2008-07-31T23:40:59.743,330,87531.0,"Given a representing their birthday, how ...",1.0,861565.0,Rich B,2012-07-30T12:23:37.267,2012-07-30T12:23:37.267,2011-08-16T19:40:43.080,NaN,<c#><.net><datetime>,33.0,5.0,148.0
5,11,1,NaN,1248.0,2008-07-31T23:55:37.967,388,37203.0,"Given a specific value, how do I display ...",1.0,1039608.0,Rich B,2012-05-04T08:57:39.843,2012-05-27T17:30:29.780,2009-09-04T13:15:59.820,NaN,<c#><.net><datetime><timespan>,32.0,10.0,277.0
6,12,2,NaN,NaN,2008-07-31T23:56:41.303,113,NaN,"Well, here's how we do it on Stack Overflow. ...",1.0,159270.0,GateKiller,2011-08-08T01:14:13.453,2011-08-08T01:14:13.453,2009-09-04T13:15:59.820,NaN,NaN,NaN,9.0,NaN
7,13,1,NaN,357.0,2008-08-01T00:42:38.903,157,39565.0,Is there a standard way for a Web Server to d...,9.0,1039608.0,Rich B,2012-05-04T08:58:19.547,2012-07-30T08:08:44.750,NaN,NaN,<html><browser><timezone><timezoneoffset>,19.0,2.0,66.0
8,14,1,NaN,NaN,2008-08-01T00:59:11.177,106,24965.0,What is the difference between and ...,11.0,1039608.0,Rich B,2012-05-04T09:00:49.407,2012-06-07T18:15:14.220,NaN,NaN,<.net><math>,5.0,1.0,17.0
9,16,1,NaN,12446.0,2008-08-01T04:59:33.643,23,29386.0,How do you expose a LINQ query as an ASMX ...,2.0,1039608.0,Chris Fournier,2012-05-04T09:01:26.053,2012-05-25T20:48:38.330,NaN,NaN,<c#><linq><web-services><.net-3.5>,5.0,0.0,6.0
10,17,1,NaN,26.0,2008-08-01T05:09:55.993,33,4746.0,How do I store binary data in MySQL ? \r\r\n,2.0,546051.0,NaN,2011-10-21T21:29:17.160,2012-06-11T15:07:58.813,NaN,NaN,<mysql><database><binary-data><data-storage>,8.0,0.0,3.0
11,18,2,NaN,NaN,2008-08-01T05:12:44.193,11,NaN,For a table like this: \r\r\n\r\r\n \r\r\...,NaN,6068.0,Jeff Atwood,2009-05-28T11:40:35.210,2009-05-28T11:40:35.210,NaN,NaN,NaN,NaN,2.0,NaN
12,19,1,NaN,NaN,2008-08-01T05:21:22.257,101,12386.0,Solutions welcome in any language. :-) I'm lo...,13.0,13.0,Chris Jester-Young,2009-08-07T11:45:50.333,2012-07-04T09:04:48.477,2009-02-26T19:22:22.320,NaN,<performance><algorithm><language-agnostic><un...,22.0,9.0,39.0
13,20,2,NaN,NaN,2008-08-01T07:25:22.443,4,NaN,I've used the JLCA (Java Language Conversion...,5.0,NaN,NaN,NaN,2008-08-01T07:25:22.443,NaN,NaN,NaN,NaN,0.0,NaN
14,21,2,NaN,NaN,2008-08-01T08:57:27.280,5,NaN,"Many years ago, to provide an age calculator...",13.0,13.0,Chris Jester-Young,2008-08-01T12:35:11.707,2008-08-01T12:35:11.707,2011-08-16T19:40:43.080,NaN,NaN,NaN,0.0,NaN
15,22,2,NaN,NaN,2008-08-01T12:07:19.500,2,NaN,The best way that I know of because of leap y...,17.0,17.0,Nick,2008-08-01T15:26:37.087,2008-08-01T15:26:37.087,2011-08-16T19:40:43.080,NaN,NaN,NaN,1.0,NaN
16,23,1,NaN,156.0,2008-08-01T12:09:41.947,23,1013.0,I'm trying to track the progress of PHP 5.3 a...,48.0,367456.0,Mat Scales,2012-06-02T17:39:22.287,2012-06-02T17:39:22.287,NaN,2012-05-18T11:12:42.583,<php>,8.0,0.0,5.0
17,24,1,NaN,49.0,2008-08-01T12:12:19.350,24,7722.0,If I have a trigger before the update on a ...,22.0,63550.0,Jim Anderson,2012-05-25T20:50:23.130,2012-06-14T04:32:17.193,NaN,NaN,<mysql><database><triggers>,3.0,0.0,3.0
18,25,1,NaN,1443907.0,2008-08-01T12:13:50.207,30,3565.0,I've been having issues getting the C sockets...,23.0,13531.0,NaN,2012-05-25T21:48:23.387,2012-05-25T21:48:23.387,NaN,NaN,<c++><c><sockets><mainframe><zos>,10.0,0.0,0.0
19,26,2,NaN,NaN,2008-08-01T12:16:22.167,27,NaN,The answer by phpguy is correct but I think t...,48.0,48.0,Geoff Dalgas,2012-06-11T15:07:58.813,2012-06-11T15:07:58.813,NaN,NaN,NaN,NaN,3.0,NaN
20,27,2,NaN,NaN,2008-08-01T12:17:19.357,7,NaN,@jeff \r\r\r\n\r\r\r\n IMHO yours seems a lit...,17.0,17.0,Nick Berardi,2008-08-01T13:16:49.127,2008-08-01T13:16:49.127,2009-09-04T13:15:59.820,NaN,NaN,NaN,1.0,NaN
21,29,2,NaN,NaN,2008-08-01T12:19:17.417,8,NaN,There are no HTTP headers that will report th...,19.0,NaN,NaN,NaN,2008-08-01T12:19:17.417,NaN,NaN,NaN,NaN,0.0,NaN
22,30,2,NaN,NaN,2008-08-01T12:22:40.797,4,NaN,I've had no trouble using the BSD sockets API...,13.0,NaN,NaN,NaN,2008-08-01T12:22:40.797,NaN,NaN,NaN,NaN,1.0,NaN
23,31,2,NaN,NaN,2008-08-01T12:22:51.593,23,NaN,Does the parent have a defined either...,NaN,842480.0,NaN,2012-06-04T23:35:58.177,2012-06-04T23:35:58.177,NaN,NaN,NaN,NaN,0.0,NaN
24,33,2,NaN,NaN,2008-08-01T12:26:39.773,172,NaN,"rounds down, rounds up, and round...",13.0,13.0,NaN,2009-10-14T02:09:03.030,2009-10-14T02:09:03.030,NaN,NaN,NaN,NaN,5.0,NaN
25,34,1,NaN,NaN,2008-08-01T12:30:57.630,16,4179.0,How do I forcefully unload a from memory ...,NaN,63550.0,NaN,2012-05-25T21:06:10.223,2012-05-25T21:06:10.223,NaN,NaN,<flex><actionscript-3>,7.0,NaN,0.0
26,36,1,NaN,352.0,2008-08-01T12:35:56.917,32,10439.0,How can I monitor an SQL Server database for ...,32.0,419.0,Mark Harrison,2012-05-25T23:43:47.697,2012-05-25T23:43:47.697,NaN,NaN,<sql-server><datatable><rdbms>,8.0,0.0,6.0
27,37,2,NaN,NaN,2008-08-01T12:36:00.957,4,NaN,Sure I can post a test app. \r\r\r\n\r\r\r\n ...,23.0,23.0,Jax,2008-08-01T12:42:32.113,2008-08-01T12:42:32.113,NaN,NaN,NaN,NaN,0.0,NaN
28,39,1,NaN,45.0,2008-08-01T12:43:11.503,11,2080.0,I am aware that in .NET there are three tim...,33.0,63550.0,Jim Anderson,2012-05-25T20:55:43.157,2012-05-25T20:55:43.157,NaN,NaN,<c#><.net><vb.net><timer>,2.0,NaN,1.0
29,41,2,NaN,NaN,2008-08-01T12:49:12.413,8,NaN,Your best bet are probably these meeting note...,34.0,31671.0,NaN,2010-02-20T23:26:24.063,2010-02-20T23:26:24.063,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10338331,11750729,1,NaN,11750757.0,2012-07-31T23:55:24.683,0,43.0,I'm working on a winform application which cr...,731901.0,731901.0,NaN,2012-08-01T00:24:12.690,2012-08-01T00:24:12.690,NaN,NaN,<c#><winforms>,2.0,2.0,NaN
10338332,11750730,2,NaN,NaN,2012-07-31T23:55:26.770,0,NaN,I know of no solution using font-size to modi...,1330275.0,NaN,NaN,NaN,2012-07-31T23:55:26.770,NaN,NaN,NaN,NaN,NaN,NaN
10338333,11750731,2,NaN,NaN,2012-07-31T23:55:29.207,2,NaN,The simple answer is you can't. But let me e...,409167.0,NaN,NaN,NaN,2012-07-31T23:55:29.207,NaN,NaN,NaN,NaN,NaN,NaN
10338334,11750732,1,NaN,NaN,2012-07-31T23:55:30.050,0,13.0,"Bear with me please, I'm a new programmer. (t...",1318705.0,1318705.0,NaN,2012-08-01T00:02:53.887,2012-08-01T00:02:53.887,NaN,NaN,<ios><json>,NaN,6.0,NaN
10338335,11750733,1,NaN,NaN,2012-07-31T23:55:35.260,0,20.0,I have a codebase that deals with angles quit...,770038.0,NaN,NaN,NaN,2012-08-01T00:25:46.087,NaN,NaN,<oop><design-patterns>,2.0,1.0,NaN
10338336,11750735,2,NaN,NaN,2012-07-31T23:55:48.533,0,NaN,The short answer to this question is that EF4...,984335.0,NaN,NaN,NaN,2012-07-31T23:55:48.533,NaN,NaN,NaN,NaN,NaN,NaN
10338337,11750736,2,NaN,NaN,2012-07-31T23:55:52.110,2,NaN,The is purely the runtime environment nee...,1398245.0,NaN,NaN,NaN,2012-07-31T23:55:52.110,NaN,NaN,NaN,NaN,1.0,NaN
10338338,11750738,1,NaN,NaN,2012-07-31T23:56:18.193,0,17.0,I've been trying to uncrush PNG's extracted f...,900747.0,NaN,NaN,NaN,2012-08-01T00:08:32.853,NaN,NaN,<iphone><ios><ipad><ipa><pngcrush>,1.0,NaN,NaN
10338339,11750739,1,NaN,NaN,2012-07-31T23:56:24.543,-6,27.0,Sorry for this not exactly being a coding rel...,1261355.0,NaN,NaN,NaN,2012-07-31T23:56:24.543,NaN,NaN,<android><free><ads><paid><monetization>,NaN,1.0,NaN
10338340,11750740,1,NaN,NaN,2012-07-31T23:56:54.217,0,9.0,"According to this: ""Important: OAuth 1.0 has ...",841626.0,NaN,NaN,NaN,2012-07-31T23:56:54.217,NaN,NaN,<api><google><oauth><google-api><deprecated>,NaN,1.0,NaN
10338341,11750741,1,NaN,11751189.0,2012-07-31T23:56:58.567,0,17.0,Sorry for my bad english \r\r\n\r\r\n i searc...,1472467.0,NaN,NaN,NaN,2012-08-01T01:00:47.150,NaN,NaN,<objective-c><arrays><cocos2d-iphone><cocos2d>...,1.0,NaN,NaN
10338342,11750742,1,NaN,11751053.0,2012-07-31T23:57:18.710,0,14.0,Using PunBB on Forumotion the idea was to use...,1567186.0,NaN,NaN,NaN,2012-08-01T00:40:30.840,NaN,NaN,<javascript><jquery><string><replace><punbb>,2.0,2.0,NaN
10338343,11750743,1,NaN,NaN,2012-07-31T23:57:30.063,0,20.0,The basic idea of the application I've been w...,539273.0,NaN,NaN,NaN,2012-08-01T00:46:01.187,NaN,NaN,<ruby-on-rails><ios><design-patterns><design><...,1.0,NaN,NaN
10338344,11750744,2,NaN,NaN,2012-07-31T23:57:56.600,1,NaN,"No, this will not work. To have cron execute ...",491094.0,NaN,NaN,NaN,2012-07-31T23:57:56.600,NaN,NaN,NaN,NaN,1.0,NaN
10338345,11750745,2,NaN,NaN,2012-07-31T23:58:02.943,0,NaN,"When displaying your results with MessageBox,...",1504644.0,NaN,NaN,NaN,2012-07-31T23:58:02.943,NaN,NaN,NaN,NaN,NaN,NaN
10338346,11750746,1,NaN,11750810.0,2012-07-31T23:58:04.573,0,20.0,I've created an XNA application that utilizes...,595437.0,NaN,NaN,NaN,2012-08-01T00:05:59.343,NaN,NaN,<.net><xna><lua><extension-methods>,2.0,NaN,NaN
10338347,11750747,1,NaN,NaN,2012-07-31T23:58:07.160,0,39.0,After looking over several articles in intern...,1567194.0,1567194.0,NaN,2012-08-01T02:11:19.287,2012-08-01T02:11:19.287,NaN,NaN,<vb.net>,1.0,9.0,NaN
10338348,11750748,2,NaN,NaN,2012-07-31T23:58:11.440,0,NaN,I execute scripts as part of an iOS project. ...,775184.0,NaN,NaN,NaN,2012-07-31T23:58:11.440,NaN,NaN,NaN,NaN,NaN,NaN
10338349,11750749,2,NaN,NaN,2012-07-31T23:58:50.220,0,NaN,Always check your model functions if they ret...,686733.0,NaN,NaN,NaN,2012-07-31T23:58:50.220,NaN,NaN,NaN,NaN,1.0,NaN
10338350,11750750,2,NaN,NaN,2012-07-31T23:58:56.213,0,NaN,"ah, actually that did work, the complex excep...",517781.0,NaN,NaN,NaN,2012-07-31T23:58:56.213,NaN,NaN,NaN,NaN,NaN,NaN
10338351,11750751,2,NaN,NaN,2012-07-31T23:59:03.527,0,NaN,\r\r\n\r\r\n or rather just \r\r\n\r\r\n ...,898266.0,898266.0,NaN,2012-08-01T00:13:55.030,2012-08-01T00:13:55.030,NaN,NaN,NaN,NaN,2.0,NaN
10338352,11750752,2,NaN,NaN,2012-07-31T23:59:12.620,0,NaN,Maybe this can help: \r\r\n\r\r\n \r\r\n\...,1478722.0,NaN,NaN,NaN,2012-07-31T23:59:12.620,NaN,NaN,NaN,NaN,NaN,NaN
10338353,11750753,2,NaN,NaN,2012-07-31T23:59:25.083,1,NaN,GetLanguagesForTranslate() returns the set of...,1567202.0,NaN,NaN,NaN,2012-07-31T23:59:25.083,NaN,NaN,NaN,NaN,NaN,NaN
10338354,11750755,1,NaN,NaN,2012-07-31T23:59:26.430,0,12.0,"I have a table, and here are the relevant...",173630.0,NaN,NaN,NaN,2012-08-01T03:30:16.943,NaN,NaN,<sql><postgresql><plpgsql><postgresql-9.1>,2.0,NaN,NaN
10338355,11750756,2,NaN,NaN,2012-07-31T23:59:29.873,1,NaN,The full error reads \r\r\n\r\r\n \r\r\n\...,582.0,NaN,NaN,NaN,2012-07-31T23:59:29.873,NaN,NaN,NaN,NaN,NaN,NaN
10338356,11750757,2,NaN,NaN,2012-07-31T23:59:38.263,0,NaN,You need elevated permissions only to copy to...,141172.0,NaN,NaN,NaN,2012-07-31T23:59:38.263,NaN,NaN,NaN,NaN,3.0,NaN
10338357,11750758,2,NaN,NaN,2012-07-31T23:59:41.953,1,NaN,CodePlex offers free TFS hosting with a featu...,729881.0,NaN,NaN,NaN,2012-07-31T23:59:41.953,NaN,NaN,NaN,NaN,1.0,NaN
10338358,11750759,1,NaN,11750812.0,2012-07-31T23:59:41.970,0,9.0,i have a database with 16 fields and i just w...,1492051.0,NaN,NaN,NaN,2012-08-01T00:14:18.913,NaN,NaN,<vb.net>,1.0,1.0,NaN
10338359,11750760,2,NaN,NaN,2012-07-31T23:59:49.843,0,NaN,Passing it through your compiler with full wa...,898258.0,NaN,NaN,NaN,2012-07-31T23:59:49.843,NaN,NaN,NaN,NaN,NaN,NaN
10338360,11750761,1,NaN,NaN,2012-07-31T23:59:57.380,0,3.0,I cant find any examples online on how to u...,1513192.0,NaN,NaN,NaN,2012-07-31T23:59:57.380,NaN,NaN,<python><wxpython><wxwidgets><wx><wxruby>,NaN,NaN,NaN

In [4]:
users = pd.read_csv("/Users/aishwaryagupta/Desktop/Btp feature creation/project data/datasets_2012_final_CombinedCSV/SO_users_2012.csv")
users

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,-1,1,2008-07-31T00:00:00.000,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,2008-08-26T00:16:53.810,http://stackoverflow.com,on the server farm,NaN,"<p>Hi, I'm not really a person.</p>\r\n<p>I'm ...",649,4310,91092
1,1,1,21812,2008-07-31T14:22:31.287,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,2012-08-01T04:46:57.447,http://www.codinghorror.com/blog/,"El Cerrito, CA",41.0,"<p><a href=""http://www.codinghorror.com/blog/a...",41072,3090,1279
2,2,2,1362,2008-07-31T14:22:31.287,Geoff Dalgas,b437f461b3fd27387c5d8ab47a293d35,2012-07-31T23:38:17.330,http://stackoverflow.com,"Corvallis, OR",35.0,<p>Developer on the StackOverflow team. Find ...,7679,430,82
3,3,3,5584,2008-07-31T14:22:31.287,Jarrod Dixon,2dfa19bf5dc5826c1fe54c2c049a1ff1,2012-07-31T22:49:53.213,http://stackoverflow.com,"New York, NY",33.0,"<p><a href=""http://blog.stackoverflow.com/2009...",8929,3280,67
4,4,4,16676,2008-07-31T14:22:31.317,Joel Spolsky,d1129adecd8c4e2a22b50605d18e376d,2012-08-01T03:37:02.227,http://www.joelonsoftware.com/,"New York, NY",NaN,<p>I am:</p>\n\n<ul>\n<li>the co-founder and C...,32408,688,91
5,5,5,20812,2008-07-31T14:22:31.317,Jon Galloway,1c494896dd56e0e27253156c28f1dfb9,2012-07-31T22:31:50.930,http://weblogs.asp.net/jgalloway/,"San Diego, CA",41.0,<p>Community program manager for ASP.NET at Mi...,2962,738,34
6,6,8,817,2008-07-31T21:33:24.057,Eggs McLaren,c7ec7dec48168d2a7d792e2b0acc78d1,2012-07-20T18:25:48.217,NaN,NaN,NaN,<p>This is a puppet test account I use to vali...,1228,12,9
7,7,9,4630,2008-07-31T21:35:26.517,Kevin Dente,23c1e2063688620b75b248e08c0d5c24,2012-07-31T23:07:18.440,http://weblogs.asp.net/kdente,"Oakland, CA",41.0,"<p>Self employed software engineer, currently ...",1056,27,4
8,8,10,101,2008-07-31T21:57:06.240,Sneakers O'Toole,f82fc4a2bfc73434ac4899690926c8a0,2012-06-19T19:35:43.433,http://www.youtube.com/watch?v=qrhNoljPtok,"Lakehead, CA",33.0,I'm not takin' my sneakers off!\r\n<br><br>\r\...,875,0,0
9,9,11,537,2008-08-01T00:59:11.147,Anonymous User,c510febb9bed68b5cc4a09f076701e0f,2008-08-01T00:59:11.147,NaN,NaN,NaN,NaN,304,0,0
10,10,13,63611,2008-08-01T04:18:04.943,Chris Jester-Young,729442eea8d8548842a6e0947e333c7b,2012-07-31T22:48:22.820,http://about.me/cky,"Raleigh, NC",32.0,"\n\n<p>Quick links:</p>\n\n<ul>\n<li><a href=""...",3347,3348,123
11,11,16,313,2008-08-01T12:01:53.023,Rodrigo Sieiro,235da791830e54ec0bfc084800523349,2012-08-01T03:21:30.773,http://twitter.com/rsieiro,Brazil,31.0,You don't know me because I keep a low profile.,279,25,1
12,12,17,22049,2008-08-01T12:02:21.617,Nick Berardi,42893555ea66c988b51c9167a650d849,2012-08-01T02:00:20.007,http://coderjournal.com,"Collegeville, PA",32.0,<p><strong>email</strong>: nberardi@gmail.com<...,1706,811,193
13,13,19,404,2008-08-01T12:05:14.233,Mads Kristiansen,4bd8c62d52be7585745a99da8f526d93,2012-03-12T13:10:34.120,NaN,Denmark,38.0,NaN,270,33,10
14,14,20,4898,2008-08-01T12:09:11.010,Tom,1f0b00b8853cf0311888bb3ed2a77ebc,2012-07-24T15:29:32.373,http://tommcfarlin.com,"Atlanta, GA",NaN,NaN,505,366,38
15,15,22,3481,2008-08-01T12:11:11.897,maclema,1c23587bf4956c04bb580a6d1310e678,2012-07-31T18:57:39.533,http://www.maclema.com,"Calgary, Canada",26.0,NaN,273,112,5
16,16,23,977,2008-08-01T12:11:43.703,Jax,41e48d118b55b1bd341141dccacbfeb5,2012-07-31T20:57:47.477,http://jackstrife.com,"Cary, NC",25.0,I'm a young whippersnapper who just got out of...,229,182,2
17,17,24,428,2008-08-01T12:12:53.453,braklet,b51e14bfee5fd2f1d63c8e2b0ff2f2bb,2012-07-26T21:55:13.853,http://www.google.com/reader/shared/Braklet,"London, United Kingdom",28.0,Code junkie,86,112,0
18,18,25,5522,2008-08-01T12:15:23.243,CodingWithoutComments,d66009e0e3917e52fbf65b8dc03c2068,2012-05-20T22:46:32.797,http://www.codingwithoutcomments.com,"Seattle, WA",31.0,"a man, a plan, a canal, panama\r\n",1047,519,73
19,19,26,6234,2008-08-01T12:18:14.520,Shawn,f878a55e08bacee0af48852c29a02dc7,2012-07-31T00:14:51.510,NaN,"San Francisco, CA",28.0,<p>a long time ago i found an xss vuln here an...,2012,556,62
20,20,27,893,2008-08-01T12:21:40.020,denny,1f5623ff6f4c6ac52bc757a7f03ab6ec,2012-07-30T16:20:09.330,http://www.dennymorrison.net,"Winchester, VA",29.0,"<p>I write shitty, buggy code...but that's oka...",145,288,3
21,21,29,24640,2008-08-01T12:24:53.820,Michael Haren,f4f4b5a6f27f72b32d42463b1a25e0df,2012-08-01T03:23:28.853,http://blog.wassupy.com/search/label/Technology,Ohio,29.0,<ul>\n<li>These days I'm a .net/sql software g...,1340,3972,145
22,22,30,3869,2008-08-01T12:25:44.817,Grant,756737fe8cbb545ed58854ff0193cc60,2012-07-31T20:37:07.323,http://beta.stackoverflow.com/badges/22/great-...,Georgia,28.0,<p>Lead (and only) programmer for respectable ...,845,136,8
23,23,32,471,2008-08-01T12:31:17.783,TimM,399ecfe1915ddb853a0421afeccbfa02,2011-10-09T22:12:56.320,http://www.sample.com,Alabama,38.0,I live in meteor crater. I hate ObjC.,98,5,1
24,24,33,5486,2008-08-01T12:32:10.963,John,d0b76ae7bf261316683cad31ba0bad91,2012-07-31T15:26:21.493,NaN,"Southampton, United Kingdom",30.0,<p>Here from the start as Stack Overflow user ...,426,1178,19
25,25,34,7553,2008-08-01T12:39:52.493,Karl Seguin,6f448664cd294829b9ed0cd356f91cb1,2012-02-04T00:55:28.387,http://www.openmymind.net/,"Ottawa, Canada",32.0,"Check out my <a href=""http://tinyurl.com/5jaae...",408,51,9
26,26,35,8520,2008-08-01T12:43:07.713,Greg Hurlman,c03ec7268e3c266e10dff18e61a2498f,2012-07-30T15:47:20.363,http://greghurlman.com,"Howell, NJ",34.0,<p>Technical Lead for .Net and SharePoint at P...,525,392,193
27,27,36,2808,2008-08-01T12:43:55.683,Pat,df0eee24254231e5393a7c5cfc4c3a0e,2012-07-31T22:16:20.847,http://patpack.blogspot.com,"Washington, DC",30.0,<p>I am a C# developer at a Public Relations C...,265,367,9
28,28,37,2177,2008-08-01T12:44:00.723,Wally Lawless,6d7ac6b2dbca2b7ce21dca615d1166ba,2012-07-30T19:45:03.893,http://www.power-coder.net,"Georgetown, Canada",31.0,I am a professional PHP developer working for ...,264,182,10
29,29,38,1363,2008-08-01T12:44:28.833,blcArmadillo,db4342fae89286695afad4c08a272ac1,2012-07-31T18:15:49.997,http://www.ianburris.com,"Detroit, MI",22.0,<p>I'm currently studying computer engineering...,200,74,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295590,1295590,1567174,1,2012-07-31T23:37:24.897,Raja,bff3158d2a6c0888fa00bddc62426409,2012-07-31T23:37:24.897,NaN,NaN,NaN,NaN,0,0,0
1295591,1295591,1567175,6,2012-07-31T23:37:38.583,Brandon,0aea0c92a6bb41685fe459ad33b06198,2012-07-31T23:37:38.583,NaN,NaN,NaN,NaN,0,0,0
1295592,1295592,1567176,1,2012-07-31T23:38:45.880,alfonsob,ebfd18737fe76dfba963bb8ba92debf2,2012-07-31T23:38:45.880,NaN,NaN,NaN,NaN,0,0,0
1295593,1295593,1567177,1,2012-07-31T23:39:35.303,Tomas Valettini,fe5242f665098f8c8975cef34d3cc868,2012-07-31T23:39:35.303,NaN,NaN,NaN,NaN,0,0,0
1295594,1295594,1567178,1,2012-07-31T23:40:04.807,Derek Knox,a8ef9b8e4a68151cdf547bca780c915a,2012-07-31T23:40:04.807,NaN,NaN,NaN,NaN,0,0,0
1295595,1295595,1567179,1,2012-07-31T23:40:09.717,Blake took,eee28c1c79aa4a4338399b933a1c2ab1,2012-08-01T00:36:09.313,NaN,NaN,NaN,NaN,0,0,0
1295596,1295596,1567180,1,2012-07-31T23:40:16.787,Alejo Hinestrosa,5c88cdc7e7939b54966326bde2d8e5f1,2012-07-31T23:40:16.787,NaN,NaN,NaN,NaN,0,0,0
1295597,1295597,1567181,1,2012-07-31T23:41:18.453,user1567181,dedbfacbf9018dea948da1cc761c0e76,2012-08-01T01:23:06.057,NaN,NaN,NaN,NaN,0,0,0
1295598,1295598,1567182,1,2012-07-31T23:41:45.597,user1567182,c5e6d27d303b62c81594ead33a7622a2,2012-07-31T23:57:15.510,NaN,NaN,NaN,NaN,0,0,0
1295599,1295599,1567183,1,2012-07-31T23:42:07.960,Nic Dahlquist,f9de1ba6dee55007993f82f0e5909ca2,2012-08-01T00:48:53.443,NaN,NaN,NaN,NaN,0,0,0
1295600,1295600,1567184,1,2012-07-31T23:44:12.433,user1567184,8079f2a0ef3cb237b102c49741a318d4,2012-08-01T00:48:39.963,NaN,NaN,NaN,NaN,0,0,0
1295601,1295601,1567185,3,2012-07-31T23:44:38.447,user1567185,6356ed8bdb9f7f002a9025d6956f47d0,2012-08-01T01:03:15.960,NaN,NaN,NaN,NaN,0,0,0
1295602,1295602,1567186,3,2012-07-31T23:45:06.600,user1567186,3701f5895191f6b115325164acbbcc27,2012-08-01T01:42:14.800,NaN,NaN,NaN,NaN,0,0,0
1295603,1295603,1567187,1,2012-07-31T23:49:08.307,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,2012-08-01T03:57:45.660,NaN,NaN,NaN,NaN,0,0,0
1295604,1295604,1567188,1,2012-07-31T23:50:16.980,Mazin SW,2857a543cb50b797a15b53620b3646b6,2012-08-01T03:24:15.943,NaN,NaN,NaN,NaN,0,0,0
1295605,1295605,1567189,1,2012-07-31T23:50:47.993,yonathanhalim,3bf1b5619c58d3a93f65a606d3ab694e,2012-08-01T02:28:52.707,NaN,NaN,NaN,NaN,0,0,0
1295606,1295606,1567190,1,2012-07-31T23:50:55.447,Dan,8899bdaf68d119870960f6da5bf0caf1,2012-07-31T23:50:55.447,NaN,NaN,NaN,NaN,0,0,0
1295607,1295607,1567191,1,2012-07-31T23:51:47.147,user1567191,a07621236020f217df42d671c44a8bc5,2012-07-31T23:51:47.147,NaN,NaN,NaN,NaN,0,0,0
1295608,1295608,1567192,1,2012-07-31T23:52:08.227,user1567192,89270f160d0fec957eaf27188905308e,2012-08-01T00:59:43.577,NaN,NaN,NaN,NaN,0,0,0
1295609,1295609,1567193,1,2012-07-31T23:52:45.777,Chris Webb,3681e9910e642a03a482a258938dcd30,2012-08-01T04:47:50.533,NaN,NaN,NaN,NaN,0,0,0
1295610,1295610,1567194,1,2012-07-31T23:53:14.933,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859,2012-08-01T04:07:34.423,NaN,NaN,NaN,NaN,0,0,0
1295611,1295611,1567195,1,2012-07-31T23:53:26.197,SummerDew,d7c17ab89beed7df211dccc61d0db24e,2012-07-31T23:53:26.197,NaN,NaN,NaN,NaN,0,0,0
1295612,1295612,1567196,1,2012-07-31T23:53:40.033,Garrett Miller,e7f8d28c8474f8175c122f5e21c8176b,2012-07-31T23:53:40.033,NaN,NaN,NaN,NaN,0,0,0
1295613,1295613,1567197,1,2012-07-31T23:54:27.930,Konnah Sharp,6c58a7d03e652933089e2141c3cb6fea,2012-07-31T23:54:27.930,NaN,NaN,NaN,NaN,0,0,0
1295614,1295614,1567198,1,2012-07-31T23:56:27.913,jibreel,39bd4523af35728426424615953a35c4,2012-08-01T02:10:31.753,NaN,NaN,NaN,NaN,0,0,0
1295615,1295615,1567199,1,2012-07-31T23:56:39.270,Eduardo Yayo Mancilla Rodrigue,ebd8df4fc27bc165736839e6d02d5253,2012-07-31T23:56:39.270,NaN,NaN,NaN,NaN,0,0,0
1295616,1295616,1567200,1,2012-07-31T23:57:57.770,user1567200,b55180b7e84ea379066fbe6dc9b64a36,2012-08-01T00:55:12.953,NaN,NaN,NaN,NaN,0,0,0
1295617,1295617,1567201,1,2012-07-31T23:58:49.450,Joe Griffin,bc1ccf16df64a0305ed8ea2f700aa71e,2012-08-01T02:47:51.793,NaN,NaN,NaN,NaN,0,0,0
1295618,1295618,1567202,26,2012-07-31T23:59:25.083,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,2012-07-31T23:59:25.083,http://www.microsofttranslator.com/dev,NaN,NaN,NaN,0,0,0
1295619,1295619,1567203,1,2012-07-31T23:59:52.773,Sarah Rose,6154727bd78491ff9f4e60e545be5330,2012-07-31T23:59:52.773,NaN,NaN,NaN,NaN,0,0,0

In [5]:
users.columns = ["sno","id","reputation","creationDate","name","emailHash",
            "lastAccess","websiteUrl","location","age","aboutMe",
            "views","upvotes","downvotes"]

In [6]:
del users['sno']
users

,id,reputation,creationDate,name,emailHash,lastAccess,websiteUrl,location,age,aboutMe,views,upvotes,downvotes
0,-1,1,2008-07-31T00:00:00.000,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,2008-08-26T00:16:53.810,http://stackoverflow.com,on the server farm,NaN,"<p>Hi, I'm not really a person.</p>\r\n<p>I'm ...",649,4310,91092
1,1,21812,2008-07-31T14:22:31.287,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,2012-08-01T04:46:57.447,http://www.codinghorror.com/blog/,"El Cerrito, CA",41.0,"<p><a href=""http://www.codinghorror.com/blog/a...",41072,3090,1279
2,2,1362,2008-07-31T14:22:31.287,Geoff Dalgas,b437f461b3fd27387c5d8ab47a293d35,2012-07-31T23:38:17.330,http://stackoverflow.com,"Corvallis, OR",35.0,<p>Developer on the StackOverflow team. Find ...,7679,430,82
3,3,5584,2008-07-31T14:22:31.287,Jarrod Dixon,2dfa19bf5dc5826c1fe54c2c049a1ff1,2012-07-31T22:49:53.213,http://stackoverflow.com,"New York, NY",33.0,"<p><a href=""http://blog.stackoverflow.com/2009...",8929,3280,67
4,4,16676,2008-07-31T14:22:31.317,Joel Spolsky,d1129adecd8c4e2a22b50605d18e376d,2012-08-01T03:37:02.227,http://www.joelonsoftware.com/,"New York, NY",NaN,<p>I am:</p>\n\n<ul>\n<li>the co-founder and C...,32408,688,91
5,5,20812,2008-07-31T14:22:31.317,Jon Galloway,1c494896dd56e0e27253156c28f1dfb9,2012-07-31T22:31:50.930,http://weblogs.asp.net/jgalloway/,"San Diego, CA",41.0,<p>Community program manager for ASP.NET at Mi...,2962,738,34
6,8,817,2008-07-31T21:33:24.057,Eggs McLaren,c7ec7dec48168d2a7d792e2b0acc78d1,2012-07-20T18:25:48.217,NaN,NaN,NaN,<p>This is a puppet test account I use to vali...,1228,12,9
7,9,4630,2008-07-31T21:35:26.517,Kevin Dente,23c1e2063688620b75b248e08c0d5c24,2012-07-31T23:07:18.440,http://weblogs.asp.net/kdente,"Oakland, CA",41.0,"<p>Self employed software engineer, currently ...",1056,27,4
8,10,101,2008-07-31T21:57:06.240,Sneakers O'Toole,f82fc4a2bfc73434ac4899690926c8a0,2012-06-19T19:35:43.433,http://www.youtube.com/watch?v=qrhNoljPtok,"Lakehead, CA",33.0,I'm not takin' my sneakers off!\r\n<br><br>\r\...,875,0,0
9,11,537,2008-08-01T00:59:11.147,Anonymous User,c510febb9bed68b5cc4a09f076701e0f,2008-08-01T00:59:11.147,NaN,NaN,NaN,NaN,304,0,0
10,13,63611,2008-08-01T04:18:04.943,Chris Jester-Young,729442eea8d8548842a6e0947e333c7b,2012-07-31T22:48:22.820,http://about.me/cky,"Raleigh, NC",32.0,"\n\n<p>Quick links:</p>\n\n<ul>\n<li><a href=""...",3347,3348,123
11,16,313,2008-08-01T12:01:53.023,Rodrigo Sieiro,235da791830e54ec0bfc084800523349,2012-08-01T03:21:30.773,http://twitter.com/rsieiro,Brazil,31.0,You don't know me because I keep a low profile.,279,25,1
12,17,22049,2008-08-01T12:02:21.617,Nick Berardi,42893555ea66c988b51c9167a650d849,2012-08-01T02:00:20.007,http://coderjournal.com,"Collegeville, PA",32.0,<p><strong>email</strong>: nberardi@gmail.com<...,1706,811,193
13,19,404,2008-08-01T12:05:14.233,Mads Kristiansen,4bd8c62d52be7585745a99da8f526d93,2012-03-12T13:10:34.120,NaN,Denmark,38.0,NaN,270,33,10
14,20,4898,2008-08-01T12:09:11.010,Tom,1f0b00b8853cf0311888bb3ed2a77ebc,2012-07-24T15:29:32.373,http://tommcfarlin.com,"Atlanta, GA",NaN,NaN,505,366,38
15,22,3481,2008-08-01T12:11:11.897,maclema,1c23587bf4956c04bb580a6d1310e678,2012-07-31T18:57:39.533,http://www.maclema.com,"Calgary, Canada",26.0,NaN,273,112,5
16,23,977,2008-08-01T12:11:43.703,Jax,41e48d118b55b1bd341141dccacbfeb5,2012-07-31T20:57:47.477,http://jackstrife.com,"Cary, NC",25.0,I'm a young whippersnapper who just got out of...,229,182,2
17,24,428,2008-08-01T12:12:53.453,braklet,b51e14bfee5fd2f1d63c8e2b0ff2f2bb,2012-07-26T21:55:13.853,http://www.google.com/reader/shared/Braklet,"London, United Kingdom",28.0,Code junkie,86,112,0
18,25,5522,2008-08-01T12:15:23.243,CodingWithoutComments,d66009e0e3917e52fbf65b8dc03c2068,2012-05-20T22:46:32.797,http://www.codingwithoutcomments.com,"Seattle, WA",31.0,"a man, a plan, a canal, panama\r\n",1047,519,73
19,26,6234,2008-08-01T12:18:14.520,Shawn,f878a55e08bacee0af48852c29a02dc7,2012-07-31T00:14:51.510,NaN,"San Francisco, CA",28.0,<p>a long time ago i found an xss vuln here an...,2012,556,62
20,27,893,2008-08-01T12:21:40.020,denny,1f5623ff6f4c6ac52bc757a7f03ab6ec,2012-07-30T16:20:09.330,http://www.dennymorrison.net,"Winchester, VA",29.0,"<p>I write shitty, buggy code...but that's oka...",145,288,3
21,29,24640,2008-08-01T12:24:53.820,Michael Haren,f4f4b5a6f27f72b32d42463b1a25e0df,2012-08-01T03:23:28.853,http://blog.wassupy.com/search/label/Technology,Ohio,29.0,<ul>\n<li>These days I'm a .net/sql software g...,1340,3972,145
22,30,3869,2008-08-01T12:25:44.817,Grant,756737fe8cbb545ed58854ff0193cc60,2012-07-31T20:37:07.323,http://beta.stackoverflow.com/badges/22/great-...,Georgia,28.0,<p>Lead (and only) programmer for respectable ...,845,136,8
23,32,471,2008-08-01T12:31:17.783,TimM,399ecfe1915ddb853a0421afeccbfa02,2011-10-09T22:12:56.320,http://www.sample.com,Alabama,38.0,I live in meteor crater. I hate ObjC.,98,5,1
24,33,5486,2008-08-01T12:32:10.963,John,d0b76ae7bf261316683cad31ba0bad91,2012-07-31T15:26:21.493,NaN,"Southampton, United Kingdom",30.0,<p>Here from the start as Stack Overflow user ...,426,1178,19
25,34,7553,2008-08-01T12:39:52.493,Karl Seguin,6f448664cd294829b9ed0cd356f91cb1,2012-02-04T00:55:28.387,http://www.openmymind.net/,"Ottawa, Canada",32.0,"Check out my <a href=""http://tinyurl.com/5jaae...",408,51,9
26,35,8520,2008-08-01T12:43:07.713,Greg Hurlman,c03ec7268e3c266e10dff18e61a2498f,2012-07-30T15:47:20.363,http://greghurlman.com,"Howell, NJ",34.0,<p>Technical Lead for .Net and SharePoint at P...,525,392,193
27,36,2808,2008-08-01T12:43:55.683,Pat,df0eee24254231e5393a7c5cfc4c3a0e,2012-07-31T22:16:20.847,http://patpack.blogspot.com,"Washington, DC",30.0,<p>I am a C# developer at a Public Relations C...,265,367,9
28,37,2177,2008-08-01T12:44:00.723,Wally Lawless,6d7ac6b2dbca2b7ce21dca615d1166ba,2012-07-30T19:45:03.893,http://www.power-coder.net,"Georgetown, Canada",31.0,I am a professional PHP developer working for ...,264,182,10
29,38,1363,2008-08-01T12:44:28.833,blcArmadillo,db4342fae89286695afad4c08a272ac1,2012-07-31T18:15:49.997,http://www.ianburris.com,"Detroit, MI",22.0,<p>I'm currently studying computer engineering...,200,74,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295590,1567174,1,2012-07-31T23:37:24.897,Raja,bff3158d2a6c0888fa00bddc62426409,2012-07-31T23:37:24.897,NaN,NaN,NaN,NaN,0,0,0
1295591,1567175,6,2012-07-31T23:37:38.583,Brandon,0aea0c92a6bb41685fe459ad33b06198,2012-07-31T23:37:38.583,NaN,NaN,NaN,NaN,0,0,0
1295592,1567176,1,2012-07-31T23:38:45.880,alfonsob,ebfd18737fe76dfba963bb8ba92debf2,2012-07-31T23:38:45.880,NaN,NaN,NaN,NaN,0,0,0
1295593,1567177,1,2012-07-31T23:39:35.303,Tomas Valettini,fe5242f665098f8c8975cef34d3cc868,2012-07-31T23:39:35.303,NaN,NaN,NaN,NaN,0,0,0
1295594,1567178,1,2012-07-31T23:40:04.807,Derek Knox,a8ef9b8e4a68151cdf547bca780c915a,2012-07-31T23:40:04.807,NaN,NaN,NaN,NaN,0,0,0
1295595,1567179,1,2012-07-31T23:40:09.717,Blake took,eee28c1c79aa4a4338399b933a1c2ab1,2012-08-01T00:36:09.313,NaN,NaN,NaN,NaN,0,0,0
1295596,1567180,1,2012-07-31T23:40:16.787,Alejo Hinestrosa,5c88cdc7e7939b54966326bde2d8e5f1,2012-07-31T23:40:16.787,NaN,NaN,NaN,NaN,0,0,0
1295597,1567181,1,2012-07-31T23:41:18.453,user1567181,dedbfacbf9018dea948da1cc761c0e76,2012-08-01T01:23:06.057,NaN,NaN,NaN,NaN,0,0,0
1295598,1567182,1,2012-07-31T23:41:45.597,user1567182,c5e6d27d303b62c81594ead33a7622a2,2012-07-31T23:57:15.510,NaN,NaN,NaN,NaN,0,0,0
1295599,1567183,1,2012-07-31T23:42:07.960,Nic Dahlquist,f9de1ba6dee55007993f82f0e5909ca2,2012-08-01T00:48:53.443,NaN,NaN,NaN,NaN,0,0,0
1295600,1567184,1,2012-07-31T23:44:12.433,user1567184,8079f2a0ef3cb237b102c49741a318d4,2012-08-01T00:48:39.963,NaN,NaN,NaN,NaN,0,0,0
1295601,1567185,3,2012-07-31T23:44:38.447,user1567185,6356ed8bdb9f7f002a9025d6956f47d0,2012-08-01T01:03:15.960,NaN,NaN,NaN,NaN,0,0,0
1295602,1567186,3,2012-07-31T23:45:06.600,user1567186,3701f5895191f6b115325164acbbcc27,2012-08-01T01:42:14.800,NaN,NaN,NaN,NaN,0,0,0
1295603,1567187,1,2012-07-31T23:49:08.307,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,2012-08-01T03:57:45.660,NaN,NaN,NaN,NaN,0,0,0
1295604,1567188,1,2012-07-31T23:50:16.980,Mazin SW,2857a543cb50b797a15b53620b3646b6,2012-08-01T03:24:15.943,NaN,NaN,NaN,NaN,0,0,0
1295605,1567189,1,2012-07-31T23:50:47.993,yonathanhalim,3bf1b5619c58d3a93f65a606d3ab694e,2012-08-01T02:28:52.707,NaN,NaN,NaN,NaN,0,0,0
1295606,1567190,1,2012-07-31T23:50:55.447,Dan,8899bdaf68d119870960f6da5bf0caf1,2012-07-31T23:50:55.447,NaN,NaN,NaN,NaN,0,0,0
1295607,1567191,1,2012-07-31T23:51:47.147,user1567191,a07621236020f217df42d671c44a8bc5,2012-07-31T23:51:47.147,NaN,NaN,NaN,NaN,0,0,0
1295608,1567192,1,2012-07-31T23:52:08.227,user1567192,89270f160d0fec957eaf27188905308e,2012-08-01T00:59:43.577,NaN,NaN,NaN,NaN,0,0,0
1295609,1567193,1,2012-07-31T23:52:45.777,Chris Webb,3681e9910e642a03a482a258938dcd30,2012-08-01T04:47:50.533,NaN,NaN,NaN,NaN,0,0,0
1295610,1567194,1,2012-07-31T23:53:14.933,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859,2012-08-01T04:07:34.423,NaN,NaN,NaN,NaN,0,0,0
1295611,1567195,1,2012-07-31T23:53:26.197,SummerDew,d7c17ab89beed7df211dccc61d0db24e,2012-07-31T23:53:26.197,NaN,NaN,NaN,NaN,0,0,0
1295612,1567196,1,2012-07-31T23:53:40.033,Garrett Miller,e7f8d28c8474f8175c122f5e21c8176b,2012-07-31T23:53:40.033,NaN,NaN,NaN,NaN,0,0,0
1295613,1567197,1,2012-07-31T23:54:27.930,Konnah Sharp,6c58a7d03e652933089e2141c3cb6fea,2012-07-31T23:54:27.930,NaN,NaN,NaN,NaN,0,0,0
1295614,1567198,1,2012-07-31T23:56:27.913,jibreel,39bd4523af35728426424615953a35c4,2012-08-01T02:10:31.753,NaN,NaN,NaN,NaN,0,0,0
1295615,1567199,1,2012-07-31T23:56:39.270,Eduardo Yayo Mancilla Rodrigue,ebd8df4fc27bc165736839e6d02d5253,2012-07-31T23:56:39.270,NaN,NaN,NaN,NaN,0,0,0
1295616,1567200,1,2012-07-31T23:57:57.770,user1567200,b55180b7e84ea379066fbe6dc9b64a36,2012-08-01T00:55:12.953,NaN,NaN,NaN,NaN,0,0,0
1295617,1567201,1,2012-07-31T23:58:49.450,Joe Griffin,bc1ccf16df64a0305ed8ea2f700aa71e,2012-08-01T02:47:51.793,NaN,NaN,NaN,NaN,0,0,0
1295618,1567202,26,2012-07-31T23:59:25.083,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,2012-07-31T23:59:25.083,http://www.microsofttranslator.com/dev,NaN,NaN,NaN,0,0,0
1295619,1567203,1,2012-07-31T23:59:52.773,Sarah Rose,6154727bd78491ff9f4e60e545be5330,2012-07-31T23:59:52.773,NaN,NaN,NaN,NaN,0,0,0

In [8]:
users.isnull().sum()

id                    0
reputation            0
creationDate          0
name                 21
emailHash           962
lastAccess            0
websiteUrl      1076408
location        1036808
age             1104184
aboutMe         1150266
views                 0
upvotes               0
downvotes             0
dtype: int64

In [9]:
users.count()

id              1295620
reputation      1295620
creationDate    1295620
name            1295599
emailHash       1294658
lastAccess      1295620
websiteUrl       219212
location         258812
age              191436
aboutMe          145354
views           1295620
upvotes         1295620
downvotes       1295620
dtype: int64

In [10]:
users[users.duplicated(['id'],keep=False)]

Empty DataFrame
Columns: [id, reputation, creationDate, name, emailHash, lastAccess, websiteUrl, location, age, aboutMe, views, upvotes, downvotes]
Index: []

In [11]:
users[users.duplicated(['emailHash'],keep=False)]

,id,reputation,creationDate,name,emailHash,lastAccess,websiteUrl,location,age,aboutMe,views,upvotes,downvotes
0,-1,1,2008-07-31T00:00:00.000,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,2008-08-26T00:16:53.810,http://stackoverflow.com,on the server farm,NaN,"<p>Hi, I'm not really a person.</p>\r\n<p>I'm ...",649,4310,91092
9,11,537,2008-08-01T00:59:11.147,Anonymous User,c510febb9bed68b5cc4a09f076701e0f,2008-08-01T00:59:11.147,NaN,NaN,NaN,NaN,304,0,0
313,398,1579,2008-08-05T12:58:30.643,Tarks,34cb6674ca7f563e04dc7b59b5341431,2012-07-31T13:38:51.753,http://N/A,United Kingdom,24.0,<p>Awesome programmer in training ^_^</p>\n,169,50,9
391,503,43,2008-08-06T12:17:31.037,littlecharva,NaN,2008-08-13T16:29:58.160,NaN,NaN,NaN,NaN,27,0,0
397,511,118,2008-08-06T13:22:48.427,krujos,fd56bf1e535fb8ffa13b9a50b0a63b5b,2012-07-31T21:23:23.453,http://bikefromscratch.com,"St. Paul, MN",32.0,NaN,13,76,0
676,901,86,2008-08-10T09:17:26.837,rotabla,2659d0b4c85e4f89a10025380c1d1cfd,2011-07-27T08:21:49.010,NaN,France,34.0,NaN,5,50,0
684,911,361,2008-08-10T10:05:24.820,winsmith,f398989b8078b09996472999babef592,2008-09-01T09:39:21.050,http://breakthesystem.org,NaN,NaN,NaN,7,0,0
709,941,9014,2008-08-10T21:04:56.673,DannySmurf,349757b58ef056de41d05f48c7266b4f,2012-07-31T21:23:11.447,NaN,"Calgary, Canada",34.0,I am a C#/ASP.NET application developer workin...,320,601,209
738,977,51,2008-08-11T11:11:41.287,Bell,NaN,2008-08-11T14:53:40.710,NaN,United Kingdom,NaN,NaN,6,0,0
779,1028,281,2008-08-11T15:13:14.077,DannySmurf,349757b58ef056de41d05f48c7266b4f,2008-08-11T16:03:38.370,NaN,NaN,NaN,NaN,16,0,0
1012,1357,61,2008-08-14T17:56:13.617,Chris,NaN,2008-08-22T18:50:03.320,NaN,NaN,NaN,NaN,11,0,0
1029,1378,189,2008-08-14T22:37:53.500,GLAF,dbb8cf725e3ad4466d5047ab112518a1,2008-08-15T10:20:02.520,NaN,NaN,NaN,NaN,31,0,0
1051,1408,40,2008-08-15T13:02:14.043,vphomealone,NaN,2008-11-25T21:20:14.057,NaN,NaN,NaN,NaN,18,10,0
1222,1638,7941,2008-08-17T17:58:57.123,mmattax,e3721ccc46e231f7f96be1644b9a6ab4,2012-07-11T12:12:51.063,http://xattam.net,United States,26.0,"<p>Software Developer @ <a href=""http://formst...",520,179,78
1227,1648,164,2008-08-17T18:39:57.837,Yossi Kreinin,NaN,2008-09-05T22:48:02.943,http://yosefk.com,NaN,NaN,NaN,160,0,0
1243,1670,1898,2008-08-17T21:56:17.567,guillermooo,dbb8cf725e3ad4466d5047ab112518a1,2012-08-01T00:28:27.023,NaN,NaN,NaN,Time you enjoyed wasting is not wasted time.,416,232,16
1343,1809,171,2008-08-18T17:04:41.960,Steven Dick,018f6a46d64db65d28b12dd1aa712489,2008-09-04T17:53:28.450,NaN,NaN,NaN,NaN,33,0,0
1453,1956,26,2008-08-19T15:27:25.197,AndyMan,NaN,2008-12-16T23:07:04.277,NaN,NaN,NaN,NaN,16,0,0
1483,1993,156,2008-08-19T18:07:09.447,Andy,78a1712271a5c6a88fb849ce25ac039b,2008-08-29T21:49:00.510,NaN,NaN,NaN,NaN,30,0,0
1527,2057,364,2008-08-20T02:09:33.587,Alex,07a546ad67797414bf1fc8928f7219c0,2008-08-20T02:09:33.587,NaN,NaN,NaN,NaN,63,0,0
1565,2110,21,2008-08-20T12:03:59.960,user2110,NaN,2008-08-20T12:03:59.960,NaN,NaN,NaN,NaN,34,0,0
1569,2116,28,2008-08-20T12:47:31.383,jessilfp,NaN,2008-08-20T18:53:59.690,NaN,NaN,NaN,NaN,0,4,0
1615,2180,207,2008-08-20T19:31:47.870,forrest,6d91a0e619b8564ea40ab3e2eb843c0c,2008-09-08T16:04:00.330,NaN,NaN,NaN,NaN,15,0,0
1698,2308,341,2008-08-21T15:09:06.417,JEzell,NaN,2008-08-22T00:04:01.230,NaN,NaN,NaN,NaN,15,0,0
1925,2668,33,2008-08-24T09:05:30.433,user2668,NaN,2008-10-09T15:04:51.727,NaN,NaN,NaN,NaN,48,0,0
1987,2752,31,2008-08-24T21:36:45.680,user2752,NaN,2008-12-23T07:28:27.430,NaN,NaN,NaN,NaN,19,0,0
2022,2800,233,2008-08-25T08:25:16.933,Journeyman,NaN,2008-09-19T18:52:22.887,NaN,NaN,NaN,NaN,3,2,0
2040,2832,875,2008-08-25T12:57:37.340,Thunder3,0f94df680ad3da6436bd73da3a49ff8f,2012-04-12T15:38:12.890,NaN,California,NaN,NaN,68,14,1
2064,2870,11,2008-08-25T16:54:25.600,user2870,NaN,2008-09-15T11:34:37.567,NaN,NaN,NaN,NaN,5,0,0
2179,3018,1659,2008-08-26T12:12:23.557,Dana,f5eca30f84354773d0e07c8cc97ab7bd,2012-07-31T19:06:39.403,http://none,Maine,33.0,<p>work with C#/ASP.NET and occasionally Share...,343,384,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294999,1566576,1,2012-07-31T18:06:20.363,marcos,b58bc8f94bc5a0d8eaf149abe297a25e,2012-07-31T18:06:20.363,NaN,NaN,NaN,NaN,0,0,0
1295001,1566578,1,2012-07-31T18:06:40.493,Oleg Sherbakov,7d2950b79d754da2eeca4a80dc0aadb9,2012-07-31T22:36:25.627,NaN,Russia,23.0,NaN,0,0,0
1295012,1566589,1,2012-07-31T18:10:13.490,Moh,ce96bc9761d90918df959ef4187769e2,2012-07-31T21:49:43.447,NaN,NaN,NaN,NaN,0,0,0
1295035,1566612,1,2012-07-31T18:20:59.347,Ed Trujillo,219ccfb67c9f500234c5d8ff82e190cf,2012-07-31T22:41:56.820,http://www.contactplus.com,Chicago,NaN,NaN,0,0,0
1295086,1566663,1,2012-07-31T18:43:35.173,Galuvian,e4356476996eca6b89fddbd15a54c060,2012-07-31T18:43:35.173,NaN,NaN,NaN,NaN,0,0,0
1295101,1566680,1,2012-07-31T18:50:13.400,John,c2031b90842dc1b23bc2b0360ba94663,2012-07-31T22:10:44.303,http://at.cg,NaN,NaN,NaN,0,0,0
1295104,1566683,1,2012-07-31T18:52:05.417,raheel khokhar,3189a5a783e7635027b6142e90a50b1b,2012-07-31T19:22:48.430,NaN,NaN,NaN,NaN,0,0,0
1295136,1566715,1,2012-07-31T19:06:52.203,Chirag,aafedb0e16cf9b821bacf7c018308380,2012-07-31T23:14:03.490,NaN,NaN,NaN,NaN,0,0,0
1295141,1566720,1,2012-07-31T19:08:33.997,user1566720,37ad12531ca8d04fae4fce59537aab1c,2012-07-31T19:23:52.003,NaN,NaN,NaN,NaN,0,0,0
1295170,1566750,1,2012-07-31T19:24:04.977,user1566750,dc82c99993b73184e6a17eebd479927b,2012-07-31T23:07:26.420,NaN,NaN,NaN,NaN,0,0,0
1295179,1566759,1,2012-07-31T19:26:34.970,zeta,432dc8d52f68991a2ff876ca772c979c,2012-07-31T19:26:34.970,NaN,NaN,NaN,NaN,0,0,0
1295201,1566781,1,2012-07-31T19:36:20.643,joewright,fd76e01540be5d76f88c9b05c115f30f,2012-07-31T19:36:20.643,NaN,31401,24.0,NaN,0,0,0
1295207,1566788,1,2012-07-31T19:39:59.977,user1566788,99c85972b1915e022bfd3e3fab7044b1,2012-08-01T00:42:25.113,NaN,NaN,NaN,NaN,0,0,0
1295217,1566798,11,2012-07-31T19:44:25.990,parsifal,e7175787cc01b05332e694c3419c9bba,2012-07-31T19:44:25.990,NaN,NaN,NaN,NaN,0,0,0
1295241,1566822,1,2012-07-31T20:02:07.917,Bojan Nikolic,321fba94442462137a44a4824c8d5beb,2012-07-31T20:43:02.263,NaN,NaN,NaN,NaN,0,0,0
1295243,1566824,1,2012-07-31T20:03:20.467,Saswat,f78897082a823502d33f15302e636616,2012-07-31T23:23:05.733,NaN,NaN,NaN,NaN,0,0,0
1295276,1566857,11,2012-07-31T20:20:05.877,roaro,275a2d4051a20238711ff5a354924ad4,2012-07-31T21:49:32.200,NaN,NaN,30.0,NaN,0,0,0
1295310,1566891,1,2012-07-31T20:33:53.440,Bjorn Bjornsson,d5cdef55139e5e731b2f1e6dd8e7fdca,2012-07-31T21:18:00.580,NaN,NaN,NaN,NaN,0,0,0
1295353,1566935,1,2012-07-31T20:57:05.807,user1566935,13a1fdd19b6f32481a1b854e2c6e91e7,2012-08-01T04:31:42.447,NaN,NaN,NaN,NaN,0,0,0
1295356,1566938,1,2012-07-31T20:58:21.523,nathan,91ea010aeb0db8c9c4564e164dcbe4af,2012-07-31T20:58:21.523,NaN,NaN,NaN,NaN,0,0,0
1295364,1566947,1,2012-07-31T21:03:34.063,Rafael Albani,b110d7b2de20d9abad86c20612b087b8,2012-07-31T22:28:36.410,NaN,NaN,NaN,NaN,0,0,0
1295375,1566958,1,2012-07-31T21:08:31.143,user1566958,ef05156e65e0496767209175c747fe1f,2012-07-31T21:23:45.270,NaN,NaN,NaN,NaN,0,0,0
1295443,1567027,1,2012-07-31T21:45:45.370,Jwlyan,3f3d65a86f5fb1203a26ba2a2848a2ff,2012-07-31T21:45:45.370,NaN,NaN,NaN,NaN,0,0,0
1295459,1567043,1,2012-07-31T21:56:47.020,GBreavin,d25f73c9a60387f343140762b13883ba,2012-07-31T21:56:47.020,NaN,NaN,NaN,NaN,0,0,0
1295503,1567087,1,2012-07-31T22:31:13.457,Trisha Hoang,97590710d77ad280da188ffcba2cf1b7,2012-08-01T01:08:09.157,NaN,NaN,NaN,NaN,0,0,0
1295516,1567100,1,2012-07-31T22:39:25.203,262media,8a11eecbb3c08c450723b8edf400d047,2012-07-31T22:39:25.203,http://262media.com,NaN,NaN,NaN,0,0,0
1295525,1567109,1,2012-07-31T22:44:52.377,Jeremy Gwa,674a19cc2cd50025003f4d198bbfa6fb,2012-08-01T01:21:59.913,NaN,NaN,NaN,NaN,0,0,0
1295538,1567122,1,2012-07-31T22:56:09.037,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,2012-07-31T22:56:09.037,NaN,NaN,NaN,NaN,0,0,0
1295555,1567139,1,2012-07-31T23:09:22.520,user1567139,f8cd3a2c074a20aa0ed9148e5d14f84a,2012-07-31T23:50:33.920,NaN,NaN,NaN,NaN,0,0,0
1295607,1567191,1,2012-07-31T23:51:47.147,user1567191,a07621236020f217df42d671c44a8bc5,2012-07-31T23:51:47.147,NaN,NaN,NaN,NaN,0,0,0

In [12]:
comments.isnull().sum()

Id                     0
PostId                 0
Score           11387609
Text                   0
CreationDate           0
UserId             85086
dtype: int64

In [13]:
comments.count()

Id              13252454
PostId          13252454
Score            1864845
Text            13252454
CreationDate    13252454
UserId          13167368
dtype: int64

In [14]:
comments[comments.duplicated(['Id'],keep=False)]

Empty DataFrame
Columns: [Id, PostId, Score, Text, CreationDate, UserId]
Index: []

In [15]:
posts.isnull().sum()

Id                              0
PostTypeId                      0
ParentID                 10338361
AcceptedAnswerId          8189907
CreationDate                    0
Score                           0
ViewCount                 6870821
Body                            0
OwnerUserId                107868
LastEditorUserId          7201283
LastEditorDisplayName    10210119
LastEditDate              7201308
LastActivityDate                0
CommunityOwnedDate       10236474
ClosedDate               10237634
Title                     6884621
Tags                      7160621
AnswerCount               5263440
CommentCount              9498227
dtype: int64

In [16]:
posts.count()

Id                       10338361
PostTypeId               10338361
ParentID                        0
AcceptedAnswerId          2148454
CreationDate             10338361
Score                    10338361
ViewCount                 3467540
Body                     10338361
OwnerUserId              10230493
LastEditorUserId          3137078
LastEditorDisplayName      128242
LastEditDate              3137053
LastActivityDate         10338361
CommunityOwnedDate         101887
ClosedDate                 100727
Title                     3453740
Tags                      3177740
AnswerCount               5074921
CommentCount               840134
dtype: int64

In [17]:
posts[posts.duplicated(['Id'],keep=False)]

Empty DataFrame
Columns: [Id, PostTypeId, ParentID, AcceptedAnswerId, CreationDate, Score, ViewCount, Body, OwnerUserId, LastEditorUserId, LastEditorDisplayName, LastEditDate, LastActivityDate, CommunityOwnedDate, ClosedDate, Title, Tags, AnswerCount, CommentCount]
Index: []

In [38]:
users['id']=users['id'].apply(lambda x:x*1.00)

In [39]:
pd.options.display.float_format = '{:.2f}'.format

In [40]:
posts

,Id,PostTypeId,ParentID,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditorDisplayName,LastEditDate,LastActivityDate,CommunityOwnedDate,ClosedDate,Title,Tags,AnswerCount,CommentCount
0,4,1,nan,7.00,2008-07-31T21:42:52.667,139,9959.00,I'm new to C# and I want to use a track-bar t...,8.00,1039608.00,Rich B,2012-05-04T08:55:46.677,2012-07-24T16:45:40.937,NaN,NaN,<c#><winforms><forms><type-conversion><opacity>,13.00,19.00,14.00
1,6,1,nan,31.00,2008-07-31T22:08:08.620,43,3582.00,I have an absolutely positioned containin...,9.00,483731.00,Rich B,2012-02-26T13:47:20.073,2012-06-04T23:35:58.177,NaN,NaN,<html><css><css3><internet-explorer-7>,5.00,5.00,3.00
2,7,2,nan,nan,2008-07-31T22:17:57.883,127,nan,An explicit cast to double isn't necessary. \...,9.00,1.00,NaN,2010-02-02T19:38:14.493,2010-02-02T19:38:14.493,NaN,NaN,NaN,nan,2.00,nan
3,8,1,nan,162.00,2008-07-31T23:33:19.290,20,1619.00,Are there any conversion tools for porting V...,9.00,1039608.00,Rich B,2012-05-04T08:56:59.720,2012-05-08T19:00:36.850,NaN,NaN,<c#><j#><visualj#>,4.00,0.00,1.00
4,9,1,nan,1404.00,2008-07-31T23:40:59.743,330,87531.00,"Given a representing their birthday, how ...",1.00,861565.00,Rich B,2012-07-30T12:23:37.267,2012-07-30T12:23:37.267,2011-08-16T19:40:43.080,NaN,<c#><.net><datetime>,33.00,5.00,148.00
5,11,1,nan,1248.00,2008-07-31T23:55:37.967,388,37203.00,"Given a specific value, how do I display ...",1.00,1039608.00,Rich B,2012-05-04T08:57:39.843,2012-05-27T17:30:29.780,2009-09-04T13:15:59.820,NaN,<c#><.net><datetime><timespan>,32.00,10.00,277.00
6,12,2,nan,nan,2008-07-31T23:56:41.303,113,nan,"Well, here's how we do it on Stack Overflow. ...",1.00,159270.00,GateKiller,2011-08-08T01:14:13.453,2011-08-08T01:14:13.453,2009-09-04T13:15:59.820,NaN,NaN,nan,9.00,nan
7,13,1,nan,357.00,2008-08-01T00:42:38.903,157,39565.00,Is there a standard way for a Web Server to d...,9.00,1039608.00,Rich B,2012-05-04T08:58:19.547,2012-07-30T08:08:44.750,NaN,NaN,<html><browser><timezone><timezoneoffset>,19.00,2.00,66.00
8,14,1,nan,nan,2008-08-01T00:59:11.177,106,24965.00,What is the difference between and ...,11.00,1039608.00,Rich B,2012-05-04T09:00:49.407,2012-06-07T18:15:14.220,NaN,NaN,<.net><math>,5.00,1.00,17.00
9,16,1,nan,12446.00,2008-08-01T04:59:33.643,23,29386.00,How do you expose a LINQ query as an ASMX ...,2.00,1039608.00,Chris Fournier,2012-05-04T09:01:26.053,2012-05-25T20:48:38.330,NaN,NaN,<c#><linq><web-services><.net-3.5>,5.00,0.00,6.00
10,17,1,nan,26.00,2008-08-01T05:09:55.993,33,4746.00,How do I store binary data in MySQL ? \r\r\n,2.00,546051.00,NaN,2011-10-21T21:29:17.160,2012-06-11T15:07:58.813,NaN,NaN,<mysql><database><binary-data><data-storage>,8.00,0.00,3.00
11,18,2,nan,nan,2008-08-01T05:12:44.193,11,nan,For a table like this: \r\r\n\r\r\n \r\r\...,nan,6068.00,Jeff Atwood,2009-05-28T11:40:35.210,2009-05-28T11:40:35.210,NaN,NaN,NaN,nan,2.00,nan
12,19,1,nan,nan,2008-08-01T05:21:22.257,101,12386.00,Solutions welcome in any language. :-) I'm lo...,13.00,13.00,Chris Jester-Young,2009-08-07T11:45:50.333,2012-07-04T09:04:48.477,2009-02-26T19:22:22.320,NaN,<performance><algorithm><language-agnostic><un...,22.00,9.00,39.00
13,20,2,nan,nan,2008-08-01T07:25:22.443,4,nan,I've used the JLCA (Java Language Conversion...,5.00,nan,NaN,NaN,2008-08-01T07:25:22.443,NaN,NaN,NaN,nan,0.00,nan
14,21,2,nan,nan,2008-08-01T08:57:27.280,5,nan,"Many years ago, to provide an age calculator...",13.00,13.00,Chris Jester-Young,2008-08-01T12:35:11.707,2008-08-01T12:35:11.707,2011-08-16T19:40:43.080,NaN,NaN,nan,0.00,nan
15,22,2,nan,nan,2008-08-01T12:07:19.500,2,nan,The best way that I know of because of leap y...,17.00,17.00,Nick,2008-08-01T15:26:37.087,2008-08-01T15:26:37.087,2011-08-16T19:40:43.080,NaN,NaN,nan,1.00,nan
16,23,1,nan,156.00,2008-08-01T12:09:41.947,23,1013.00,I'm trying to track the progress of PHP 5.3 a...,48.00,367456.00,Mat Scales,2012-06-02T17:39:22.287,2012-06-02T17:39:22.287,NaN,2012-05-18T11:12:42.583,<php>,8.00,0.00,5.00
17,24,1,nan,49.00,2008-08-01T12:12:19.350,24,7722.00,If I have a trigger before the update on a ...,22.00,63550.00,Jim Anderson,2012-05-25T20:50:23.130,2012-06-14T04:32:17.193,NaN,NaN,<mysql><database><triggers>,3.00,0.00,3.00
18,25,1,nan,1443907.00,2008-08-01T12:13:50.207,30,3565.00,I've been having issues getting the C sockets...,23.00,13531.00,NaN,2012-05-25T21:48:23.387,2012-05-25T21:48:23.387,NaN,NaN,<c++><c><sockets><mainframe><zos>,10.00,0.00,0.00
19,26,2,nan,nan,2008-08-01T12:16:22.167,27,nan,The answer by phpguy is correct but I think t...,48.00,48.00,Geoff Dalgas,2012-06-11T15:07:58.813,2012-06-11T15:07:58.813,NaN,NaN,NaN,nan,3.00,nan
20,27,2,nan,nan,2008-08-01T12:17:19.357,7,nan,@jeff \r\r\r\n\r\r\r\n IMHO yours seems a lit...,17.00,17.00,Nick Berardi,2008-08-01T13:16:49.127,2008-08-01T13:16:49.127,2009-09-04T13:15:59.820,NaN,NaN,nan,1.00,nan
21,29,2,nan,nan,2008-08-01T12:19:17.417,8,nan,There are no HTTP headers that will report th...,19.00,nan,NaN,NaN,2008-08-01T12:19:17.417,NaN,NaN,NaN,nan,0.00,nan
22,30,2,nan,nan,2008-08-01T12:22:40.797,4,nan,I've had no trouble using the BSD sockets API...,13.00,nan,NaN,NaN,2008-08-01T12:22:40.797,NaN,NaN,NaN,nan,1.00,nan
23,31,2,nan,nan,2008-08-01T12:22:51.593,23,nan,Does the parent have a defined either...,nan,842480.00,NaN,2012-06-04T23:35:58.177,2012-06-04T23:35:58.177,NaN,NaN,NaN,nan,0.00,nan
24,33,2,nan,nan,2008-08-01T12:26:39.773,172,nan,"rounds down, rounds up, and round...",13.00,13.00,NaN,2009-10-14T02:09:03.030,2009-10-14T02:09:03.030,NaN,NaN,NaN,nan,5.00,nan
25,34,1,nan,nan,2008-08-01T12:30:57.630,16,4179.00,How do I forcefully unload a from memory ...,nan,63550.00,NaN,2012-05-25T21:06:10.223,2012-05-25T21:06:10.223,NaN,NaN,<flex><actionscript-3>,7.00,nan,0.00
26,36,1,nan,352.00,2008-08-01T12:35:56.917,32,10439.00,How can I monitor an SQL Server database for ...,32.00,419.00,Mark Harrison,2012-05-25T23:43:47.697,2012-05-25T23:43:47.697,NaN,NaN,<sql-server><datatable><rdbms>,8.00,0.00,6.00
27,37,2,nan,nan,2008-08-01T12:36:00.957,4,nan,Sure I can post a test app. \r\r\r\n\r\r\r\n ...,23.00,23.00,Jax,2008-08-01T12:42:32.113,2008-08-01T12:42:32.113,NaN,NaN,NaN,nan,0.00,nan
28,39,1,nan,45.00,2008-08-01T12:43:11.503,11,2080.00,I am aware that in .NET there are three tim...,33.00,63550.00,Jim Anderson,2012-05-25T20:55:43.157,2012-05-25T20:55:43.157,NaN,NaN,<c#><.net><vb.net><timer>,2.00,nan,1.00
29,41,2,nan,nan,2008-08-01T12:49:12.413,8,nan,Your best bet are probably these meeting note...,34.00,31671.00,NaN,2010-02-20T23:26:24.063,2010-02-20T23:26:24.063,NaN,NaN,NaN,nan,0.00,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10338331,11750729,1,nan,11750757.00,2012-07-31T23:55:24.683,0,43.00,I'm working on a winform application which cr...,731901.00,731901.00,NaN,2012-08-01T00:24:12.690,2012-08-01T00:24:12.690,NaN,NaN,<c#><winforms>,2.00,2.00,nan
10338332,11750730,2,nan,nan,2012-07-31T23:55:26.770,0,nan,I know of no solution using font-size to modi...,1330275.00,nan,NaN,NaN,2012-07-31T23:55:26.770,NaN,NaN,NaN,nan,nan,nan
10338333,11750731,2,nan,nan,2012-07-31T23:55:29.207,2,nan,The simple answer is you can't. But let me e...,409167.00,nan,NaN,NaN,2012-07-31T23:55:29.207,NaN,NaN,NaN,nan,nan,nan
10338334,11750732,1,nan,nan,2012-07-31T23:55:30.050,0,13.00,"Bear with me please, I'm a new programmer. (t...",1318705.00,1318705.00,NaN,2012-08-01T00:02:53.887,2012-08-01T00:02:53.887,NaN,NaN,<ios><json>,nan,6.00,nan
10338335,11750733,1,nan,nan,2012-07-31T23:55:35.260,0,20.00,I have a codebase that deals with angles quit...,770038.00,nan,NaN,NaN,2012-08-01T00:25:46.087,NaN,NaN,<oop><design-patterns>,2.00,1.00,nan
10338336,11750735,2,nan,nan,2012-07-31T23:55:48.533,0,nan,The short answer to this question is that EF4...,984335.00,nan,NaN,NaN,2012-07-31T23:55:48.533,NaN,NaN,NaN,nan,nan,nan
10338337,11750736,2,nan,nan,2012-07-31T23:55:52.110,2,nan,The is purely the runtime environment nee...,1398245.00,nan,NaN,NaN,2012-07-31T23:55:52.110,NaN,NaN,NaN,nan,1.00,nan
10338338,11750738,1,nan,nan,2012-07-31T23:56:18.193,0,17.00,I've been trying to uncrush PNG's extracted f...,900747.00,nan,NaN,NaN,2012-08-01T00:08:32.853,NaN,NaN,<iphone><ios><ipad><ipa><pngcrush>,1.00,nan,nan
10338339,11750739,1,nan,nan,2012-07-31T23:56:24.543,-6,27.00,Sorry for this not exactly being a coding rel...,1261355.00,nan,NaN,NaN,2012-07-31T23:56:24.543,NaN,NaN,<android><free><ads><paid><monetization>,nan,1.00,nan
10338340,11750740,1,nan,nan,2012-07-31T23:56:54.217,0,9.00,"According to this: ""Important: OAuth 1.0 has ...",841626.00,nan,NaN,NaN,2012-07-31T23:56:54.217,NaN,NaN,<api><google><oauth><google-api><deprecated>,nan,1.00,nan
10338341,11750741,1,nan,11751189.00,2012-07-31T23:56:58.567,0,17.00,Sorry for my bad english \r\r\n\r\r\n i searc...,1472467.00,nan,NaN,NaN,2012-08-01T01:00:47.150,NaN,NaN,<objective-c><arrays><cocos2d-iphone><cocos2d>...,1.00,nan,nan
10338342,11750742,1,nan,11751053.00,2012-07-31T23:57:18.710,0,14.00,Using PunBB on Forumotion the idea was to use...,1567186.00,nan,NaN,NaN,2012-08-01T00:40:30.840,NaN,NaN,<javascript><jquery><string><replace><punbb>,2.00,2.00,nan
10338343,11750743,1,nan,nan,2012-07-31T23:57:30.063,0,20.00,The basic idea of the application I've been w...,539273.00,nan,NaN,NaN,2012-08-01T00:46:01.187,NaN,NaN,<ruby-on-rails><ios><design-patterns><design><...,1.00,nan,nan
10338344,11750744,2,nan,nan,2012-07-31T23:57:56.600,1,nan,"No, this will not work. To have cron execute ...",491094.00,nan,NaN,NaN,2012-07-31T23:57:56.600,NaN,NaN,NaN,nan,1.00,nan
10338345,11750745,2,nan,nan,2012-07-31T23:58:02.943,0,nan,"When displaying your results with MessageBox,...",1504644.00,nan,NaN,NaN,2012-07-31T23:58:02.943,NaN,NaN,NaN,nan,nan,nan
10338346,11750746,1,nan,11750810.00,2012-07-31T23:58:04.573,0,20.00,I've created an XNA application that utilizes...,595437.00,nan,NaN,NaN,2012-08-01T00:05:59.343,NaN,NaN,<.net><xna><lua><extension-methods>,2.00,nan,nan
10338347,11750747,1,nan,nan,2012-07-31T23:58:07.160,0,39.00,After looking over several articles in intern...,1567194.00,1567194.00,NaN,2012-08-01T02:11:19.287,2012-08-01T02:11:19.287,NaN,NaN,<vb.net>,1.00,9.00,nan
10338348,11750748,2,nan,nan,2012-07-31T23:58:11.440,0,nan,I execute scripts as part of an iOS project. ...,775184.00,nan,NaN,NaN,2012-07-31T23:58:11.440,NaN,NaN,NaN,nan,nan,nan
10338349,11750749,2,nan,nan,2012-07-31T23:58:50.220,0,nan,Always check your model functions if they ret...,686733.00,nan,NaN,NaN,2012-07-31T23:58:50.220,NaN,NaN,NaN,nan,1.00,nan
10338350,11750750,2,nan,nan,2012-07-31T23:58:56.213,0,nan,"ah, actually that did work, the complex excep...",517781.00,nan,NaN,NaN,2012-07-31T23:58:56.213,NaN,NaN,NaN,nan,nan,nan
10338351,11750751,2,nan,nan,2012-07-31T23:59:03.527,0,nan,\r\r\n\r\r\n or rather just \r\r\n\r\r\n ...,898266.00,898266.00,NaN,2012-08-01T00:13:55.030,2012-08-01T00:13:55.030,NaN,NaN,NaN,nan,2.00,nan
10338352,11750752,2,nan,nan,2012-07-31T23:59:12.620,0,nan,Maybe this can help: \r\r\n\r\r\n \r\r\n\...,1478722.00,nan,NaN,NaN,2012-07-31T23:59:12.620,NaN,NaN,NaN,nan,nan,nan
10338353,11750753,2,nan,nan,2012-07-31T23:59:25.083,1,nan,GetLanguagesForTranslate() returns the set of...,1567202.00,nan,NaN,NaN,2012-07-31T23:59:25.083,NaN,NaN,NaN,nan,nan,nan
10338354,11750755,1,nan,nan,2012-07-31T23:59:26.430,0,12.00,"I have a table, and here are the relevant...",173630.00,nan,NaN,NaN,2012-08-01T03:30:16.943,NaN,NaN,<sql><postgresql><plpgsql><postgresql-9.1>,2.00,nan,nan
10338355,11750756,2,nan,nan,2012-07-31T23:59:29.873,1,nan,The full error reads \r\r\n\r\r\n \r\r\n\...,582.00,nan,NaN,NaN,2012-07-31T23:59:29.873,NaN,NaN,NaN,nan,nan,nan
10338356,11750757,2,nan,nan,2012-07-31T23:59:38.263,0,nan,You need elevated permissions only to copy to...,141172.00,nan,NaN,NaN,2012-07-31T23:59:38.263,NaN,NaN,NaN,nan,3.00,nan
10338357,11750758,2,nan,nan,2012-07-31T23:59:41.953,1,nan,CodePlex offers free TFS hosting with a featu...,729881.00,nan,NaN,NaN,2012-07-31T23:59:41.953,NaN,NaN,NaN,nan,1.00,nan
10338358,11750759,1,nan,11750812.00,2012-07-31T23:59:41.970,0,9.00,i have a database with 16 fields and i just w...,1492051.00,nan,NaN,NaN,2012-08-01T00:14:18.913,NaN,NaN,<vb.net>,1.00,1.00,nan
10338359,11750760,2,nan,nan,2012-07-31T23:59:49.843,0,nan,Passing it through your compiler with full wa...,898258.00,nan,NaN,NaN,2012-07-31T23:59:49.843,NaN,NaN,NaN,nan,nan,nan
10338360,11750761,1,nan,nan,2012-07-31T23:59:57.380,0,3.00,I cant find any examples online on how to u...,1513192.00,nan,NaN,NaN,2012-07-31T23:59:57.380,NaN,NaN,<python><wxpython><wxwidgets><wx><wxruby>,nan,nan,nan

In [41]:
users

,id,reputation,creationDate,name,emailHash,lastAccess,websiteUrl,location,age,aboutMe,views,upvotes,downvotes
0,-1.00,1,2008-07-31T00:00:00.000,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,2008-08-26T00:16:53.810,http://stackoverflow.com,on the server farm,nan,"<p>Hi, I'm not really a person.</p>\r\n<p>I'm ...",649,4310,91092
1,1.00,21812,2008-07-31T14:22:31.287,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,2012-08-01T04:46:57.447,http://www.codinghorror.com/blog/,"El Cerrito, CA",41.00,"<p><a href=""http://www.codinghorror.com/blog/a...",41072,3090,1279
2,2.00,1362,2008-07-31T14:22:31.287,Geoff Dalgas,b437f461b3fd27387c5d8ab47a293d35,2012-07-31T23:38:17.330,http://stackoverflow.com,"Corvallis, OR",35.00,<p>Developer on the StackOverflow team. Find ...,7679,430,82
3,3.00,5584,2008-07-31T14:22:31.287,Jarrod Dixon,2dfa19bf5dc5826c1fe54c2c049a1ff1,2012-07-31T22:49:53.213,http://stackoverflow.com,"New York, NY",33.00,"<p><a href=""http://blog.stackoverflow.com/2009...",8929,3280,67
4,4.00,16676,2008-07-31T14:22:31.317,Joel Spolsky,d1129adecd8c4e2a22b50605d18e376d,2012-08-01T03:37:02.227,http://www.joelonsoftware.com/,"New York, NY",nan,<p>I am:</p>\n\n<ul>\n<li>the co-founder and C...,32408,688,91
5,5.00,20812,2008-07-31T14:22:31.317,Jon Galloway,1c494896dd56e0e27253156c28f1dfb9,2012-07-31T22:31:50.930,http://weblogs.asp.net/jgalloway/,"San Diego, CA",41.00,<p>Community program manager for ASP.NET at Mi...,2962,738,34
6,8.00,817,2008-07-31T21:33:24.057,Eggs McLaren,c7ec7dec48168d2a7d792e2b0acc78d1,2012-07-20T18:25:48.217,NaN,NaN,nan,<p>This is a puppet test account I use to vali...,1228,12,9
7,9.00,4630,2008-07-31T21:35:26.517,Kevin Dente,23c1e2063688620b75b248e08c0d5c24,2012-07-31T23:07:18.440,http://weblogs.asp.net/kdente,"Oakland, CA",41.00,"<p>Self employed software engineer, currently ...",1056,27,4
8,10.00,101,2008-07-31T21:57:06.240,Sneakers O'Toole,f82fc4a2bfc73434ac4899690926c8a0,2012-06-19T19:35:43.433,http://www.youtube.com/watch?v=qrhNoljPtok,"Lakehead, CA",33.00,I'm not takin' my sneakers off!\r\n<br><br>\r\...,875,0,0
9,11.00,537,2008-08-01T00:59:11.147,Anonymous User,c510febb9bed68b5cc4a09f076701e0f,2008-08-01T00:59:11.147,NaN,NaN,nan,NaN,304,0,0
10,13.00,63611,2008-08-01T04:18:04.943,Chris Jester-Young,729442eea8d8548842a6e0947e333c7b,2012-07-31T22:48:22.820,http://about.me/cky,"Raleigh, NC",32.00,"\n\n<p>Quick links:</p>\n\n<ul>\n<li><a href=""...",3347,3348,123
11,16.00,313,2008-08-01T12:01:53.023,Rodrigo Sieiro,235da791830e54ec0bfc084800523349,2012-08-01T03:21:30.773,http://twitter.com/rsieiro,Brazil,31.00,You don't know me because I keep a low profile.,279,25,1
12,17.00,22049,2008-08-01T12:02:21.617,Nick Berardi,42893555ea66c988b51c9167a650d849,2012-08-01T02:00:20.007,http://coderjournal.com,"Collegeville, PA",32.00,<p><strong>email</strong>: nberardi@gmail.com<...,1706,811,193
13,19.00,404,2008-08-01T12:05:14.233,Mads Kristiansen,4bd8c62d52be7585745a99da8f526d93,2012-03-12T13:10:34.120,NaN,Denmark,38.00,NaN,270,33,10
14,20.00,4898,2008-08-01T12:09:11.010,Tom,1f0b00b8853cf0311888bb3ed2a77ebc,2012-07-24T15:29:32.373,http://tommcfarlin.com,"Atlanta, GA",nan,NaN,505,366,38
15,22.00,3481,2008-08-01T12:11:11.897,maclema,1c23587bf4956c04bb580a6d1310e678,2012-07-31T18:57:39.533,http://www.maclema.com,"Calgary, Canada",26.00,NaN,273,112,5
16,23.00,977,2008-08-01T12:11:43.703,Jax,41e48d118b55b1bd341141dccacbfeb5,2012-07-31T20:57:47.477,http://jackstrife.com,"Cary, NC",25.00,I'm a young whippersnapper who just got out of...,229,182,2
17,24.00,428,2008-08-01T12:12:53.453,braklet,b51e14bfee5fd2f1d63c8e2b0ff2f2bb,2012-07-26T21:55:13.853,http://www.google.com/reader/shared/Braklet,"London, United Kingdom",28.00,Code junkie,86,112,0
18,25.00,5522,2008-08-01T12:15:23.243,CodingWithoutComments,d66009e0e3917e52fbf65b8dc03c2068,2012-05-20T22:46:32.797,http://www.codingwithoutcomments.com,"Seattle, WA",31.00,"a man, a plan, a canal, panama\r\n",1047,519,73
19,26.00,6234,2008-08-01T12:18:14.520,Shawn,f878a55e08bacee0af48852c29a02dc7,2012-07-31T00:14:51.510,NaN,"San Francisco, CA",28.00,<p>a long time ago i found an xss vuln here an...,2012,556,62
20,27.00,893,2008-08-01T12:21:40.020,denny,1f5623ff6f4c6ac52bc757a7f03ab6ec,2012-07-30T16:20:09.330,http://www.dennymorrison.net,"Winchester, VA",29.00,"<p>I write shitty, buggy code...but that's oka...",145,288,3
21,29.00,24640,2008-08-01T12:24:53.820,Michael Haren,f4f4b5a6f27f72b32d42463b1a25e0df,2012-08-01T03:23:28.853,http://blog.wassupy.com/search/label/Technology,Ohio,29.00,<ul>\n<li>These days I'm a .net/sql software g...,1340,3972,145
22,30.00,3869,2008-08-01T12:25:44.817,Grant,756737fe8cbb545ed58854ff0193cc60,2012-07-31T20:37:07.323,http://beta.stackoverflow.com/badges/22/great-...,Georgia,28.00,<p>Lead (and only) programmer for respectable ...,845,136,8
23,32.00,471,2008-08-01T12:31:17.783,TimM,399ecfe1915ddb853a0421afeccbfa02,2011-10-09T22:12:56.320,http://www.sample.com,Alabama,38.00,I live in meteor crater. I hate ObjC.,98,5,1
24,33.00,5486,2008-08-01T12:32:10.963,John,d0b76ae7bf261316683cad31ba0bad91,2012-07-31T15:26:21.493,NaN,"Southampton, United Kingdom",30.00,<p>Here from the start as Stack Overflow user ...,426,1178,19
25,34.00,7553,2008-08-01T12:39:52.493,Karl Seguin,6f448664cd294829b9ed0cd356f91cb1,2012-02-04T00:55:28.387,http://www.openmymind.net/,"Ottawa, Canada",32.00,"Check out my <a href=""http://tinyurl.com/5jaae...",408,51,9
26,35.00,8520,2008-08-01T12:43:07.713,Greg Hurlman,c03ec7268e3c266e10dff18e61a2498f,2012-07-30T15:47:20.363,http://greghurlman.com,"Howell, NJ",34.00,<p>Technical Lead for .Net and SharePoint at P...,525,392,193
27,36.00,2808,2008-08-01T12:43:55.683,Pat,df0eee24254231e5393a7c5cfc4c3a0e,2012-07-31T22:16:20.847,http://patpack.blogspot.com,"Washington, DC",30.00,<p>I am a C# developer at a Public Relations C...,265,367,9
28,37.00,2177,2008-08-01T12:44:00.723,Wally Lawless,6d7ac6b2dbca2b7ce21dca615d1166ba,2012-07-30T19:45:03.893,http://www.power-coder.net,"Georgetown, Canada",31.00,I am a professional PHP developer working for ...,264,182,10
29,38.00,1363,2008-08-01T12:44:28.833,blcArmadillo,db4342fae89286695afad4c08a272ac1,2012-07-31T18:15:49.997,http://www.ianburris.com,"Detroit, MI",22.00,<p>I'm currently studying computer engineering...,200,74,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295590,1567174.00,1,2012-07-31T23:37:24.897,Raja,bff3158d2a6c0888fa00bddc62426409,2012-07-31T23:37:24.897,NaN,NaN,nan,NaN,0,0,0
1295591,1567175.00,6,2012-07-31T23:37:38.583,Brandon,0aea0c92a6bb41685fe459ad33b06198,2012-07-31T23:37:38.583,NaN,NaN,nan,NaN,0,0,0
1295592,1567176.00,1,2012-07-31T23:38:45.880,alfonsob,ebfd18737fe76dfba963bb8ba92debf2,2012-07-31T23:38:45.880,NaN,NaN,nan,NaN,0,0,0
1295593,1567177.00,1,2012-07-31T23:39:35.303,Tomas Valettini,fe5242f665098f8c8975cef34d3cc868,2012-07-31T23:39:35.303,NaN,NaN,nan,NaN,0,0,0
1295594,1567178.00,1,2012-07-31T23:40:04.807,Derek Knox,a8ef9b8e4a68151cdf547bca780c915a,2012-07-31T23:40:04.807,NaN,NaN,nan,NaN,0,0,0
1295595,1567179.00,1,2012-07-31T23:40:09.717,Blake took,eee28c1c79aa4a4338399b933a1c2ab1,2012-08-01T00:36:09.313,NaN,NaN,nan,NaN,0,0,0
1295596,1567180.00,1,2012-07-31T23:40:16.787,Alejo Hinestrosa,5c88cdc7e7939b54966326bde2d8e5f1,2012-07-31T23:40:16.787,NaN,NaN,nan,NaN,0,0,0
1295597,1567181.00,1,2012-07-31T23:41:18.453,user1567181,dedbfacbf9018dea948da1cc761c0e76,2012-08-01T01:23:06.057,NaN,NaN,nan,NaN,0,0,0
1295598,1567182.00,1,2012-07-31T23:41:45.597,user1567182,c5e6d27d303b62c81594ead33a7622a2,2012-07-31T23:57:15.510,NaN,NaN,nan,NaN,0,0,0
1295599,1567183.00,1,2012-07-31T23:42:07.960,Nic Dahlquist,f9de1ba6dee55007993f82f0e5909ca2,2012-08-01T00:48:53.443,NaN,NaN,nan,NaN,0,0,0
1295600,1567184.00,1,2012-07-31T23:44:12.433,user1567184,8079f2a0ef3cb237b102c49741a318d4,2012-08-01T00:48:39.963,NaN,NaN,nan,NaN,0,0,0
1295601,1567185.00,3,2012-07-31T23:44:38.447,user1567185,6356ed8bdb9f7f002a9025d6956f47d0,2012-08-01T01:03:15.960,NaN,NaN,nan,NaN,0,0,0
1295602,1567186.00,3,2012-07-31T23:45:06.600,user1567186,3701f5895191f6b115325164acbbcc27,2012-08-01T01:42:14.800,NaN,NaN,nan,NaN,0,0,0
1295603,1567187.00,1,2012-07-31T23:49:08.307,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,2012-08-01T03:57:45.660,NaN,NaN,nan,NaN,0,0,0
1295604,1567188.00,1,2012-07-31T23:50:16.980,Mazin SW,2857a543cb50b797a15b53620b3646b6,2012-08-01T03:24:15.943,NaN,NaN,nan,NaN,0,0,0
1295605,1567189.00,1,2012-07-31T23:50:47.993,yonathanhalim,3bf1b5619c58d3a93f65a606d3ab694e,2012-08-01T02:28:52.707,NaN,NaN,nan,NaN,0,0,0
1295606,1567190.00,1,2012-07-31T23:50:55.447,Dan,8899bdaf68d119870960f6da5bf0caf1,2012-07-31T23:50:55.447,NaN,NaN,nan,NaN,0,0,0
1295607,1567191.00,1,2012-07-31T23:51:47.147,user1567191,a07621236020f217df42d671c44a8bc5,2012-07-31T23:51:47.147,NaN,NaN,nan,NaN,0,0,0
1295608,1567192.00,1,2012-07-31T23:52:08.227,user1567192,89270f160d0fec957eaf27188905308e,2012-08-01T00:59:43.577,NaN,NaN,nan,NaN,0,0,0
1295609,1567193.00,1,2012-07-31T23:52:45.777,Chris Webb,3681e9910e642a03a482a258938dcd30,2012-08-01T04:47:50.533,NaN,NaN,nan,NaN,0,0,0
1295610,1567194.00,1,2012-07-31T23:53:14.933,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859,2012-08-01T04:07:34.423,NaN,NaN,nan,NaN,0,0,0
1295611,1567195.00,1,2012-07-31T23:53:26.197,SummerDew,d7c17ab89beed7df211dccc61d0db24e,2012-07-31T23:53:26.197,NaN,NaN,nan,NaN,0,0,0
1295612,1567196.00,1,2012-07-31T23:53:40.033,Garrett Miller,e7f8d28c8474f8175c122f5e21c8176b,2012-07-31T23:53:40.033,NaN,NaN,nan,NaN,0,0,0
1295613,1567197.00,1,2012-07-31T23:54:27.930,Konnah Sharp,6c58a7d03e652933089e2141c3cb6fea,2012-07-31T23:54:27.930,NaN,NaN,nan,NaN,0,0,0
1295614,1567198.00,1,2012-07-31T23:56:27.913,jibreel,39bd4523af35728426424615953a35c4,2012-08-01T02:10:31.753,NaN,NaN,nan,NaN,0,0,0
1295615,1567199.00,1,2012-07-31T23:56:39.270,Eduardo Yayo Mancilla Rodrigue,ebd8df4fc27bc165736839e6d02d5253,2012-07-31T23:56:39.270,NaN,NaN,nan,NaN,0,0,0
1295616,1567200.00,1,2012-07-31T23:57:57.770,user1567200,b55180b7e84ea379066fbe6dc9b64a36,2012-08-01T00:55:12.953,NaN,NaN,nan,NaN,0,0,0
1295617,1567201.00,1,2012-07-31T23:58:49.450,Joe Griffin,bc1ccf16df64a0305ed8ea2f700aa71e,2012-08-01T02:47:51.793,NaN,NaN,nan,NaN,0,0,0
1295618,1567202.00,26,2012-07-31T23:59:25.083,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,2012-07-31T23:59:25.083,http://www.microsofttranslator.com/dev,NaN,nan,NaN,0,0,0
1295619,1567203.00,1,2012-07-31T23:59:52.773,Sarah Rose,6154727bd78491ff9f4e60e545be5330,2012-07-31T23:59:52.773,NaN,NaN,nan,NaN,0,0,0

In [23]:
merged_users_posts = pd.merge(left=users,right=posts,how='inner', left_on='id', right_on='OwnerUserId')
merged_users_posts.shape

(10230493, 32)

In [ ]:
merged_users_posts.to_csv('merged_users_posts_whole.csv')

In [11]:
m_users=users[['id','name','emailHash']]
m_users

,id,name,emailHash
0,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e
1,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8
2,2.00,Geoff Dalgas,b437f461b3fd27387c5d8ab47a293d35
3,3.00,Jarrod Dixon,2dfa19bf5dc5826c1fe54c2c049a1ff1
4,4.00,Joel Spolsky,d1129adecd8c4e2a22b50605d18e376d
5,5.00,Jon Galloway,1c494896dd56e0e27253156c28f1dfb9
6,8.00,Eggs McLaren,c7ec7dec48168d2a7d792e2b0acc78d1
7,9.00,Kevin Dente,23c1e2063688620b75b248e08c0d5c24
8,10.00,Sneakers O'Toole,f82fc4a2bfc73434ac4899690926c8a0
9,11.00,Anonymous User,c510febb9bed68b5cc4a09f076701e0f
10,13.00,Chris Jester-Young,729442eea8d8548842a6e0947e333c7b
11,16.00,Rodrigo Sieiro,235da791830e54ec0bfc084800523349
12,17.00,Nick Berardi,42893555ea66c988b51c9167a650d849
13,19.00,Mads Kristiansen,4bd8c62d52be7585745a99da8f526d93
14,20.00,Tom,1f0b00b8853cf0311888bb3ed2a77ebc
15,22.00,maclema,1c23587bf4956c04bb580a6d1310e678
16,23.00,Jax,41e48d118b55b1bd341141dccacbfeb5
17,24.00,braklet,b51e14bfee5fd2f1d63c8e2b0ff2f2bb
18,25.00,CodingWithoutComments,d66009e0e3917e52fbf65b8dc03c2068
19,26.00,Shawn,f878a55e08bacee0af48852c29a02dc7
20,27.00,denny,1f5623ff6f4c6ac52bc757a7f03ab6ec
21,29.00,Michael Haren,f4f4b5a6f27f72b32d42463b1a25e0df
22,30.00,Grant,756737fe8cbb545ed58854ff0193cc60
23,32.00,TimM,399ecfe1915ddb853a0421afeccbfa02
24,33.00,John,d0b76ae7bf261316683cad31ba0bad91
25,34.00,Karl Seguin,6f448664cd294829b9ed0cd356f91cb1
26,35.00,Greg Hurlman,c03ec7268e3c266e10dff18e61a2498f
27,36.00,Pat,df0eee24254231e5393a7c5cfc4c3a0e
28,37.00,Wally Lawless,6d7ac6b2dbca2b7ce21dca615d1166ba
29,38.00,blcArmadillo,db4342fae89286695afad4c08a272ac1
...,...,...,...
1295590,1567174.00,Raja,bff3158d2a6c0888fa00bddc62426409
1295591,1567175.00,Brandon,0aea0c92a6bb41685fe459ad33b06198
1295592,1567176.00,alfonsob,ebfd18737fe76dfba963bb8ba92debf2
1295593,1567177.00,Tomas Valettini,fe5242f665098f8c8975cef34d3cc868
1295594,1567178.00,Derek Knox,a8ef9b8e4a68151cdf547bca780c915a
1295595,1567179.00,Blake took,eee28c1c79aa4a4338399b933a1c2ab1
1295596,1567180.00,Alejo Hinestrosa,5c88cdc7e7939b54966326bde2d8e5f1
1295597,1567181.00,user1567181,dedbfacbf9018dea948da1cc761c0e76
1295598,1567182.00,user1567182,c5e6d27d303b62c81594ead33a7622a2
1295599,1567183.00,Nic Dahlquist,f9de1ba6dee55007993f82f0e5909ca2
1295600,1567184.00,user1567184,8079f2a0ef3cb237b102c49741a318d4
1295601,1567185.00,user1567185,6356ed8bdb9f7f002a9025d6956f47d0
1295602,1567186.00,user1567186,3701f5895191f6b115325164acbbcc27
1295603,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0
1295604,1567188.00,Mazin SW,2857a543cb50b797a15b53620b3646b6
1295605,1567189.00,yonathanhalim,3bf1b5619c58d3a93f65a606d3ab694e
1295606,1567190.00,Dan,8899bdaf68d119870960f6da5bf0caf1
1295607,1567191.00,user1567191,a07621236020f217df42d671c44a8bc5
1295608,1567192.00,user1567192,89270f160d0fec957eaf27188905308e
1295609,1567193.00,Chris Webb,3681e9910e642a03a482a258938dcd30
1295610,1567194.00,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859
1295611,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e
1295612,1567196.00,Garrett Miller,e7f8d28c8474f8175c122f5e21c8176b
1295613,1567197.00,Konnah Sharp,6c58a7d03e652933089e2141c3cb6fea
1295614,1567198.00,jibreel,39bd4523af35728426424615953a35c4
1295615,1567199.00,Eduardo Yayo Mancilla Rodrigue,ebd8df4fc27bc165736839e6d02d5253
1295616,1567200.00,user1567200,b55180b7e84ea379066fbe6dc9b64a36
1295617,1567201.00,Joe Griffin,bc1ccf16df64a0305ed8ea2f700aa71e
1295618,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb
1295619,1567203.00,Sarah Rose,6154727bd78491ff9f4e60e545be5330

In [12]:
m_posts=posts[['OwnerUserId','PostTypeId','CreationDate','Id']]
m_posts

          OwnerUserId  PostTypeId             CreationDate        Id
0                8.00           1  2008-07-31T21:42:52.667         4
1                9.00           1  2008-07-31T22:08:08.620         6
2                9.00           2  2008-07-31T22:17:57.883         7
3                9.00           1  2008-07-31T23:33:19.290         8
4                1.00           1  2008-07-31T23:40:59.743         9
5                1.00           1  2008-07-31T23:55:37.967        11
6                1.00           2  2008-07-31T23:56:41.303        12
7                9.00           1  2008-08-01T00:42:38.903        13
8               11.00           1  2008-08-01T00:59:11.177        14
9                2.00           1  2008-08-01T04:59:33.643        16
10               2.00           1  2008-08-01T05:09:55.993        17
11                nan           2  2008-08-01T05:12:44.193        18
12              13.00           1  2008-08-01T05:21:22.257        19
13               5.00           2  2008-08-01T07:25:22.443        20
14              13.00           2  2008-08-01T08:57:27.280        21
15              17.00           2  2008-08-01T12:07:19.500        22
16              48.00           1  2008-08-01T12:09:41.947        23
17              22.00           1  2008-08-01T12:12:19.350        24
18              23.00           1  2008-08-01T12:13:50.207        25
19              48.00           2  2008-08-01T12:16:22.167        26
20              17.00           2  2008-08-01T12:17:19.357        27
21              19.00           2  2008-08-01T12:19:17.417        29
22              13.00           2  2008-08-01T12:22:40.797        30
23                nan           2  2008-08-01T12:22:51.593        31
24              13.00           2  2008-08-01T12:26:39.773        33
25                nan           1  2008-08-01T12:30:57.630        34
26              32.00           1  2008-08-01T12:35:56.917        36
27              23.00           2  2008-08-01T12:36:00.957        37
28              33.00           1  2008-08-01T12:43:11.503        39
29              34.00           2  2008-08-01T12:49:12.413        41
...               ...         ...                      ...       ...
10338331    731901.00           1  2012-07-31T23:55:24.683  11750729
10338332   1330275.00           2  2012-07-31T23:55:26.770  11750730
10338333    409167.00           2  2012-07-31T23:55:29.207  11750731
10338334   1318705.00           1  2012-07-31T23:55:30.050  11750732
10338335    770038.00           1  2012-07-31T23:55:35.260  11750733
10338336    984335.00           2  2012-07-31T23:55:48.533  11750735
10338337   1398245.00           2  2012-07-31T23:55:52.110  11750736
10338338    900747.00           1  2012-07-31T23:56:18.193  11750738
10338339   1261355.00           1  2012-07-31T23:56:24.543  11750739
10338340    841626.00           1  2012-07-31T23:56:54.217  11750740
10338341   1472467.00           1  2012-07-31T23:56:58.567  11750741
10338342   1567186.00           1  2012-07-31T23:57:18.710  11750742
10338343    539273.00           1  2012-07-31T23:57:30.063  11750743
10338344    491094.00           2  2012-07-31T23:57:56.600  11750744
10338345   1504644.00           2  2012-07-31T23:58:02.943  11750745
10338346    595437.00           1  2012-07-31T23:58:04.573  11750746
10338347   1567194.00           1  2012-07-31T23:58:07.160  11750747
10338348    775184.00           2  2012-07-31T23:58:11.440  11750748
10338349    686733.00           2  2012-07-31T23:58:50.220  11750749
10338350    517781.00           2  2012-07-31T23:58:56.213  11750750
10338351    898266.00           2  2012-07-31T23:59:03.527  11750751
10338352   1478722.00           2  2012-07-31T23:59:12.620  11750752
10338353   1567202.00           2  2012-07-31T23:59:25.083  11750753
10338354    173630.00           1  2012-07-31T23:59:26.430  11750755
10338355       582.00           2  2012-07-31T23:59:29.873  11750756
10338356    141172.00           2  2012-07-31T23:59:38.263  11750757
10338357    729881.00           2  2012-07-31T23:59:41.953  11750758
10338358   1492051.00           1  2012-07-31T23:59:41.970  11750759
10338359    898258.00           2  2012-07-31T23:59:49.843  11750760
10338360   1513192.00           1  2012-07-31T23:59:57.380  11750761

[10338361 rows x 4 columns]

In [13]:
m_users_posts = pd.merge(left=m_users,right=m_posts,how='inner', left_on='id', right_on='OwnerUserId')
m_users_posts.shape

(10230493, 7)

In [19]:
m_users_posts.to_csv('merged_users_posts_whole_1.csv')

In [15]:
m_users_posts[m_users_posts.duplicated(['Id'],keep=False)]

Empty DataFrame
Columns: [id, name, emailHash, OwnerUserId, PostTypeId, CreationDate, Id]
Index: []

In [16]:
m_users_posts.isnull().sum()

id                 0
name             231
emailHash       2301
OwnerUserId        0
PostTypeId         0
CreationDate       0
Id                 0
dtype: int64

In [17]:
m_users_posts[m_users_posts['id'] != m_users_posts['OwnerUserId']].count()

id              0
name            0
emailHash       0
OwnerUserId     0
PostTypeId      0
CreationDate    0
Id              0
dtype: int64

In [18]:
s_users_posts = m_users_posts.sort_values(by=['OwnerUserId','CreationDate'], ascending=[True,True])
s_users_posts

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id
32,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T07:35:31.060,3607476
21,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:17:51.803,3607052
25,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:45:59.633,3607228
2,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:48:17.037,3607007
9,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:49:10.483,3607030
35,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T10:36:15.080,3607484
30,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T10:57:34.840,3607365
119,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T11:37:15.443,3610293
4,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T11:37:35.990,3607013
7,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:35:01.460,3607017
5,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:45:03.020,3607014
292,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:53:03.237,3625095
293,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,4,2010-07-22T12:53:03.237,3625096
19,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:56:33.970,3607049
152,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:57:31.333,3617964
0,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T13:36:17.203,3606997
59,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T13:46:37.380,3607588
8,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T14:17:07.700,3607018
85,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T14:33:28.080,3607770
22,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T14:44:16.900,3607053
53,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T15:33:45.897,3607531
15,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T17:14:10.223,3607042
73,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T17:16:23.833,3607689
108,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T17:51:24.860,3609445
116,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,3,2010-07-22T18:39:58.787,3609905
370,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T18:52:44.253,3625191
371,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,4,2010-07-22T18:52:44.253,3625192
92,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T19:59:57.740,3608598
82,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T20:16:22.867,3607736
17,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T21:52:12.340,3607044
...,...,...,...,...,...,...,...
10230463,1567107.00,Gareth Bowen,378ba4d326f85281ace0735410a67bd5,1567107.00,1,2012-07-31T23:10:18.157,11750349
10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119
10230465,1567109.00,Jeremy Gwa,674a19cc2cd50025003f4d198bbfa6fb,1567109.00,1,2012-07-31T22:51:09.377,11750171
10230466,1567109.00,Jeremy Gwa,674a19cc2cd50025003f4d198bbfa6fb,1567109.00,1,2012-07-31T23:23:59.020,11750471
10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153
10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175
10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211
10230470,1567123.00,Eric Philmore,2497667570de1a14d49d7965f48328ba,1567123.00,1,2012-07-31T23:06:09.733,11750312
10230471,1567124.00,DeekMan,0b875468b8aa885867c9e36efd1a2ff8,1567124.00,1,2012-07-31T23:38:37.877,11750608
10230472,1567130.00,user1567130,b7cec2c453a5a2b5c0ddfbb5633493c7,1567130.00,1,2012-07-31T23:26:12.880,11750501
10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269
10230474,1567134.00,ben,e1a4c358edf6f5562b83c09e086e0eb3,1567134.00,1,2012-07-31T23:18:41.547,11750424
10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320
10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357
10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374
10230478,1567149.00,Tom Androy,47e7eefe52a528eda86d3f857777606d,1567149.00,1,2012-07-31T23:52:54.200,11750707
10230479,1567150.00,Lyndsay Moon,130cc668c1b92496e96f8c5a4d123063,1567150.00,1,2012-07-31T23:25:20.323,11750491
10230480,1567164.00,Suyu Zhang,0edf4b6fd29f2e6ab8761c9e4bd3b352,1567164.00,1,2012-07-31T23:40:02.323,11750621
10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536
10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614
10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564
10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566
10230485,1567174.00,Raja,bff3158d2a6c0888fa00bddc62426409,1567174.00,1,2012-07-31T23:44:55.367,11750654
10230486,1567175.00,Brandon,0aea0c92a6bb41685fe459ad33b06198,1567175.00,1,2012-07-31T23:41:43.107,11750631
10230487,1567179.00,Blake took,eee28c1c79aa4a4338399b933a1c2ab1,1567179.00,1,2012-07-31T23:54:29.380,11750719
10230488,1567186.00,user1567186,3701f5895191f6b115325164acbbcc27,1567186.00,1,2012-07-31T23:57:18.710,11750742
10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685
10230490,1567194.00,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859,1567194.00,1,2012-07-31T23:58:07.160,11750747
10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711
10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753

In [20]:
import dateutil.parser

In [21]:
import datetime

In [22]:
s_ans_users_posts = s_users_posts.loc[s_users_posts['PostTypeId'] == 2]
s_ans_users_posts

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id
26357,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-07-31T23:56:41.303,12
26358,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T02:45:07.717,986
26359,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T04:31:02.557,1016
26360,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T08:04:41.737,1074
26361,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-05T12:01:32.227,2135
26362,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-10T08:28:52.100,7099
26363,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-11T19:23:47.160,8116
26364,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T00:30:43.390,8368
26366,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T05:02:49.453,8474
26367,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:13:41.470,9310
26368,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:27:54.093,9318
26369,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T01:52:36.670,9400
26370,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T03:30:58.860,9446
26371,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T06:14:11.197,9507
26372,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T12:03:05.940,9685
26373,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:10:22.660,10614
26374,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:13:56.770,10617
26375,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:17:18.153,10623
26376,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T13:48:02.523,11034
26377,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T02:58:18.083,13486
26378,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T03:00:34.317,13488
26379,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-18T13:29:55.687,14587
26380,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-19T16:51:17.103,16532
26382,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-24T23:40:09.253,25456
26383,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T00:11:43.763,25486
26384,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T13:43:41.643,26046
26385,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-27T13:08:30.010,30034
26386,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T11:23:59.427,32021
26387,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T13:26:27.823,32254
26388,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-09-01T12:03:30.520,37817
...,...,...,...,...,...,...,...
10230403,1566944.00,PahanCS,d9e2b0fec26ae9743462b20ae0f69ffd,1566944.00,2,2012-07-31T21:02:30.597,11748957
10230404,1566946.00,Srinivasan,6b3e106fe114714bdad9657f04b64138,1566946.00,2,2012-07-31T21:03:19.733,11748968
10230409,1566963.00,Manny in Cape Town,917eb7a84d44444da687ef4d0b7078d7,1566963.00,2,2012-07-31T21:11:55.417,11749076
10230414,1566981.00,Luke,1f4abdc335ee20a5d652aa8cfbed1cd2,1566981.00,2,2012-07-31T21:20:54.430,11749183
10230415,1566983.00,dbsx,595734cb022c9368f2d7f4ccfec7c46d,1566983.00,2,2012-07-31T21:57:21.443,11749608
10230422,1567003.00,mfc,cc5dd9ffd9a4599efd6eb29069eb57e9,1567003.00,2,2012-07-31T21:32:15.223,11749330
10230434,1567046.00,Chris X,a83ec9a7cfab407f766ff20f0a505d0f,1567046.00,2,2012-07-31T21:59:58.937,11749638
10230435,1567047.00,ehernandez,ade9d8ce17e3009005ea4fca75c7b184,1567047.00,2,2012-07-31T22:16:04.053,11749819
10230439,1567058.00,StackTest,091419e676e6f6d1bce069cc0ea994f9,1567058.00,2,2012-07-31T22:07:05.393,11749721
10230443,1567067.00,Chuck,d1054eddee873dc403637d7921dceeb5,1567067.00,2,2012-07-31T22:14:40.697,11749794
10230450,1567080.00,DuncanDavies,94714775a44c3c2768f3e69cc5c6b2b8,1567080.00,2,2012-07-31T22:30:08.300,11749970
10230455,1567089.00,Oblivion,39592f05c7c22fec180bc5d44391b1b9,1567089.00,2,2012-07-31T22:32:01.930,11749989
10230456,1567091.00,RyanHilliker,dadd09b47fb4445a85368407ddb7953e,1567091.00,2,2012-07-31T22:33:07.517,11750002
10230460,1567100.00,262media,8a11eecbb3c08c450723b8edf400d047,1567100.00,2,2012-07-31T22:39:25.203,11750065
10230462,1567106.00,Weslley S. Pereira,300c9c80adb08b4e97a64f1716827418,1567106.00,2,2012-07-31T22:44:33.157,11750116
10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119
10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153
10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175
10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211
10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269
10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320
10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357
10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374
10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536
10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614
10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564
10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566
10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685
10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711
10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753

In [23]:
s_ans_users_posts1 = s_ans_users_posts.sort_values(by=['OwnerUserId','CreationDate'], ascending=[True,True])

In [24]:
s_ans_users_posts1.head(20)

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id
26357,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-07-31T23:56:41.303,12
26358,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T02:45:07.717,986
26359,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T04:31:02.557,1016
26360,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T08:04:41.737,1074
26361,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-05T12:01:32.227,2135
26362,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-10T08:28:52.100,7099
26363,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-11T19:23:47.160,8116
26364,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T00:30:43.390,8368
26366,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T05:02:49.453,8474
26367,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:13:41.470,9310
26368,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:27:54.093,9318
26369,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T01:52:36.670,9400
26370,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T03:30:58.860,9446
26371,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T06:14:11.197,9507
26372,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T12:03:05.940,9685
26373,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:10:22.660,10614
26374,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:13:56.770,10617
26375,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:17:18.153,10623
26376,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T13:48:02.523,11034
26377,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T02:58:18.083,13486

### number of posts which are not answers

In [25]:
10230493 - 6803342

3427151

In [26]:
s_ans_users_posts['timestamp'] = s_ans_users_posts['CreationDate'].apply(dateutil.parser.parse)

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [27]:
s_ans_users_posts

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id,timestamp
26357,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-07-31T23:56:41.303,12,2008-07-31 23:56:41.303
26358,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T02:45:07.717,986,2008-08-04 02:45:07.717
26359,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T04:31:02.557,1016,2008-08-04 04:31:02.557
26360,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T08:04:41.737,1074,2008-08-04 08:04:41.737
26361,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-05T12:01:32.227,2135,2008-08-05 12:01:32.227
26362,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-10T08:28:52.100,7099,2008-08-10 08:28:52.100
26363,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-11T19:23:47.160,8116,2008-08-11 19:23:47.160
26364,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T00:30:43.390,8368,2008-08-12 00:30:43.390
26366,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T05:02:49.453,8474,2008-08-12 05:02:49.453
26367,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:13:41.470,9310,2008-08-12 23:13:41.470
26368,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:27:54.093,9318,2008-08-12 23:27:54.093
26369,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T01:52:36.670,9400,2008-08-13 01:52:36.670
26370,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T03:30:58.860,9446,2008-08-13 03:30:58.860
26371,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T06:14:11.197,9507,2008-08-13 06:14:11.197
26372,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T12:03:05.940,9685,2008-08-13 12:03:05.940
26373,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:10:22.660,10614,2008-08-14 03:10:22.660
26374,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:13:56.770,10617,2008-08-14 03:13:56.770
26375,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:17:18.153,10623,2008-08-14 03:17:18.153
26376,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T13:48:02.523,11034,2008-08-14 13:48:02.523
26377,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T02:58:18.083,13486,2008-08-17 02:58:18.083
26378,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T03:00:34.317,13488,2008-08-17 03:00:34.317
26379,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-18T13:29:55.687,14587,2008-08-18 13:29:55.687
26380,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-19T16:51:17.103,16532,2008-08-19 16:51:17.103
26382,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-24T23:40:09.253,25456,2008-08-24 23:40:09.253
26383,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T00:11:43.763,25486,2008-08-25 00:11:43.763
26384,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T13:43:41.643,26046,2008-08-25 13:43:41.643
26385,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-27T13:08:30.010,30034,2008-08-27 13:08:30.010
26386,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T11:23:59.427,32021,2008-08-28 11:23:59.427
26387,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T13:26:27.823,32254,2008-08-28 13:26:27.823
26388,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-09-01T12:03:30.520,37817,2008-09-01 12:03:30.520
...,...,...,...,...,...,...,...,...
10230403,1566944.00,PahanCS,d9e2b0fec26ae9743462b20ae0f69ffd,1566944.00,2,2012-07-31T21:02:30.597,11748957,2012-07-31 21:02:30.597
10230404,1566946.00,Srinivasan,6b3e106fe114714bdad9657f04b64138,1566946.00,2,2012-07-31T21:03:19.733,11748968,2012-07-31 21:03:19.733
10230409,1566963.00,Manny in Cape Town,917eb7a84d44444da687ef4d0b7078d7,1566963.00,2,2012-07-31T21:11:55.417,11749076,2012-07-31 21:11:55.417
10230414,1566981.00,Luke,1f4abdc335ee20a5d652aa8cfbed1cd2,1566981.00,2,2012-07-31T21:20:54.430,11749183,2012-07-31 21:20:54.430
10230415,1566983.00,dbsx,595734cb022c9368f2d7f4ccfec7c46d,1566983.00,2,2012-07-31T21:57:21.443,11749608,2012-07-31 21:57:21.443
10230422,1567003.00,mfc,cc5dd9ffd9a4599efd6eb29069eb57e9,1567003.00,2,2012-07-31T21:32:15.223,11749330,2012-07-31 21:32:15.223
10230434,1567046.00,Chris X,a83ec9a7cfab407f766ff20f0a505d0f,1567046.00,2,2012-07-31T21:59:58.937,11749638,2012-07-31 21:59:58.937
10230435,1567047.00,ehernandez,ade9d8ce17e3009005ea4fca75c7b184,1567047.00,2,2012-07-31T22:16:04.053,11749819,2012-07-31 22:16:04.053
10230439,1567058.00,StackTest,091419e676e6f6d1bce069cc0ea994f9,1567058.00,2,2012-07-31T22:07:05.393,11749721,2012-07-31 22:07:05.393
10230443,1567067.00,Chuck,d1054eddee873dc403637d7921dceeb5,1567067.00,2,2012-07-31T22:14:40.697,11749794,2012-07-31 22:14:40.697
10230450,1567080.00,DuncanDavies,94714775a44c3c2768f3e69cc5c6b2b8,1567080.00,2,2012-07-31T22:30:08.300,11749970,2012-07-31 22:30:08.300
10230455,1567089.00,Oblivion,39592f05c7c22fec180bc5d44391b1b9,1567089.00,2,2012-07-31T22:32:01.930,11749989,2012-07-31 22:32:01.930
10230456,1567091.00,RyanHilliker,dadd09b47fb4445a85368407ddb7953e,1567091.00,2,2012-07-31T22:33:07.517,11750002,2012-07-31 22:33:07.517
10230460,1567100.00,262media,8a11eecbb3c08c450723b8edf400d047,1567100.00,2,2012-07-31T22:39:25.203,11750065,2012-07-31 22:39:25.203
10230462,1567106.00,Weslley S. Pereira,300c9c80adb08b4e97a64f1716827418,1567106.00,2,2012-07-31T22:44:33.157,11750116,2012-07-31 22:44:33.157
10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119,2012-07-31 22:44:46.437
10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153,2012-07-31 22:49:08.643
10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175,2012-07-31 22:52:01.630
10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211,2012-07-31 22:56:09.037
10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269,2012-07-31 23:01:32.390
10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320,2012-07-31 23:07:21.073
10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357,2012-07-31 23:11:26.800
10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374,2012-07-31 23:12:56.433
10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536,2012-07-31 23:29:52.760
10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614,2012-07-31 23:38:52.320
10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564,2012-07-31 23:33:21.643
10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566,2012-07-31 23:33:50.723
10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685,2012-07-31 23:49:08.307
10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711,2012-07-31 23:53:26.197
10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753,2012-07-31 23:59:25.083

In [30]:
sd_ans_users_posts = s_ans_users_posts.sort_values(by=['OwnerUserId','timestamp'], ascending=[True,True])

In [31]:
sd_ans_users_posts

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id,timestamp
26357,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-07-31T23:56:41.303,12,2008-07-31 23:56:41.303
26358,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T02:45:07.717,986,2008-08-04 02:45:07.717
26359,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T04:31:02.557,1016,2008-08-04 04:31:02.557
26360,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T08:04:41.737,1074,2008-08-04 08:04:41.737
26361,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-05T12:01:32.227,2135,2008-08-05 12:01:32.227
26362,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-10T08:28:52.100,7099,2008-08-10 08:28:52.100
26363,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-11T19:23:47.160,8116,2008-08-11 19:23:47.160
26364,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T00:30:43.390,8368,2008-08-12 00:30:43.390
26366,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T05:02:49.453,8474,2008-08-12 05:02:49.453
26367,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:13:41.470,9310,2008-08-12 23:13:41.470
26368,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:27:54.093,9318,2008-08-12 23:27:54.093
26369,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T01:52:36.670,9400,2008-08-13 01:52:36.670
26370,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T03:30:58.860,9446,2008-08-13 03:30:58.860
26371,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T06:14:11.197,9507,2008-08-13 06:14:11.197
26372,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T12:03:05.940,9685,2008-08-13 12:03:05.940
26373,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:10:22.660,10614,2008-08-14 03:10:22.660
26374,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:13:56.770,10617,2008-08-14 03:13:56.770
26375,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:17:18.153,10623,2008-08-14 03:17:18.153
26376,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T13:48:02.523,11034,2008-08-14 13:48:02.523
26377,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T02:58:18.083,13486,2008-08-17 02:58:18.083
26378,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T03:00:34.317,13488,2008-08-17 03:00:34.317
26379,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-18T13:29:55.687,14587,2008-08-18 13:29:55.687
26380,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-19T16:51:17.103,16532,2008-08-19 16:51:17.103
26382,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-24T23:40:09.253,25456,2008-08-24 23:40:09.253
26383,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T00:11:43.763,25486,2008-08-25 00:11:43.763
26384,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T13:43:41.643,26046,2008-08-25 13:43:41.643
26385,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-27T13:08:30.010,30034,2008-08-27 13:08:30.010
26386,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T11:23:59.427,32021,2008-08-28 11:23:59.427
26387,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T13:26:27.823,32254,2008-08-28 13:26:27.823
26388,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-09-01T12:03:30.520,37817,2008-09-01 12:03:30.520
...,...,...,...,...,...,...,...,...
10230403,1566944.00,PahanCS,d9e2b0fec26ae9743462b20ae0f69ffd,1566944.00,2,2012-07-31T21:02:30.597,11748957,2012-07-31 21:02:30.597
10230404,1566946.00,Srinivasan,6b3e106fe114714bdad9657f04b64138,1566946.00,2,2012-07-31T21:03:19.733,11748968,2012-07-31 21:03:19.733
10230409,1566963.00,Manny in Cape Town,917eb7a84d44444da687ef4d0b7078d7,1566963.00,2,2012-07-31T21:11:55.417,11749076,2012-07-31 21:11:55.417
10230414,1566981.00,Luke,1f4abdc335ee20a5d652aa8cfbed1cd2,1566981.00,2,2012-07-31T21:20:54.430,11749183,2012-07-31 21:20:54.430
10230415,1566983.00,dbsx,595734cb022c9368f2d7f4ccfec7c46d,1566983.00,2,2012-07-31T21:57:21.443,11749608,2012-07-31 21:57:21.443
10230422,1567003.00,mfc,cc5dd9ffd9a4599efd6eb29069eb57e9,1567003.00,2,2012-07-31T21:32:15.223,11749330,2012-07-31 21:32:15.223
10230434,1567046.00,Chris X,a83ec9a7cfab407f766ff20f0a505d0f,1567046.00,2,2012-07-31T21:59:58.937,11749638,2012-07-31 21:59:58.937
10230435,1567047.00,ehernandez,ade9d8ce17e3009005ea4fca75c7b184,1567047.00,2,2012-07-31T22:16:04.053,11749819,2012-07-31 22:16:04.053
10230439,1567058.00,StackTest,091419e676e6f6d1bce069cc0ea994f9,1567058.00,2,2012-07-31T22:07:05.393,11749721,2012-07-31 22:07:05.393
10230443,1567067.00,Chuck,d1054eddee873dc403637d7921dceeb5,1567067.00,2,2012-07-31T22:14:40.697,11749794,2012-07-31 22:14:40.697
10230450,1567080.00,DuncanDavies,94714775a44c3c2768f3e69cc5c6b2b8,1567080.00,2,2012-07-31T22:30:08.300,11749970,2012-07-31 22:30:08.300
10230455,1567089.00,Oblivion,39592f05c7c22fec180bc5d44391b1b9,1567089.00,2,2012-07-31T22:32:01.930,11749989,2012-07-31 22:32:01.930
10230456,1567091.00,RyanHilliker,dadd09b47fb4445a85368407ddb7953e,1567091.00,2,2012-07-31T22:33:07.517,11750002,2012-07-31 22:33:07.517
10230460,1567100.00,262media,8a11eecbb3c08c450723b8edf400d047,1567100.00,2,2012-07-31T22:39:25.203,11750065,2012-07-31 22:39:25.203
10230462,1567106.00,Weslley S. Pereira,300c9c80adb08b4e97a64f1716827418,1567106.00,2,2012-07-31T22:44:33.157,11750116,2012-07-31 22:44:33.157
10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119,2012-07-31 22:44:46.437
10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153,2012-07-31 22:49:08.643
10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175,2012-07-31 22:52:01.630
10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211,2012-07-31 22:56:09.037
10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269,2012-07-31 23:01:32.390
10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320,2012-07-31 23:07:21.073
10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357,2012-07-31 23:11:26.800
10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374,2012-07-31 23:12:56.433
10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536,2012-07-31 23:29:52.760
10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614,2012-07-31 23:38:52.320
10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564,2012-07-31 23:33:21.643
10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566,2012-07-31 23:33:50.723
10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685,2012-07-31 23:49:08.307
10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711,2012-07-31 23:53:26.197
10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753,2012-07-31 23:59:25.083

In [32]:
#t_users_posts = s_users_posts.sort_values(by=['name','timestamp'])
sd_ans_users_posts['time_diff'] = sd_ans_users_posts.groupby('OwnerUserId')['timestamp'].diff()

In [33]:
sd_ans_users_posts

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id,timestamp,time_diff
26357,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-07-31T23:56:41.303,12,2008-07-31 23:56:41.303,NaT
26358,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T02:45:07.717,986,2008-08-04 02:45:07.717,3 days 02:48:26.414000
26359,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T04:31:02.557,1016,2008-08-04 04:31:02.557,0 days 01:45:54.840000
26360,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T08:04:41.737,1074,2008-08-04 08:04:41.737,0 days 03:33:39.180000
26361,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-05T12:01:32.227,2135,2008-08-05 12:01:32.227,1 days 03:56:50.490000
26362,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-10T08:28:52.100,7099,2008-08-10 08:28:52.100,4 days 20:27:19.873000
26363,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-11T19:23:47.160,8116,2008-08-11 19:23:47.160,1 days 10:54:55.060000
26364,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T00:30:43.390,8368,2008-08-12 00:30:43.390,0 days 05:06:56.230000
26366,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T05:02:49.453,8474,2008-08-12 05:02:49.453,0 days 04:32:06.063000
26367,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:13:41.470,9310,2008-08-12 23:13:41.470,0 days 18:10:52.017000
26368,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:27:54.093,9318,2008-08-12 23:27:54.093,0 days 00:14:12.623000
26369,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T01:52:36.670,9400,2008-08-13 01:52:36.670,0 days 02:24:42.577000
26370,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T03:30:58.860,9446,2008-08-13 03:30:58.860,0 days 01:38:22.190000
26371,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T06:14:11.197,9507,2008-08-13 06:14:11.197,0 days 02:43:12.337000
26372,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T12:03:05.940,9685,2008-08-13 12:03:05.940,0 days 05:48:54.743000
26373,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:10:22.660,10614,2008-08-14 03:10:22.660,0 days 15:07:16.720000
26374,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:13:56.770,10617,2008-08-14 03:13:56.770,0 days 00:03:34.110000
26375,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:17:18.153,10623,2008-08-14 03:17:18.153,0 days 00:03:21.383000
26376,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T13:48:02.523,11034,2008-08-14 13:48:02.523,0 days 10:30:44.370000
26377,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T02:58:18.083,13486,2008-08-17 02:58:18.083,2 days 13:10:15.560000
26378,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T03:00:34.317,13488,2008-08-17 03:00:34.317,0 days 00:02:16.234000
26379,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-18T13:29:55.687,14587,2008-08-18 13:29:55.687,1 days 10:29:21.370000
26380,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-19T16:51:17.103,16532,2008-08-19 16:51:17.103,1 days 03:21:21.416000
26382,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-24T23:40:09.253,25456,2008-08-24 23:40:09.253,5 days 06:48:52.150000
26383,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T00:11:43.763,25486,2008-08-25 00:11:43.763,0 days 00:31:34.510000
26384,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T13:43:41.643,26046,2008-08-25 13:43:41.643,0 days 13:31:57.880000
26385,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-27T13:08:30.010,30034,2008-08-27 13:08:30.010,1 days 23:24:48.367000
26386,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T11:23:59.427,32021,2008-08-28 11:23:59.427,0 days 22:15:29.417000
26387,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T13:26:27.823,32254,2008-08-28 13:26:27.823,0 days 02:02:28.396000
26388,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-09-01T12:03:30.520,37817,2008-09-01 12:03:30.520,3 days 22:37:02.697000
...,...,...,...,...,...,...,...,...,...
10230403,1566944.00,PahanCS,d9e2b0fec26ae9743462b20ae0f69ffd,1566944.00,2,2012-07-31T21:02:30.597,11748957,2012-07-31 21:02:30.597,NaT
10230404,1566946.00,Srinivasan,6b3e106fe114714bdad9657f04b64138,1566946.00,2,2012-07-31T21:03:19.733,11748968,2012-07-31 21:03:19.733,NaT
10230409,1566963.00,Manny in Cape Town,917eb7a84d44444da687ef4d0b7078d7,1566963.00,2,2012-07-31T21:11:55.417,11749076,2012-07-31 21:11:55.417,NaT
10230414,1566981.00,Luke,1f4abdc335ee20a5d652aa8cfbed1cd2,1566981.00,2,2012-07-31T21:20:54.430,11749183,2012-07-31 21:20:54.430,NaT
10230415,1566983.00,dbsx,595734cb022c9368f2d7f4ccfec7c46d,1566983.00,2,2012-07-31T21:57:21.443,11749608,2012-07-31 21:57:21.443,NaT
10230422,1567003.00,mfc,cc5dd9ffd9a4599efd6eb29069eb57e9,1567003.00,2,2012-07-31T21:32:15.223,11749330,2012-07-31 21:32:15.223,NaT
10230434,1567046.00,Chris X,a83ec9a7cfab407f766ff20f0a505d0f,1567046.00,2,2012-07-31T21:59:58.937,11749638,2012-07-31 21:59:58.937,NaT
10230435,1567047.00,ehernandez,ade9d8ce17e3009005ea4fca75c7b184,1567047.00,2,2012-07-31T22:16:04.053,11749819,2012-07-31 22:16:04.053,NaT
10230439,1567058.00,StackTest,091419e676e6f6d1bce069cc0ea994f9,1567058.00,2,2012-07-31T22:07:05.393,11749721,2012-07-31 22:07:05.393,NaT
10230443,1567067.00,Chuck,d1054eddee873dc403637d7921dceeb5,1567067.00,2,2012-07-31T22:14:40.697,11749794,2012-07-31 22:14:40.697,NaT
10230450,1567080.00,DuncanDavies,94714775a44c3c2768f3e69cc5c6b2b8,1567080.00,2,2012-07-31T22:30:08.300,11749970,2012-07-31 22:30:08.300,NaT
10230455,1567089.00,Oblivion,39592f05c7c22fec180bc5d44391b1b9,1567089.00,2,2012-07-31T22:32:01.930,11749989,2012-07-31 22:32:01.930,NaT
10230456,1567091.00,RyanHilliker,dadd09b47fb4445a85368407ddb7953e,1567091.00,2,2012-07-31T22:33:07.517,11750002,2012-07-31 22:33:07.517,NaT
10230460,1567100.00,262media,8a11eecbb3c08c450723b8edf400d047,1567100.00,2,2012-07-31T22:39:25.203,11750065,2012-07-31 22:39:25.203,NaT
10230462,1567106.00,Weslley S. Pereira,300c9c80adb08b4e97a64f1716827418,1567106.00,2,2012-07-31T22:44:33.157,11750116,2012-07-31 22:44:33.157,NaT
10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119,2012-07-31 22:44:46.437,NaT
10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153,2012-07-31 22:49:08.643,NaT
10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175,2012-07-31 22:52:01.630,NaT
10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211,2012-07-31 22:56:09.037,NaT
10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269,2012-07-31 23:01:32.390,NaT
10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320,2012-07-31 23:07:21.073,NaT
10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357,2012-07-31 23:11:26.800,NaT
10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374,2012-07-31 23:12:56.433,NaT
10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536,2012-07-31 23:29:52.760,NaT
10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614,2012-07-31 23:38:52.320,NaT
10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564,2012-07-31 23:33:21.643,NaT
10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566,2012-07-31 23:33:50.723,NaT
10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685,2012-07-31 23:49:08.307,NaT
10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711,2012-07-31 23:53:26.197,NaT
10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753,2012-07-31 23:59:25.083,NaT

In [34]:
sd_ans_users_posts['time_diff_sec'] = sd_ans_users_posts.time_diff.dt.total_seconds()
sd_ans_users_posts

,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id,timestamp,time_diff,time_diff_sec
26357,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-07-31T23:56:41.303,12,2008-07-31 23:56:41.303,NaT,nan
26358,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T02:45:07.717,986,2008-08-04 02:45:07.717,3 days 02:48:26.414000,269306.41
26359,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T04:31:02.557,1016,2008-08-04 04:31:02.557,0 days 01:45:54.840000,6354.84
26360,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-04T08:04:41.737,1074,2008-08-04 08:04:41.737,0 days 03:33:39.180000,12819.18
26361,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-05T12:01:32.227,2135,2008-08-05 12:01:32.227,1 days 03:56:50.490000,100610.49
26362,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-10T08:28:52.100,7099,2008-08-10 08:28:52.100,4 days 20:27:19.873000,419239.87
26363,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-11T19:23:47.160,8116,2008-08-11 19:23:47.160,1 days 10:54:55.060000,125695.06
26364,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T00:30:43.390,8368,2008-08-12 00:30:43.390,0 days 05:06:56.230000,18416.23
26366,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T05:02:49.453,8474,2008-08-12 05:02:49.453,0 days 04:32:06.063000,16326.06
26367,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:13:41.470,9310,2008-08-12 23:13:41.470,0 days 18:10:52.017000,65452.02
26368,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-12T23:27:54.093,9318,2008-08-12 23:27:54.093,0 days 00:14:12.623000,852.62
26369,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T01:52:36.670,9400,2008-08-13 01:52:36.670,0 days 02:24:42.577000,8682.58
26370,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T03:30:58.860,9446,2008-08-13 03:30:58.860,0 days 01:38:22.190000,5902.19
26371,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T06:14:11.197,9507,2008-08-13 06:14:11.197,0 days 02:43:12.337000,9792.34
26372,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-13T12:03:05.940,9685,2008-08-13 12:03:05.940,0 days 05:48:54.743000,20934.74
26373,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:10:22.660,10614,2008-08-14 03:10:22.660,0 days 15:07:16.720000,54436.72
26374,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:13:56.770,10617,2008-08-14 03:13:56.770,0 days 00:03:34.110000,214.11
26375,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T03:17:18.153,10623,2008-08-14 03:17:18.153,0 days 00:03:21.383000,201.38
26376,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-14T13:48:02.523,11034,2008-08-14 13:48:02.523,0 days 10:30:44.370000,37844.37
26377,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T02:58:18.083,13486,2008-08-17 02:58:18.083,2 days 13:10:15.560000,220215.56
26378,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-17T03:00:34.317,13488,2008-08-17 03:00:34.317,0 days 00:02:16.234000,136.23
26379,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-18T13:29:55.687,14587,2008-08-18 13:29:55.687,1 days 10:29:21.370000,124161.37
26380,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-19T16:51:17.103,16532,2008-08-19 16:51:17.103,1 days 03:21:21.416000,98481.42
26382,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-24T23:40:09.253,25456,2008-08-24 23:40:09.253,5 days 06:48:52.150000,456532.15
26383,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T00:11:43.763,25486,2008-08-25 00:11:43.763,0 days 00:31:34.510000,1894.51
26384,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-25T13:43:41.643,26046,2008-08-25 13:43:41.643,0 days 13:31:57.880000,48717.88
26385,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-27T13:08:30.010,30034,2008-08-27 13:08:30.010,1 days 23:24:48.367000,170688.37
26386,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T11:23:59.427,32021,2008-08-28 11:23:59.427,0 days 22:15:29.417000,80129.42
26387,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-08-28T13:26:27.823,32254,2008-08-28 13:26:27.823,0 days 02:02:28.396000,7348.40
26388,1.00,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,1.00,2,2008-09-01T12:03:30.520,37817,2008-09-01 12:03:30.520,3 days 22:37:02.697000,340622.70
...,...,...,...,...,...,...,...,...,...,...
10230403,1566944.00,PahanCS,d9e2b0fec26ae9743462b20ae0f69ffd,1566944.00,2,2012-07-31T21:02:30.597,11748957,2012-07-31 21:02:30.597,NaT,nan
10230404,1566946.00,Srinivasan,6b3e106fe114714bdad9657f04b64138,1566946.00,2,2012-07-31T21:03:19.733,11748968,2012-07-31 21:03:19.733,NaT,nan
10230409,1566963.00,Manny in Cape Town,917eb7a84d44444da687ef4d0b7078d7,1566963.00,2,2012-07-31T21:11:55.417,11749076,2012-07-31 21:11:55.417,NaT,nan
10230414,1566981.00,Luke,1f4abdc335ee20a5d652aa8cfbed1cd2,1566981.00,2,2012-07-31T21:20:54.430,11749183,2012-07-31 21:20:54.430,NaT,nan
10230415,1566983.00,dbsx,595734cb022c9368f2d7f4ccfec7c46d,1566983.00,2,2012-07-31T21:57:21.443,11749608,2012-07-31 21:57:21.443,NaT,nan
10230422,1567003.00,mfc,cc5dd9ffd9a4599efd6eb29069eb57e9,1567003.00,2,2012-07-31T21:32:15.223,11749330,2012-07-31 21:32:15.223,NaT,nan
10230434,1567046.00,Chris X,a83ec9a7cfab407f766ff20f0a505d0f,1567046.00,2,2012-07-31T21:59:58.937,11749638,2012-07-31 21:59:58.937,NaT,nan
10230435,1567047.00,ehernandez,ade9d8ce17e3009005ea4fca75c7b184,1567047.00,2,2012-07-31T22:16:04.053,11749819,2012-07-31 22:16:04.053,NaT,nan
10230439,1567058.00,StackTest,091419e676e6f6d1bce069cc0ea994f9,1567058.00,2,2012-07-31T22:07:05.393,11749721,2012-07-31 22:07:05.393,NaT,nan
10230443,1567067.00,Chuck,d1054eddee873dc403637d7921dceeb5,1567067.00,2,2012-07-31T22:14:40.697,11749794,2012-07-31 22:14:40.697,NaT,nan
10230450,1567080.00,DuncanDavies,94714775a44c3c2768f3e69cc5c6b2b8,1567080.00,2,2012-07-31T22:30:08.300,11749970,2012-07-31 22:30:08.300,NaT,nan
10230455,1567089.00,Oblivion,39592f05c7c22fec180bc5d44391b1b9,1567089.00,2,2012-07-31T22:32:01.930,11749989,2012-07-31 22:32:01.930,NaT,nan
10230456,1567091.00,RyanHilliker,dadd09b47fb4445a85368407ddb7953e,1567091.00,2,2012-07-31T22:33:07.517,11750002,2012-07-31 22:33:07.517,NaT,nan
10230460,1567100.00,262media,8a11eecbb3c08c450723b8edf400d047,1567100.00,2,2012-07-31T22:39:25.203,11750065,2012-07-31 22:39:25.203,NaT,nan
10230462,1567106.00,Weslley S. Pereira,300c9c80adb08b4e97a64f1716827418,1567106.00,2,2012-07-31T22:44:33.157,11750116,2012-07-31 22:44:33.157,NaT,nan
10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119,2012-07-31 22:44:46.437,NaT,nan
10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153,2012-07-31 22:49:08.643,NaT,nan
10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175,2012-07-31 22:52:01.630,NaT,nan
10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211,2012-07-31 22:56:09.037,NaT,nan
10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269,2012-07-31 23:01:32.390,NaT,nan
10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320,2012-07-31 23:07:21.073,NaT,nan
10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357,2012-07-31 23:11:26.800,NaT,nan
10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374,2012-07-31 23:12:56.433,NaT,nan
10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536,2012-07-31 23:29:52.760,NaT,nan
10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614,2012-07-31 23:38:52.320,NaT,nan
10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564,2012-07-31 23:33:21.643,NaT,nan
10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566,2012-07-31 23:33:50.723,NaT,nan
10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685,2012-07-31 23:49:08.307,NaT,nan
10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711,2012-07-31 23:53:26.197,NaT,nan
10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753,2012-07-31 23:59:25.083,NaT,nan

In [37]:
sd_ans_users_posts.to_csv('timestamped_answersonly_users_posts_whole_1.csv')

In [35]:
#time_elapsed = s_users_posts
time_elapsed = sd_ans_users_posts.groupby('OwnerUserId', as_index=False)['time_diff_sec'].mean()
time_elapsed

        OwnerUserId  time_diff_sec
0              1.00      849582.73
1              2.00    21723088.50
2              3.00     2956787.78
3              4.00      737658.20
4              5.00      424657.21
5              9.00     2990386.75
6             13.00       97919.54
7             16.00    10813451.60
8             17.00      198318.47
9             19.00     8875554.71
10            20.00     1061775.08
11            22.00      683924.54
12            23.00    13836083.23
13            24.00     9785244.96
14            25.00     1308844.79
15            26.00      537988.00
16            27.00     2000426.24
17            29.00      286577.68
18            30.00      824992.63
19            32.00        2905.68
20            33.00     1426554.91
21            34.00     1704861.77
22            35.00      445783.70
23            36.00     1068775.46
24            37.00     2669247.89
25            38.00     2224026.64
26            39.00     1718174.67
27            40.00     1149147.75
28            41.00      958730.59
29            42.00      592554.06
...             ...            ...
443330   1566944.00            nan
443331   1566946.00            nan
443332   1566963.00            nan
443333   1566981.00            nan
443334   1566983.00            nan
443335   1567003.00            nan
443336   1567046.00            nan
443337   1567047.00            nan
443338   1567058.00            nan
443339   1567067.00            nan
443340   1567080.00            nan
443341   1567089.00            nan
443342   1567091.00            nan
443343   1567100.00            nan
443344   1567106.00            nan
443345   1567108.00            nan
443346   1567112.00            nan
443347   1567115.00            nan
443348   1567122.00            nan
443349   1567132.00            nan
443350   1567138.00            nan
443351   1567142.00            nan
443352   1567145.00            nan
443353   1567166.00            nan
443354   1567168.00            nan
443355   1567169.00            nan
443356   1567170.00            nan
443357   1567187.00            nan
443358   1567195.00            nan
443359   1567202.00            nan

[443360 rows x 2 columns]

In [36]:
time_elapsed.to_csv('time_elapsed_whole_1.csv')

## Commitment towards community

In [42]:
users

,id,reputation,creationDate,name,emailHash,lastAccess,websiteUrl,location,age,aboutMe,views,upvotes,downvotes
0,-1.00,1,2008-07-31T00:00:00.000,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,2008-08-26T00:16:53.810,http://stackoverflow.com,on the server farm,nan,"<p>Hi, I'm not really a person.</p>\r\n<p>I'm ...",649,4310,91092
1,1.00,21812,2008-07-31T14:22:31.287,Jeff Atwood,51d623f33f8b83095db84ff35e15dbe8,2012-08-01T04:46:57.447,http://www.codinghorror.com/blog/,"El Cerrito, CA",41.00,"<p><a href=""http://www.codinghorror.com/blog/a...",41072,3090,1279
2,2.00,1362,2008-07-31T14:22:31.287,Geoff Dalgas,b437f461b3fd27387c5d8ab47a293d35,2012-07-31T23:38:17.330,http://stackoverflow.com,"Corvallis, OR",35.00,<p>Developer on the StackOverflow team. Find ...,7679,430,82
3,3.00,5584,2008-07-31T14:22:31.287,Jarrod Dixon,2dfa19bf5dc5826c1fe54c2c049a1ff1,2012-07-31T22:49:53.213,http://stackoverflow.com,"New York, NY",33.00,"<p><a href=""http://blog.stackoverflow.com/2009...",8929,3280,67
4,4.00,16676,2008-07-31T14:22:31.317,Joel Spolsky,d1129adecd8c4e2a22b50605d18e376d,2012-08-01T03:37:02.227,http://www.joelonsoftware.com/,"New York, NY",nan,<p>I am:</p>\n\n<ul>\n<li>the co-founder and C...,32408,688,91
5,5.00,20812,2008-07-31T14:22:31.317,Jon Galloway,1c494896dd56e0e27253156c28f1dfb9,2012-07-31T22:31:50.930,http://weblogs.asp.net/jgalloway/,"San Diego, CA",41.00,<p>Community program manager for ASP.NET at Mi...,2962,738,34
6,8.00,817,2008-07-31T21:33:24.057,Eggs McLaren,c7ec7dec48168d2a7d792e2b0acc78d1,2012-07-20T18:25:48.217,NaN,NaN,nan,<p>This is a puppet test account I use to vali...,1228,12,9
7,9.00,4630,2008-07-31T21:35:26.517,Kevin Dente,23c1e2063688620b75b248e08c0d5c24,2012-07-31T23:07:18.440,http://weblogs.asp.net/kdente,"Oakland, CA",41.00,"<p>Self employed software engineer, currently ...",1056,27,4
8,10.00,101,2008-07-31T21:57:06.240,Sneakers O'Toole,f82fc4a2bfc73434ac4899690926c8a0,2012-06-19T19:35:43.433,http://www.youtube.com/watch?v=qrhNoljPtok,"Lakehead, CA",33.00,I'm not takin' my sneakers off!\r\n<br><br>\r\...,875,0,0
9,11.00,537,2008-08-01T00:59:11.147,Anonymous User,c510febb9bed68b5cc4a09f076701e0f,2008-08-01T00:59:11.147,NaN,NaN,nan,NaN,304,0,0
10,13.00,63611,2008-08-01T04:18:04.943,Chris Jester-Young,729442eea8d8548842a6e0947e333c7b,2012-07-31T22:48:22.820,http://about.me/cky,"Raleigh, NC",32.00,"\n\n<p>Quick links:</p>\n\n<ul>\n<li><a href=""...",3347,3348,123
11,16.00,313,2008-08-01T12:01:53.023,Rodrigo Sieiro,235da791830e54ec0bfc084800523349,2012-08-01T03:21:30.773,http://twitter.com/rsieiro,Brazil,31.00,You don't know me because I keep a low profile.,279,25,1
12,17.00,22049,2008-08-01T12:02:21.617,Nick Berardi,42893555ea66c988b51c9167a650d849,2012-08-01T02:00:20.007,http://coderjournal.com,"Collegeville, PA",32.00,<p><strong>email</strong>: nberardi@gmail.com<...,1706,811,193
13,19.00,404,2008-08-01T12:05:14.233,Mads Kristiansen,4bd8c62d52be7585745a99da8f526d93,2012-03-12T13:10:34.120,NaN,Denmark,38.00,NaN,270,33,10
14,20.00,4898,2008-08-01T12:09:11.010,Tom,1f0b00b8853cf0311888bb3ed2a77ebc,2012-07-24T15:29:32.373,http://tommcfarlin.com,"Atlanta, GA",nan,NaN,505,366,38
15,22.00,3481,2008-08-01T12:11:11.897,maclema,1c23587bf4956c04bb580a6d1310e678,2012-07-31T18:57:39.533,http://www.maclema.com,"Calgary, Canada",26.00,NaN,273,112,5
16,23.00,977,2008-08-01T12:11:43.703,Jax,41e48d118b55b1bd341141dccacbfeb5,2012-07-31T20:57:47.477,http://jackstrife.com,"Cary, NC",25.00,I'm a young whippersnapper who just got out of...,229,182,2
17,24.00,428,2008-08-01T12:12:53.453,braklet,b51e14bfee5fd2f1d63c8e2b0ff2f2bb,2012-07-26T21:55:13.853,http://www.google.com/reader/shared/Braklet,"London, United Kingdom",28.00,Code junkie,86,112,0
18,25.00,5522,2008-08-01T12:15:23.243,CodingWithoutComments,d66009e0e3917e52fbf65b8dc03c2068,2012-05-20T22:46:32.797,http://www.codingwithoutcomments.com,"Seattle, WA",31.00,"a man, a plan, a canal, panama\r\n",1047,519,73
19,26.00,6234,2008-08-01T12:18:14.520,Shawn,f878a55e08bacee0af48852c29a02dc7,2012-07-31T00:14:51.510,NaN,"San Francisco, CA",28.00,<p>a long time ago i found an xss vuln here an...,2012,556,62
20,27.00,893,2008-08-01T12:21:40.020,denny,1f5623ff6f4c6ac52bc757a7f03ab6ec,2012-07-30T16:20:09.330,http://www.dennymorrison.net,"Winchester, VA",29.00,"<p>I write shitty, buggy code...but that's oka...",145,288,3
21,29.00,24640,2008-08-01T12:24:53.820,Michael Haren,f4f4b5a6f27f72b32d42463b1a25e0df,2012-08-01T03:23:28.853,http://blog.wassupy.com/search/label/Technology,Ohio,29.00,<ul>\n<li>These days I'm a .net/sql software g...,1340,3972,145
22,30.00,3869,2008-08-01T12:25:44.817,Grant,756737fe8cbb545ed58854ff0193cc60,2012-07-31T20:37:07.323,http://beta.stackoverflow.com/badges/22/great-...,Georgia,28.00,<p>Lead (and only) programmer for respectable ...,845,136,8
23,32.00,471,2008-08-01T12:31:17.783,TimM,399ecfe1915ddb853a0421afeccbfa02,2011-10-09T22:12:56.320,http://www.sample.com,Alabama,38.00,I live in meteor crater. I hate ObjC.,98,5,1
24,33.00,5486,2008-08-01T12:32:10.963,John,d0b76ae7bf261316683cad31ba0bad91,2012-07-31T15:26:21.493,NaN,"Southampton, United Kingdom",30.00,<p>Here from the start as Stack Overflow user ...,426,1178,19
25,34.00,7553,2008-08-01T12:39:52.493,Karl Seguin,6f448664cd294829b9ed0cd356f91cb1,2012-02-04T00:55:28.387,http://www.openmymind.net/,"Ottawa, Canada",32.00,"Check out my <a href=""http://tinyurl.com/5jaae...",408,51,9
26,35.00,8520,2008-08-01T12:43:07.713,Greg Hurlman,c03ec7268e3c266e10dff18e61a2498f,2012-07-30T15:47:20.363,http://greghurlman.com,"Howell, NJ",34.00,<p>Technical Lead for .Net and SharePoint at P...,525,392,193
27,36.00,2808,2008-08-01T12:43:55.683,Pat,df0eee24254231e5393a7c5cfc4c3a0e,2012-07-31T22:16:20.847,http://patpack.blogspot.com,"Washington, DC",30.00,<p>I am a C# developer at a Public Relations C...,265,367,9
28,37.00,2177,2008-08-01T12:44:00.723,Wally Lawless,6d7ac6b2dbca2b7ce21dca615d1166ba,2012-07-30T19:45:03.893,http://www.power-coder.net,"Georgetown, Canada",31.00,I am a professional PHP developer working for ...,264,182,10
29,38.00,1363,2008-08-01T12:44:28.833,blcArmadillo,db4342fae89286695afad4c08a272ac1,2012-07-31T18:15:49.997,http://www.ianburris.com,"Detroit, MI",22.00,<p>I'm currently studying computer engineering...,200,74,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295590,1567174.00,1,2012-07-31T23:37:24.897,Raja,bff3158d2a6c0888fa00bddc62426409,2012-07-31T23:37:24.897,NaN,NaN,nan,NaN,0,0,0
1295591,1567175.00,6,2012-07-31T23:37:38.583,Brandon,0aea0c92a6bb41685fe459ad33b06198,2012-07-31T23:37:38.583,NaN,NaN,nan,NaN,0,0,0
1295592,1567176.00,1,2012-07-31T23:38:45.880,alfonsob,ebfd18737fe76dfba963bb8ba92debf2,2012-07-31T23:38:45.880,NaN,NaN,nan,NaN,0,0,0
1295593,1567177.00,1,2012-07-31T23:39:35.303,Tomas Valettini,fe5242f665098f8c8975cef34d3cc868,2012-07-31T23:39:35.303,NaN,NaN,nan,NaN,0,0,0
1295594,1567178.00,1,2012-07-31T23:40:04.807,Derek Knox,a8ef9b8e4a68151cdf547bca780c915a,2012-07-31T23:40:04.807,NaN,NaN,nan,NaN,0,0,0
1295595,1567179.00,1,2012-07-31T23:40:09.717,Blake took,eee28c1c79aa4a4338399b933a1c2ab1,2012-08-01T00:36:09.313,NaN,NaN,nan,NaN,0,0,0
1295596,1567180.00,1,2012-07-31T23:40:16.787,Alejo Hinestrosa,5c88cdc7e7939b54966326bde2d8e5f1,2012-07-31T23:40:16.787,NaN,NaN,nan,NaN,0,0,0
1295597,1567181.00,1,2012-07-31T23:41:18.453,user1567181,dedbfacbf9018dea948da1cc761c0e76,2012-08-01T01:23:06.057,NaN,NaN,nan,NaN,0,0,0
1295598,1567182.00,1,2012-07-31T23:41:45.597,user1567182,c5e6d27d303b62c81594ead33a7622a2,2012-07-31T23:57:15.510,NaN,NaN,nan,NaN,0,0,0
1295599,1567183.00,1,2012-07-31T23:42:07.960,Nic Dahlquist,f9de1ba6dee55007993f82f0e5909ca2,2012-08-01T00:48:53.443,NaN,NaN,nan,NaN,0,0,0
1295600,1567184.00,1,2012-07-31T23:44:12.433,user1567184,8079f2a0ef3cb237b102c49741a318d4,2012-08-01T00:48:39.963,NaN,NaN,nan,NaN,0,0,0
1295601,1567185.00,3,2012-07-31T23:44:38.447,user1567185,6356ed8bdb9f7f002a9025d6956f47d0,2012-08-01T01:03:15.960,NaN,NaN,nan,NaN,0,0,0
1295602,1567186.00,3,2012-07-31T23:45:06.600,user1567186,3701f5895191f6b115325164acbbcc27,2012-08-01T01:42:14.800,NaN,NaN,nan,NaN,0,0,0
1295603,1567187.00,1,2012-07-31T23:49:08.307,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,2012-08-01T03:57:45.660,NaN,NaN,nan,NaN,0,0,0
1295604,1567188.00,1,2012-07-31T23:50:16.980,Mazin SW,2857a543cb50b797a15b53620b3646b6,2012-08-01T03:24:15.943,NaN,NaN,nan,NaN,0,0,0
1295605,1567189.00,1,2012-07-31T23:50:47.993,yonathanhalim,3bf1b5619c58d3a93f65a606d3ab694e,2012-08-01T02:28:52.707,NaN,NaN,nan,NaN,0,0,0
1295606,1567190.00,1,2012-07-31T23:50:55.447,Dan,8899bdaf68d119870960f6da5bf0caf1,2012-07-31T23:50:55.447,NaN,NaN,nan,NaN,0,0,0
1295607,1567191.00,1,2012-07-31T23:51:47.147,user1567191,a07621236020f217df42d671c44a8bc5,2012-07-31T23:51:47.147,NaN,NaN,nan,NaN,0,0,0
1295608,1567192.00,1,2012-07-31T23:52:08.227,user1567192,89270f160d0fec957eaf27188905308e,2012-08-01T00:59:43.577,NaN,NaN,nan,NaN,0,0,0
1295609,1567193.00,1,2012-07-31T23:52:45.777,Chris Webb,3681e9910e642a03a482a258938dcd30,2012-08-01T04:47:50.533,NaN,NaN,nan,NaN,0,0,0
1295610,1567194.00,1,2012-07-31T23:53:14.933,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859,2012-08-01T04:07:34.423,NaN,NaN,nan,NaN,0,0,0
1295611,1567195.00,1,2012-07-31T23:53:26.197,SummerDew,d7c17ab89beed7df211dccc61d0db24e,2012-07-31T23:53:26.197,NaN,NaN,nan,NaN,0,0,0
1295612,1567196.00,1,2012-07-31T23:53:40.033,Garrett Miller,e7f8d28c8474f8175c122f5e21c8176b,2012-07-31T23:53:40.033,NaN,NaN,nan,NaN,0,0,0
1295613,1567197.00,1,2012-07-31T23:54:27.930,Konnah Sharp,6c58a7d03e652933089e2141c3cb6fea,2012-07-31T23:54:27.930,NaN,NaN,nan,NaN,0,0,0
1295614,1567198.00,1,2012-07-31T23:56:27.913,jibreel,39bd4523af35728426424615953a35c4,2012-08-01T02:10:31.753,NaN,NaN,nan,NaN,0,0,0
1295615,1567199.00,1,2012-07-31T23:56:39.270,Eduardo Yayo Mancilla Rodrigue,ebd8df4fc27bc165736839e6d02d5253,2012-07-31T23:56:39.270,NaN,NaN,nan,NaN,0,0,0
1295616,1567200.00,1,2012-07-31T23:57:57.770,user1567200,b55180b7e84ea379066fbe6dc9b64a36,2012-08-01T00:55:12.953,NaN,NaN,nan,NaN,0,0,0
1295617,1567201.00,1,2012-07-31T23:58:49.450,Joe Griffin,bc1ccf16df64a0305ed8ea2f700aa71e,2012-08-01T02:47:51.793,NaN,NaN,nan,NaN,0,0,0
1295618,1567202.00,26,2012-07-31T23:59:25.083,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,2012-07-31T23:59:25.083,http://www.microsofttranslator.com/dev,NaN,nan,NaN,0,0,0
1295619,1567203.00,1,2012-07-31T23:59:52.773,Sarah Rose,6154727bd78491ff9f4e60e545be5330,2012-07-31T23:59:52.773,NaN,NaN,nan,NaN,0,0,0

In [44]:
posts

,Id,PostTypeId,ParentID,AcceptedAnswerId,CreationDate,Score,ViewCount,Body,OwnerUserId,LastEditorUserId,LastEditorDisplayName,LastEditDate,LastActivityDate,CommunityOwnedDate,ClosedDate,Title,Tags,AnswerCount,CommentCount
0,4,1,nan,7.00,2008-07-31T21:42:52.667,139,9959.00,I'm new to C# and I want to use a track-bar t...,8.00,1039608.00,Rich B,2012-05-04T08:55:46.677,2012-07-24T16:45:40.937,NaN,NaN,<c#><winforms><forms><type-conversion><opacity>,13.00,19.00,14.00
1,6,1,nan,31.00,2008-07-31T22:08:08.620,43,3582.00,I have an absolutely positioned containin...,9.00,483731.00,Rich B,2012-02-26T13:47:20.073,2012-06-04T23:35:58.177,NaN,NaN,<html><css><css3><internet-explorer-7>,5.00,5.00,3.00
2,7,2,nan,nan,2008-07-31T22:17:57.883,127,nan,An explicit cast to double isn't necessary. \...,9.00,1.00,NaN,2010-02-02T19:38:14.493,2010-02-02T19:38:14.493,NaN,NaN,NaN,nan,2.00,nan
3,8,1,nan,162.00,2008-07-31T23:33:19.290,20,1619.00,Are there any conversion tools for porting V...,9.00,1039608.00,Rich B,2012-05-04T08:56:59.720,2012-05-08T19:00:36.850,NaN,NaN,<c#><j#><visualj#>,4.00,0.00,1.00
4,9,1,nan,1404.00,2008-07-31T23:40:59.743,330,87531.00,"Given a representing their birthday, how ...",1.00,861565.00,Rich B,2012-07-30T12:23:37.267,2012-07-30T12:23:37.267,2011-08-16T19:40:43.080,NaN,<c#><.net><datetime>,33.00,5.00,148.00
5,11,1,nan,1248.00,2008-07-31T23:55:37.967,388,37203.00,"Given a specific value, how do I display ...",1.00,1039608.00,Rich B,2012-05-04T08:57:39.843,2012-05-27T17:30:29.780,2009-09-04T13:15:59.820,NaN,<c#><.net><datetime><timespan>,32.00,10.00,277.00
6,12,2,nan,nan,2008-07-31T23:56:41.303,113,nan,"Well, here's how we do it on Stack Overflow. ...",1.00,159270.00,GateKiller,2011-08-08T01:14:13.453,2011-08-08T01:14:13.453,2009-09-04T13:15:59.820,NaN,NaN,nan,9.00,nan
7,13,1,nan,357.00,2008-08-01T00:42:38.903,157,39565.00,Is there a standard way for a Web Server to d...,9.00,1039608.00,Rich B,2012-05-04T08:58:19.547,2012-07-30T08:08:44.750,NaN,NaN,<html><browser><timezone><timezoneoffset>,19.00,2.00,66.00
8,14,1,nan,nan,2008-08-01T00:59:11.177,106,24965.00,What is the difference between and ...,11.00,1039608.00,Rich B,2012-05-04T09:00:49.407,2012-06-07T18:15:14.220,NaN,NaN,<.net><math>,5.00,1.00,17.00
9,16,1,nan,12446.00,2008-08-01T04:59:33.643,23,29386.00,How do you expose a LINQ query as an ASMX ...,2.00,1039608.00,Chris Fournier,2012-05-04T09:01:26.053,2012-05-25T20:48:38.330,NaN,NaN,<c#><linq><web-services><.net-3.5>,5.00,0.00,6.00
10,17,1,nan,26.00,2008-08-01T05:09:55.993,33,4746.00,How do I store binary data in MySQL ? \r\r\n,2.00,546051.00,NaN,2011-10-21T21:29:17.160,2012-06-11T15:07:58.813,NaN,NaN,<mysql><database><binary-data><data-storage>,8.00,0.00,3.00
11,18,2,nan,nan,2008-08-01T05:12:44.193,11,nan,For a table like this: \r\r\n\r\r\n \r\r\...,nan,6068.00,Jeff Atwood,2009-05-28T11:40:35.210,2009-05-28T11:40:35.210,NaN,NaN,NaN,nan,2.00,nan
12,19,1,nan,nan,2008-08-01T05:21:22.257,101,12386.00,Solutions welcome in any language. :-) I'm lo...,13.00,13.00,Chris Jester-Young,2009-08-07T11:45:50.333,2012-07-04T09:04:48.477,2009-02-26T19:22:22.320,NaN,<performance><algorithm><language-agnostic><un...,22.00,9.00,39.00
13,20,2,nan,nan,2008-08-01T07:25:22.443,4,nan,I've used the JLCA (Java Language Conversion...,5.00,nan,NaN,NaN,2008-08-01T07:25:22.443,NaN,NaN,NaN,nan,0.00,nan
14,21,2,nan,nan,2008-08-01T08:57:27.280,5,nan,"Many years ago, to provide an age calculator...",13.00,13.00,Chris Jester-Young,2008-08-01T12:35:11.707,2008-08-01T12:35:11.707,2011-08-16T19:40:43.080,NaN,NaN,nan,0.00,nan
15,22,2,nan,nan,2008-08-01T12:07:19.500,2,nan,The best way that I know of because of leap y...,17.00,17.00,Nick,2008-08-01T15:26:37.087,2008-08-01T15:26:37.087,2011-08-16T19:40:43.080,NaN,NaN,nan,1.00,nan
16,23,1,nan,156.00,2008-08-01T12:09:41.947,23,1013.00,I'm trying to track the progress of PHP 5.3 a...,48.00,367456.00,Mat Scales,2012-06-02T17:39:22.287,2012-06-02T17:39:22.287,NaN,2012-05-18T11:12:42.583,<php>,8.00,0.00,5.00
17,24,1,nan,49.00,2008-08-01T12:12:19.350,24,7722.00,If I have a trigger before the update on a ...,22.00,63550.00,Jim Anderson,2012-05-25T20:50:23.130,2012-06-14T04:32:17.193,NaN,NaN,<mysql><database><triggers>,3.00,0.00,3.00
18,25,1,nan,1443907.00,2008-08-01T12:13:50.207,30,3565.00,I've been having issues getting the C sockets...,23.00,13531.00,NaN,2012-05-25T21:48:23.387,2012-05-25T21:48:23.387,NaN,NaN,<c++><c><sockets><mainframe><zos>,10.00,0.00,0.00
19,26,2,nan,nan,2008-08-01T12:16:22.167,27,nan,The answer by phpguy is correct but I think t...,48.00,48.00,Geoff Dalgas,2012-06-11T15:07:58.813,2012-06-11T15:07:58.813,NaN,NaN,NaN,nan,3.00,nan
20,27,2,nan,nan,2008-08-01T12:17:19.357,7,nan,@jeff \r\r\r\n\r\r\r\n IMHO yours seems a lit...,17.00,17.00,Nick Berardi,2008-08-01T13:16:49.127,2008-08-01T13:16:49.127,2009-09-04T13:15:59.820,NaN,NaN,nan,1.00,nan
21,29,2,nan,nan,2008-08-01T12:19:17.417,8,nan,There are no HTTP headers that will report th...,19.00,nan,NaN,NaN,2008-08-01T12:19:17.417,NaN,NaN,NaN,nan,0.00,nan
22,30,2,nan,nan,2008-08-01T12:22:40.797,4,nan,I've had no trouble using the BSD sockets API...,13.00,nan,NaN,NaN,2008-08-01T12:22:40.797,NaN,NaN,NaN,nan,1.00,nan
23,31,2,nan,nan,2008-08-01T12:22:51.593,23,nan,Does the parent have a defined either...,nan,842480.00,NaN,2012-06-04T23:35:58.177,2012-06-04T23:35:58.177,NaN,NaN,NaN,nan,0.00,nan
24,33,2,nan,nan,2008-08-01T12:26:39.773,172,nan,"rounds down, rounds up, and round...",13.00,13.00,NaN,2009-10-14T02:09:03.030,2009-10-14T02:09:03.030,NaN,NaN,NaN,nan,5.00,nan
25,34,1,nan,nan,2008-08-01T12:30:57.630,16,4179.00,How do I forcefully unload a from memory ...,nan,63550.00,NaN,2012-05-25T21:06:10.223,2012-05-25T21:06:10.223,NaN,NaN,<flex><actionscript-3>,7.00,nan,0.00
26,36,1,nan,352.00,2008-08-01T12:35:56.917,32,10439.00,How can I monitor an SQL Server database for ...,32.00,419.00,Mark Harrison,2012-05-25T23:43:47.697,2012-05-25T23:43:47.697,NaN,NaN,<sql-server><datatable><rdbms>,8.00,0.00,6.00
27,37,2,nan,nan,2008-08-01T12:36:00.957,4,nan,Sure I can post a test app. \r\r\r\n\r\r\r\n ...,23.00,23.00,Jax,2008-08-01T12:42:32.113,2008-08-01T12:42:32.113,NaN,NaN,NaN,nan,0.00,nan
28,39,1,nan,45.00,2008-08-01T12:43:11.503,11,2080.00,I am aware that in .NET there are three tim...,33.00,63550.00,Jim Anderson,2012-05-25T20:55:43.157,2012-05-25T20:55:43.157,NaN,NaN,<c#><.net><vb.net><timer>,2.00,nan,1.00
29,41,2,nan,nan,2008-08-01T12:49:12.413,8,nan,Your best bet are probably these meeting note...,34.00,31671.00,NaN,2010-02-20T23:26:24.063,2010-02-20T23:26:24.063,NaN,NaN,NaN,nan,0.00,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10338331,11750729,1,nan,11750757.00,2012-07-31T23:55:24.683,0,43.00,I'm working on a winform application which cr...,731901.00,731901.00,NaN,2012-08-01T00:24:12.690,2012-08-01T00:24:12.690,NaN,NaN,<c#><winforms>,2.00,2.00,nan
10338332,11750730,2,nan,nan,2012-07-31T23:55:26.770,0,nan,I know of no solution using font-size to modi...,1330275.00,nan,NaN,NaN,2012-07-31T23:55:26.770,NaN,NaN,NaN,nan,nan,nan
10338333,11750731,2,nan,nan,2012-07-31T23:55:29.207,2,nan,The simple answer is you can't. But let me e...,409167.00,nan,NaN,NaN,2012-07-31T23:55:29.207,NaN,NaN,NaN,nan,nan,nan
10338334,11750732,1,nan,nan,2012-07-31T23:55:30.050,0,13.00,"Bear with me please, I'm a new programmer. (t...",1318705.00,1318705.00,NaN,2012-08-01T00:02:53.887,2012-08-01T00:02:53.887,NaN,NaN,<ios><json>,nan,6.00,nan
10338335,11750733,1,nan,nan,2012-07-31T23:55:35.260,0,20.00,I have a codebase that deals with angles quit...,770038.00,nan,NaN,NaN,2012-08-01T00:25:46.087,NaN,NaN,<oop><design-patterns>,2.00,1.00,nan
10338336,11750735,2,nan,nan,2012-07-31T23:55:48.533,0,nan,The short answer to this question is that EF4...,984335.00,nan,NaN,NaN,2012-07-31T23:55:48.533,NaN,NaN,NaN,nan,nan,nan
10338337,11750736,2,nan,nan,2012-07-31T23:55:52.110,2,nan,The is purely the runtime environment nee...,1398245.00,nan,NaN,NaN,2012-07-31T23:55:52.110,NaN,NaN,NaN,nan,1.00,nan
10338338,11750738,1,nan,nan,2012-07-31T23:56:18.193,0,17.00,I've been trying to uncrush PNG's extracted f...,900747.00,nan,NaN,NaN,2012-08-01T00:08:32.853,NaN,NaN,<iphone><ios><ipad><ipa><pngcrush>,1.00,nan,nan
10338339,11750739,1,nan,nan,2012-07-31T23:56:24.543,-6,27.00,Sorry for this not exactly being a coding rel...,1261355.00,nan,NaN,NaN,2012-07-31T23:56:24.543,NaN,NaN,<android><free><ads><paid><monetization>,nan,1.00,nan
10338340,11750740,1,nan,nan,2012-07-31T23:56:54.217,0,9.00,"According to this: ""Important: OAuth 1.0 has ...",841626.00,nan,NaN,NaN,2012-07-31T23:56:54.217,NaN,NaN,<api><google><oauth><google-api><deprecated>,nan,1.00,nan
10338341,11750741,1,nan,11751189.00,2012-07-31T23:56:58.567,0,17.00,Sorry for my bad english \r\r\n\r\r\n i searc...,1472467.00,nan,NaN,NaN,2012-08-01T01:00:47.150,NaN,NaN,<objective-c><arrays><cocos2d-iphone><cocos2d>...,1.00,nan,nan
10338342,11750742,1,nan,11751053.00,2012-07-31T23:57:18.710,0,14.00,Using PunBB on Forumotion the idea was to use...,1567186.00,nan,NaN,NaN,2012-08-01T00:40:30.840,NaN,NaN,<javascript><jquery><string><replace><punbb>,2.00,2.00,nan
10338343,11750743,1,nan,nan,2012-07-31T23:57:30.063,0,20.00,The basic idea of the application I've been w...,539273.00,nan,NaN,NaN,2012-08-01T00:46:01.187,NaN,NaN,<ruby-on-rails><ios><design-patterns><design><...,1.00,nan,nan
10338344,11750744,2,nan,nan,2012-07-31T23:57:56.600,1,nan,"No, this will not work. To have cron execute ...",491094.00,nan,NaN,NaN,2012-07-31T23:57:56.600,NaN,NaN,NaN,nan,1.00,nan
10338345,11750745,2,nan,nan,2012-07-31T23:58:02.943,0,nan,"When displaying your results with MessageBox,...",1504644.00,nan,NaN,NaN,2012-07-31T23:58:02.943,NaN,NaN,NaN,nan,nan,nan
10338346,11750746,1,nan,11750810.00,2012-07-31T23:58:04.573,0,20.00,I've created an XNA application that utilizes...,595437.00,nan,NaN,NaN,2012-08-01T00:05:59.343,NaN,NaN,<.net><xna><lua><extension-methods>,2.00,nan,nan
10338347,11750747,1,nan,nan,2012-07-31T23:58:07.160,0,39.00,After looking over several articles in intern...,1567194.00,1567194.00,NaN,2012-08-01T02:11:19.287,2012-08-01T02:11:19.287,NaN,NaN,<vb.net>,1.00,9.00,nan
10338348,11750748,2,nan,nan,2012-07-31T23:58:11.440,0,nan,I execute scripts as part of an iOS project. ...,775184.00,nan,NaN,NaN,2012-07-31T23:58:11.440,NaN,NaN,NaN,nan,nan,nan
10338349,11750749,2,nan,nan,2012-07-31T23:58:50.220,0,nan,Always check your model functions if they ret...,686733.00,nan,NaN,NaN,2012-07-31T23:58:50.220,NaN,NaN,NaN,nan,1.00,nan
10338350,11750750,2,nan,nan,2012-07-31T23:58:56.213,0,nan,"ah, actually that did work, the complex excep...",517781.00,nan,NaN,NaN,2012-07-31T23:58:56.213,NaN,NaN,NaN,nan,nan,nan
10338351,11750751,2,nan,nan,2012-07-31T23:59:03.527,0,nan,\r\r\n\r\r\n or rather just \r\r\n\r\r\n ...,898266.00,898266.00,NaN,2012-08-01T00:13:55.030,2012-08-01T00:13:55.030,NaN,NaN,NaN,nan,2.00,nan
10338352,11750752,2,nan,nan,2012-07-31T23:59:12.620,0,nan,Maybe this can help: \r\r\n\r\r\n \r\r\n\...,1478722.00,nan,NaN,NaN,2012-07-31T23:59:12.620,NaN,NaN,NaN,nan,nan,nan
10338353,11750753,2,nan,nan,2012-07-31T23:59:25.083,1,nan,GetLanguagesForTranslate() returns the set of...,1567202.00,nan,NaN,NaN,2012-07-31T23:59:25.083,NaN,NaN,NaN,nan,nan,nan
10338354,11750755,1,nan,nan,2012-07-31T23:59:26.430,0,12.00,"I have a table, and here are the relevant...",173630.00,nan,NaN,NaN,2012-08-01T03:30:16.943,NaN,NaN,<sql><postgresql><plpgsql><postgresql-9.1>,2.00,nan,nan
10338355,11750756,2,nan,nan,2012-07-31T23:59:29.873,1,nan,The full error reads \r\r\n\r\r\n \r\r\n\...,582.00,nan,NaN,NaN,2012-07-31T23:59:29.873,NaN,NaN,NaN,nan,nan,nan
10338356,11750757,2,nan,nan,2012-07-31T23:59:38.263,0,nan,You need elevated permissions only to copy to...,141172.00,nan,NaN,NaN,2012-07-31T23:59:38.263,NaN,NaN,NaN,nan,3.00,nan
10338357,11750758,2,nan,nan,2012-07-31T23:59:41.953,1,nan,CodePlex offers free TFS hosting with a featu...,729881.00,nan,NaN,NaN,2012-07-31T23:59:41.953,NaN,NaN,NaN,nan,1.00,nan
10338358,11750759,1,nan,11750812.00,2012-07-31T23:59:41.970,0,9.00,i have a database with 16 fields and i just w...,1492051.00,nan,NaN,NaN,2012-08-01T00:14:18.913,NaN,NaN,<vb.net>,1.00,1.00,nan
10338359,11750760,2,nan,nan,2012-07-31T23:59:49.843,0,nan,Passing it through your compiler with full wa...,898258.00,nan,NaN,NaN,2012-07-31T23:59:49.843,NaN,NaN,NaN,nan,nan,nan
10338360,11750761,1,nan,nan,2012-07-31T23:59:57.380,0,3.00,I cant find any examples online on how to u...,1513192.00,nan,NaN,NaN,2012-07-31T23:59:57.380,NaN,NaN,<python><wxpython><wxwidgets><wx><wxruby>,nan,nan,nan

In [46]:
import os
import pandas as pd
comments = pd.read_csv("project data/datasets_2012_final_CombinedCSV/Comments_2012_SO_1.csv")
comments

,Unnamed: 0,Id,PostId,Score,Text,CreationDate,UserId
0,0,1,35314,9.00,not sure why this is getting downvoted -- it i...,2008-09-06T08:07:10.730,1.00
1,1,2,35314,5.00,"Yeah, I didn't believe it until I created a co...",2008-09-06T08:09:52.330,3.00
2,2,4,35195,nan,"I don't see an accepted answer now, I wonder h...",2008-09-06T08:42:16.980,380.00
3,3,8,12755,1.00,"It has to be said, pair programming is an exce...",2008-09-06T11:51:50.207,4642.00
4,4,9,47239,nan,"Jonathan: Wow! Thank you for all of that, you...",2008-09-06T12:26:30.060,4550.00
5,5,10,45651,2.00,It will help if you give some details of which...,2008-09-06T13:38:23.647,242.00
6,6,12,47428,2.00,One of the things that make a url user-friendl...,2008-09-06T13:51:47.843,4642.00
7,7,14,47481,nan,"I agree, both CodeRush and RefactorPro are vis...",2008-09-06T14:15:46.897,4642.00
8,8,15,47373,nan,Just wanted to mention that this is an excelle...,2008-09-06T14:30:40.217,2495.00
9,9,16,47497,nan,"Indeed, the only way to do this is get the ser...",2008-09-06T14:42:35.303,4642.00
10,10,18,47513,1.00,"This advice goes against the spirit of CSS, wh...",2008-09-06T15:02:40.980,2515.00
11,11,19,47466,1.00,It was bad when people used table for everythi...,2008-09-06T15:11:11.227,2515.00
12,12,20,1517,nan,"In the interests of tact, this is the kind of ...",2008-09-06T15:44:39.477,199.00
13,13,21,47527,1.00,The Digg link was the first one I came across ...,2008-09-06T16:00:35.147,658.00
14,14,22,47626,nan,concat infact doesn't do that. I've edited my...,2008-09-06T16:46:31.450,292.00
15,15,24,46538,nan,Why did I receive a downvote? The enhancement ...,2008-09-06T17:33:30.417,4213.00
16,16,25,47626,3.00,infact it does. Look a the first lines of your...,2008-09-06T17:37:35.757,4213.00
17,17,26,47464,nan,Yep. I have been thinking about that and will ...,2008-09-06T19:15:41.277,4585.00
18,18,27,47624,1.00,"""Currently + is implemented using StringBuffer...",2008-09-06T19:25:04.703,4064.00
19,19,28,47290,nan,"You should not have to say that you are ""not a...",2008-09-06T19:40:51.123,4064.00
20,20,30,36050,nan,I am assuming that this will work *only* if th...,2008-09-06T20:14:30.777,4906.00
21,21,31,47777,4.00,That code will fail as .Distinct() returns an ...,2008-09-06T20:21:55.457,3394.00
22,22,33,47513,nan,Bloats the HTML & complicates application of s...,2008-09-06T20:33:10.610,4906.00
23,23,34,47630,nan,"Yes, saw reCaptcha & looks promising but it's ...",2008-09-06T20:44:00.927,4906.00
24,24,37,27429,1.00,This is easily the best solution,2008-09-06T21:40:25.923,4213.00
25,25,38,47631,nan,"Nice article, cic - thanks for sharing!",2008-09-06T22:13:15.563,811.00
26,26,41,47885,2.00,I don't think that's the magic number he was r...,2008-09-06T22:32:45.003,4213.00
27,27,44,47885,1.00,"Maybe you should remove the ""file-format"" and ...",2008-09-06T22:42:13.623,1597.00
28,28,48,47895,nan,Can you be more specific on why eliminating ma...,2008-09-06T23:00:58.880,4213.00
29,29,49,47857,nan,When the hardware integration gets sufficientl...,2008-09-06T23:11:04.613,4071.00
...,...,...,...,...,...,...,...
13252424,252426,15599013,11750602,nan,"@Ignacio: Yes, you are right in that. But it's...",2012-07-31T23:56:14.280,344949.00
13252425,252427,15599014,11718081,nan,"You've got a terrible accept rate, Ehsan. Plea...",2012-07-31T23:56:26.337,589259.00
13252426,252428,15599015,11750668,nan,"hmm, I never thought about that. I'll have to ...",2012-07-31T23:56:33.637,669886.00
13252427,252429,15599016,11750632,nan,Well I think so yes. It's seems that this API ...,2012-07-31T23:56:38.787,295342.00
13252428,252430,15599017,9035474,nan,Added a test case and a bounty.,2012-07-31T23:56:43.357,524555.00
13252429,252431,15599019,11750399,nan,@ernie... Fraggin' *edit* feature!! **:-D** Th...,2012-07-31T23:57:05.947,289011.00
13252430,252432,15599020,11750575,1.00,"In addition to @LarsTech answer, familarize yo...",2012-07-31T23:57:09.333,495455.00
13252431,252433,15599021,11750583,nan,"@DanielFischer, is it will be helpful for key ...",2012-07-31T23:57:19.193,772399.00
13252432,252434,15599023,11749200,nan,"Using Batarang, I was exactly right, there was...",2012-07-31T23:57:29.677,135786.00
13252433,252435,15599024,11750563,nan,Well the other option is to check the user age...,2012-07-31T23:57:32.890,140877.00
13252434,252436,15599025,11750368,2.00,@user1553248: `std::vector<std::vector<std::st...,2012-07-31T23:57:41.343,315052.00
13252435,252437,15599026,11748741,2.00,I agree flash on the web is dying (especially ...,2012-07-31T23:57:54.107,1457439.00
13252436,252438,15599027,11750399,nan,"@BorrajaX you see, and I'm a programmer... and...",2012-07-31T23:57:54.170,592212.00
13252437,252439,15599028,11750168,nan,1GB might actually be the default as per http:...,2012-07-31T23:58:08.203,41655.00
13252438,252440,15599029,11750729,1.00,Have you tried? There are some locations you c...,2012-07-31T23:58:08.613,210709.00
13252439,252441,15599030,11750726,nan,Thank you thank you thank you! Just what I was...,2012-07-31T23:58:16.757,1166285.00
13252440,252442,15599031,11750720,nan,"""makes it sound like you don't need to recurse...",2012-07-31T23:58:21.527,1455028.00
13252441,252443,15599033,11749427,nan,Care to explain the downvote?,2012-07-31T23:58:38.687,788260.00
13252442,252444,15599034,11740530,nan,Why's that? The idea would be that a client re...,2012-07-31T23:58:45.243,364.00
13252443,252445,15599035,11750506,nan,I think I see the problem. Try adding `Rewrite...,2012-07-31T23:58:57.710,1563759.00
13252444,252446,15599036,11750726,1.00,"@iight Please check it again, I had a typo :)",2012-07-31T23:59:16.743,57611.00
13252445,252447,15599037,11749849,nan,"@PhillipMills Nevermind, I'm stupid, that work...",2012-07-31T23:59:18.427,1454835.00
13252446,252448,15599038,11749158,1.00,What version of Ember are you using? Can you p...,2012-07-31T23:59:20.173,365865.00
13252447,252449,15599039,11750476,nan,this is THE perfect answer :),2012-07-31T23:59:22.483,592212.00
13252448,252450,15599041,11749408,nan,what do you mean ? cause I lready specified it,2012-07-31T23:59:27.083,1083453.00
13252449,252451,15599042,11750722,nan,Thank you!! Just what I was looking for.,2012-07-31T23:59:57.443,1166285.00
13252450,252452,15599120,5719657,nan,comment out the DllCall - does it still throw ...,2011-04-19T16:39:17.257,9345.00
13252451,252453,15599121,5719657,nan,"No, it's certainly something to do with the ca...",2011-04-20T08:18:39.010,301811.00
13252452,252454,15599394,4746905,nan,I have found that the VisibleChanged event fir...,2011-07-13T19:51:50.070,21727.00
13252453,252455,15599823,175312,nan,"I realize this was asked about a year ago, but...",2009-10-03T07:15:43.297,30301.00

In [47]:
cols = [0]
comments.drop(comments.columns[cols],axis=1,inplace=True)
comments

,Id,PostId,Score,Text,CreationDate,UserId
0,1,35314,9.00,not sure why this is getting downvoted -- it i...,2008-09-06T08:07:10.730,1.00
1,2,35314,5.00,"Yeah, I didn't believe it until I created a co...",2008-09-06T08:09:52.330,3.00
2,4,35195,nan,"I don't see an accepted answer now, I wonder h...",2008-09-06T08:42:16.980,380.00
3,8,12755,1.00,"It has to be said, pair programming is an exce...",2008-09-06T11:51:50.207,4642.00
4,9,47239,nan,"Jonathan: Wow! Thank you for all of that, you...",2008-09-06T12:26:30.060,4550.00
5,10,45651,2.00,It will help if you give some details of which...,2008-09-06T13:38:23.647,242.00
6,12,47428,2.00,One of the things that make a url user-friendl...,2008-09-06T13:51:47.843,4642.00
7,14,47481,nan,"I agree, both CodeRush and RefactorPro are vis...",2008-09-06T14:15:46.897,4642.00
8,15,47373,nan,Just wanted to mention that this is an excelle...,2008-09-06T14:30:40.217,2495.00
9,16,47497,nan,"Indeed, the only way to do this is get the ser...",2008-09-06T14:42:35.303,4642.00
10,18,47513,1.00,"This advice goes against the spirit of CSS, wh...",2008-09-06T15:02:40.980,2515.00
11,19,47466,1.00,It was bad when people used table for everythi...,2008-09-06T15:11:11.227,2515.00
12,20,1517,nan,"In the interests of tact, this is the kind of ...",2008-09-06T15:44:39.477,199.00
13,21,47527,1.00,The Digg link was the first one I came across ...,2008-09-06T16:00:35.147,658.00
14,22,47626,nan,concat infact doesn't do that. I've edited my...,2008-09-06T16:46:31.450,292.00
15,24,46538,nan,Why did I receive a downvote? The enhancement ...,2008-09-06T17:33:30.417,4213.00
16,25,47626,3.00,infact it does. Look a the first lines of your...,2008-09-06T17:37:35.757,4213.00
17,26,47464,nan,Yep. I have been thinking about that and will ...,2008-09-06T19:15:41.277,4585.00
18,27,47624,1.00,"""Currently + is implemented using StringBuffer...",2008-09-06T19:25:04.703,4064.00
19,28,47290,nan,"You should not have to say that you are ""not a...",2008-09-06T19:40:51.123,4064.00
20,30,36050,nan,I am assuming that this will work *only* if th...,2008-09-06T20:14:30.777,4906.00
21,31,47777,4.00,That code will fail as .Distinct() returns an ...,2008-09-06T20:21:55.457,3394.00
22,33,47513,nan,Bloats the HTML & complicates application of s...,2008-09-06T20:33:10.610,4906.00
23,34,47630,nan,"Yes, saw reCaptcha & looks promising but it's ...",2008-09-06T20:44:00.927,4906.00
24,37,27429,1.00,This is easily the best solution,2008-09-06T21:40:25.923,4213.00
25,38,47631,nan,"Nice article, cic - thanks for sharing!",2008-09-06T22:13:15.563,811.00
26,41,47885,2.00,I don't think that's the magic number he was r...,2008-09-06T22:32:45.003,4213.00
27,44,47885,1.00,"Maybe you should remove the ""file-format"" and ...",2008-09-06T22:42:13.623,1597.00
28,48,47895,nan,Can you be more specific on why eliminating ma...,2008-09-06T23:00:58.880,4213.00
29,49,47857,nan,When the hardware integration gets sufficientl...,2008-09-06T23:11:04.613,4071.00
...,...,...,...,...,...,...
13252424,15599013,11750602,nan,"@Ignacio: Yes, you are right in that. But it's...",2012-07-31T23:56:14.280,344949.00
13252425,15599014,11718081,nan,"You've got a terrible accept rate, Ehsan. Plea...",2012-07-31T23:56:26.337,589259.00
13252426,15599015,11750668,nan,"hmm, I never thought about that. I'll have to ...",2012-07-31T23:56:33.637,669886.00
13252427,15599016,11750632,nan,Well I think so yes. It's seems that this API ...,2012-07-31T23:56:38.787,295342.00
13252428,15599017,9035474,nan,Added a test case and a bounty.,2012-07-31T23:56:43.357,524555.00
13252429,15599019,11750399,nan,@ernie... Fraggin' *edit* feature!! **:-D** Th...,2012-07-31T23:57:05.947,289011.00
13252430,15599020,11750575,1.00,"In addition to @LarsTech answer, familarize yo...",2012-07-31T23:57:09.333,495455.00
13252431,15599021,11750583,nan,"@DanielFischer, is it will be helpful for key ...",2012-07-31T23:57:19.193,772399.00
13252432,15599023,11749200,nan,"Using Batarang, I was exactly right, there was...",2012-07-31T23:57:29.677,135786.00
13252433,15599024,11750563,nan,Well the other option is to check the user age...,2012-07-31T23:57:32.890,140877.00
13252434,15599025,11750368,2.00,@user1553248: `std::vector<std::vector<std::st...,2012-07-31T23:57:41.343,315052.00
13252435,15599026,11748741,2.00,I agree flash on the web is dying (especially ...,2012-07-31T23:57:54.107,1457439.00
13252436,15599027,11750399,nan,"@BorrajaX you see, and I'm a programmer... and...",2012-07-31T23:57:54.170,592212.00
13252437,15599028,11750168,nan,1GB might actually be the default as per http:...,2012-07-31T23:58:08.203,41655.00
13252438,15599029,11750729,1.00,Have you tried? There are some locations you c...,2012-07-31T23:58:08.613,210709.00
13252439,15599030,11750726,nan,Thank you thank you thank you! Just what I was...,2012-07-31T23:58:16.757,1166285.00
13252440,15599031,11750720,nan,"""makes it sound like you don't need to recurse...",2012-07-31T23:58:21.527,1455028.00
13252441,15599033,11749427,nan,Care to explain the downvote?,2012-07-31T23:58:38.687,788260.00
13252442,15599034,11740530,nan,Why's that? The idea would be that a client re...,2012-07-31T23:58:45.243,364.00
13252443,15599035,11750506,nan,I think I see the problem. Try adding `Rewrite...,2012-07-31T23:58:57.710,1563759.00
13252444,15599036,11750726,1.00,"@iight Please check it again, I had a typo :)",2012-07-31T23:59:16.743,57611.00
13252445,15599037,11749849,nan,"@PhillipMills Nevermind, I'm stupid, that work...",2012-07-31T23:59:18.427,1454835.00
13252446,15599038,11749158,1.00,What version of Ember are you using? Can you p...,2012-07-31T23:59:20.173,365865.00
13252447,15599039,11750476,nan,this is THE perfect answer :),2012-07-31T23:59:22.483,592212.00
13252448,15599041,11749408,nan,what do you mean ? cause I lready specified it,2012-07-31T23:59:27.083,1083453.00
13252449,15599042,11750722,nan,Thank you!! Just what I was looking for.,2012-07-31T23:59:57.443,1166285.00
13252450,15599120,5719657,nan,comment out the DllCall - does it still throw ...,2011-04-19T16:39:17.257,9345.00
13252451,15599121,5719657,nan,"No, it's certainly something to do with the ca...",2011-04-20T08:18:39.010,301811.00
13252452,15599394,4746905,nan,I have found that the VisibleChanged event fir...,2011-07-13T19:51:50.070,21727.00
13252453,15599823,175312,nan,"I realize this was asked about a year ago, but...",2009-10-03T07:15:43.297,30301.00

In [48]:
merged_users_posts = pd.read_csv("merged_users_posts_whole_1.csv")
merged_users_posts

,Unnamed: 0,id,name,emailHash,OwnerUserId,PostTypeId,CreationDate,Id
0,0,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T13:36:17.203,3606997
1,1,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-01T12:16:53.587,3607000
2,2,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:48:17.037,3607007
3,3,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-03T03:02:31.127,3607012
4,4,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T11:37:35.990,3607013
5,5,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:45:03.020,3607014
6,6,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-23T12:27:50.593,3607016
7,7,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:35:01.460,3607017
8,8,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T14:17:07.700,3607018
9,9,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:49:10.483,3607030
10,10,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-02T05:57:32.280,3607031
11,11,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-03T12:26:36.060,3607033
12,12,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-27T23:19:48.963,3607034
13,13,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-27T12:22:48.823,3607037
14,14,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-31T05:44:11.327,3607041
15,15,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T17:14:10.223,3607042
16,16,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-29T18:34:22.717,3607043
17,17,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T21:52:12.340,3607044
18,18,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-25T21:59:55.567,3607047
19,19,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T12:56:33.970,3607049
20,20,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-23T05:01:59.090,3607050
21,21,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:17:51.803,3607052
22,22,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T14:44:16.900,3607053
23,23,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-07T21:01:11.410,3607120
24,24,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-21T13:07:45.283,3607191
25,25,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-22T08:45:59.633,3607228
26,26,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-26T18:24:50.097,3607237
27,27,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-08-26T09:39:18.357,3607299
28,28,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-29T02:41:56.317,3607304
29,29,-1.00,Community,a007be5a61f6aa8f3e85ae2fc18dd66e,-1.00,5,2010-07-26T14:41:46.740,3607327
...,...,...,...,...,...,...,...,...
10230463,10230463,1567107.00,Gareth Bowen,378ba4d326f85281ace0735410a67bd5,1567107.00,1,2012-07-31T23:10:18.157,11750349
10230464,10230464,1567108.00,cyberloco,b845b522ddb87203bd2d6207c3dc3ec5,1567108.00,2,2012-07-31T22:44:46.437,11750119
10230465,10230465,1567109.00,Jeremy Gwa,674a19cc2cd50025003f4d198bbfa6fb,1567109.00,1,2012-07-31T22:51:09.377,11750171
10230466,10230466,1567109.00,Jeremy Gwa,674a19cc2cd50025003f4d198bbfa6fb,1567109.00,1,2012-07-31T23:23:59.020,11750471
10230467,10230467,1567112.00,Andy,508a2b9c270e468d5659f4b4b2c8044c,1567112.00,2,2012-07-31T22:49:08.643,11750153
10230468,10230468,1567115.00,Tim Higham,d5e7d575638d61dcfbccdfe4946c3701,1567115.00,2,2012-07-31T22:52:01.630,11750175
10230469,10230469,1567122.00,frinkfree,ffe8e205b35ef15d035bf930ea18a4a9,1567122.00,2,2012-07-31T22:56:09.037,11750211
10230470,10230470,1567123.00,Eric Philmore,2497667570de1a14d49d7965f48328ba,1567123.00,1,2012-07-31T23:06:09.733,11750312
10230471,10230471,1567124.00,DeekMan,0b875468b8aa885867c9e36efd1a2ff8,1567124.00,1,2012-07-31T23:38:37.877,11750608
10230472,10230472,1567130.00,user1567130,b7cec2c453a5a2b5c0ddfbb5633493c7,1567130.00,1,2012-07-31T23:26:12.880,11750501
10230473,10230473,1567132.00,Patrick M,3f525842d66c9be503f9ea5289deec67,1567132.00,2,2012-07-31T23:01:32.390,11750269
10230474,10230474,1567134.00,ben,e1a4c358edf6f5562b83c09e086e0eb3,1567134.00,1,2012-07-31T23:18:41.547,11750424
10230475,10230475,1567138.00,gmvoeth,1c56f4b387f81dd97100e75844268ebe,1567138.00,2,2012-07-31T23:07:21.073,11750320
10230476,10230476,1567142.00,knockoutrose,f16a47c15fa5ff723fce99ec42906149,1567142.00,2,2012-07-31T23:11:26.800,11750357
10230477,10230477,1567145.00,kluo,28b4c26c9a537543bf1dbd9099783b98,1567145.00,2,2012-07-31T23:12:56.433,11750374
10230478,10230478,1567149.00,Tom Androy,47e7eefe52a528eda86d3f857777606d,1567149.00,1,2012-07-31T23:52:54.200,11750707
10230479,10230479,1567150.00,Lyndsay Moon,130cc668c1b92496e96f8c5a4d123063,1567150.00,1,2012-07-31T23:25:20.323,11750491
10230480,10230480,1567164.00,Suyu Zhang,0edf4b6fd29f2e6ab8761c9e4bd3b352,1567164.00,1,2012-07-31T23:40:02.323,11750621
10230481,10230481,1567166.00,Bryan,1a264608b53acce9403ea7dbcf97f1d9,1567166.00,2,2012-07-31T23:29:52.760,11750536
10230482,10230482,1567168.00,righteous.ninja,5f898164dbe37ef4e33c17870313bbe9,1567168.00,2,2012-07-31T23:38:52.320,11750614
10230483,10230483,1567169.00,nimda,37c18547525ce3a560361372d0f598df,1567169.00,2,2012-07-31T23:33:21.643,11750564
10230484,10230484,1567170.00,Hellius666,98728fb1dcc3cf5018503326655de693,1567170.00,2,2012-07-31T23:33:50.723,11750566
10230485,10230485,1567174.00,Raja,bff3158d2a6c0888fa00bddc62426409,1567174.00,1,2012-07-31T23:44:55.367,11750654
10230486,10230486,1567175.00,Brandon,0aea0c92a6bb41685fe459ad33b06198,1567175.00,1,2012-07-31T23:41:43.107,11750631
10230487,10230487,1567179.00,Blake took,eee28c1c79aa4a4338399b933a1c2ab1,1567179.00,1,2012-07-31T23:54:29.380,11750719
10230488,10230488,1567186.00,user1567186,3701f5895191f6b115325164acbbcc27,1567186.00,1,2012-07-31T23:57:18.710,11750742
10230489,10230489,1567187.00,Troy,d8b68858d503b5bb1f4c48a7a7b99ec0,1567187.00,2,2012-07-31T23:49:08.307,11750685
10230490,10230490,1567194.00,user1567194,42e6bec57fdb5b4a9c370d2a4f8d1859,1567194.00,1,2012-07-31T23:58:07.160,11750747
10230491,10230491,1567195.00,SummerDew,d7c17ab89beed7df211dccc61d0db24e,1567195.00,2,2012-07-31T23:53:26.197,11750711
10230492,10230492,1567202.00,Chris Wendt,489e3a1a149c8699096536b7d0c133fb,1567202.00,2,2012-07-31T23:59:25.083,11750753

In [49]:
m_users_posts=merged_users_posts[['id','OwnerUserId','PostTypeId','CreationDate','Id']]
m_users_posts

,id,OwnerUserId,PostTypeId,CreationDate,Id
0,-1.00,-1.00,5,2010-07-22T13:36:17.203,3606997
1,-1.00,-1.00,5,2010-08-01T12:16:53.587,3607000
2,-1.00,-1.00,5,2010-07-22T08:48:17.037,3607007
3,-1.00,-1.00,5,2010-08-03T03:02:31.127,3607012
4,-1.00,-1.00,5,2010-07-22T11:37:35.990,3607013
5,-1.00,-1.00,5,2010-07-22T12:45:03.020,3607014
6,-1.00,-1.00,5,2010-07-23T12:27:50.593,3607016
7,-1.00,-1.00,5,2010-07-22T12:35:01.460,3607017
8,-1.00,-1.00,5,2010-07-22T14:17:07.700,3607018
9,-1.00,-1.00,5,2010-07-22T08:49:10.483,3607030
10,-1.00,-1.00,5,2010-08-02T05:57:32.280,3607031
11,-1.00,-1.00,5,2010-08-03T12:26:36.060,3607033
12,-1.00,-1.00,5,2010-08-27T23:19:48.963,3607034
13,-1.00,-1.00,5,2010-08-27T12:22:48.823,3607037
14,-1.00,-1.00,5,2010-08-31T05:44:11.327,3607041
15,-1.00,-1.00,5,2010-07-22T17:14:10.223,3607042
16,-1.00,-1.00,5,2010-07-29T18:34:22.717,3607043
17,-1.00,-1.00,5,2010-07-22T21:52:12.340,3607044
18,-1.00,-1.00,5,2010-07-25T21:59:55.567,3607047
19,-1.00,-1.00,5,2010-07-22T12:56:33.970,3607049
20,-1.00,-1.00,5,2010-07-23T05:01:59.090,3607050
21,-1.00,-1.00,5,2010-07-22T08:17:51.803,3607052
22,-1.00,-1.00,5,2010-07-22T14:44:16.900,3607053
23,-1.00,-1.00,5,2010-08-07T21:01:11.410,3607120
24,-1.00,-1.00,5,2010-08-21T13:07:45.283,3607191
25,-1.00,-1.00,5,2010-07-22T08:45:59.633,3607228
26,-1.00,-1.00,5,2010-08-26T18:24:50.097,3607237
27,-1.00,-1.00,5,2010-08-26T09:39:18.357,3607299
28,-1.00,-1.00,5,2010-07-29T02:41:56.317,3607304
29,-1.00,-1.00,5,2010-07-26T14:41:46.740,3607327
...,...,...,...,...,...
10230463,1567107.00,1567107.00,1,2012-07-31T23:10:18.157,11750349
10230464,1567108.00,1567108.00,2,2012-07-31T22:44:46.437,11750119
10230465,1567109.00,1567109.00,1,2012-07-31T22:51:09.377,11750171
10230466,1567109.00,1567109.00,1,2012-07-31T23:23:59.020,11750471
10230467,1567112.00,1567112.00,2,2012-07-31T22:49:08.643,11750153
10230468,1567115.00,1567115.00,2,2012-07-31T22:52:01.630,11750175
10230469,1567122.00,1567122.00,2,2012-07-31T22:56:09.037,11750211
10230470,1567123.00,1567123.00,1,2012-07-31T23:06:09.733,11750312
10230471,1567124.00,1567124.00,1,2012-07-31T23:38:37.877,11750608
10230472,1567130.00,1567130.00,1,2012-07-31T23:26:12.880,11750501
10230473,1567132.00,1567132.00,2,2012-07-31T23:01:32.390,11750269
10230474,1567134.00,1567134.00,1,2012-07-31T23:18:41.547,11750424
10230475,1567138.00,1567138.00,2,2012-07-31T23:07:21.073,11750320
10230476,1567142.00,1567142.00,2,2012-07-31T23:11:26.800,11750357
10230477,1567145.00,1567145.00,2,2012-07-31T23:12:56.433,11750374
10230478,1567149.00,1567149.00,1,2012-07-31T23:52:54.200,11750707
10230479,1567150.00,1567150.00,1,2012-07-31T23:25:20.323,11750491
10230480,1567164.00,1567164.00,1,2012-07-31T23:40:02.323,11750621
10230481,1567166.00,1567166.00,2,2012-07-31T23:29:52.760,11750536
10230482,1567168.00,1567168.00,2,2012-07-31T23:38:52.320,11750614
10230483,1567169.00,1567169.00,2,2012-07-31T23:33:21.643,11750564
10230484,1567170.00,1567170.00,2,2012-07-31T23:33:50.723,11750566
10230485,1567174.00,1567174.00,1,2012-07-31T23:44:55.367,11750654
10230486,1567175.00,1567175.00,1,2012-07-31T23:41:43.107,11750631
10230487,1567179.00,1567179.00,1,2012-07-31T23:54:29.380,11750719
10230488,1567186.00,1567186.00,1,2012-07-31T23:57:18.710,11750742
10230489,1567187.00,1567187.00,2,2012-07-31T23:49:08.307,11750685
10230490,1567194.00,1567194.00,1,2012-07-31T23:58:07.160,11750747
10230491,1567195.00,1567195.00,2,2012-07-31T23:53:26.197,11750711
10230492,1567202.00,1567202.00,2,2012-07-31T23:59:25.083,11750753

In [50]:
m_users_posts.groupby('id')['PostTypeId'].describe()

              count  mean  std  min  25%  50%  75%  max
id
-1.00      26355.00  4.49 0.51 3.00 4.00 4.00 5.00 7.00
1.00         158.00  1.91 0.29 1.00 2.00 2.00 2.00 2.00
2.00          12.00  1.42 0.51 1.00 1.00 1.00 2.00 2.00
3.00          38.00  1.84 0.37 1.00 2.00 2.00 2.00 2.00
4.00         178.00  1.94 0.24 1.00 2.00 2.00 2.00 2.00
5.00         343.00  1.87 0.34 1.00 2.00 2.00 2.00 2.00
8.00           1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
9.00          58.00  1.69 0.47 1.00 1.00 2.00 2.00 2.00
11.00          1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
13.00       1288.00  2.00 0.14 1.00 2.00 2.00 2.00 6.00
16.00         10.00  1.90 0.32 1.00 2.00 2.00 2.00 2.00
17.00        609.00  1.95 0.21 1.00 2.00 2.00 2.00 2.00
19.00         14.00  1.86 0.36 1.00 2.00 2.00 2.00 2.00
20.00        112.00  1.81 0.39 1.00 2.00 2.00 2.00 2.00
22.00        189.00  1.92 0.28 1.00 2.00 2.00 2.00 2.00
23.00         10.00  1.40 0.52 1.00 1.00 1.00 2.00 2.00
24.00         14.00  1.93 0.27 1.00 2.00 2.00 2.00 2.00
25.00         83.00  1.59 0.49 1.00 1.00 2.00 2.00 2.00
26.00        350.00  1.66 0.47 1.00 1.00 2.00 2.00 2.00
27.00         13.00  1.69 0.48 1.00 1.00 2.00 2.00 2.00
29.00        491.00  1.88 0.32 1.00 2.00 2.00 2.00 2.00
30.00         82.00  1.88 0.33 1.00 2.00 2.00 2.00 2.00
32.00          5.00  1.60 0.55 1.00 1.00 2.00 2.00 2.00
33.00        116.00  1.70 0.46 1.00 1.00 2.00 2.00 2.00
34.00         70.00  1.93 0.26 1.00 2.00 2.00 2.00 2.00
35.00        219.00  1.91 0.29 1.00 2.00 2.00 2.00 2.00
36.00        113.00  1.95 0.23 1.00 2.00 2.00 2.00 2.00
37.00         72.00  1.67 0.47 1.00 1.00 2.00 2.00 2.00
38.00        141.00  1.28 0.45 1.00 1.00 1.00 2.00 2.00
39.00         70.00  1.77 0.42 1.00 2.00 2.00 2.00 2.00
...             ...   ...  ...  ...  ...  ...  ...  ...
1567106.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567107.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567108.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567109.00     2.00  1.00 0.00 1.00 1.00 1.00 1.00 1.00
1567112.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567115.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567122.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567123.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567124.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567130.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567132.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567134.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567138.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567142.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567145.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567149.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567150.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567164.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567166.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567168.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567169.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567170.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567174.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567175.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567179.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567186.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567187.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567194.00     1.00  1.00  nan 1.00 1.00 1.00 1.00 1.00
1567195.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00
1567202.00     1.00  2.00  nan 2.00 2.00 2.00 2.00 2.00

[837993 rows x 8 columns]

In [51]:
p_users_posts=m_users_posts.groupby('id').size().reset_index(name='noPosts')
p_users_posts

               id  noPosts
0           -1.00    26355
1            1.00      158
2            2.00       12
3            3.00       38
4            4.00      178
5            5.00      343
6            8.00        1
7            9.00       58
8           11.00        1
9           13.00     1288
10          16.00       10
11          17.00      609
12          19.00       14
13          20.00      112
14          22.00      189
15          23.00       10
16          24.00       14
17          25.00       83
18          26.00      350
19          27.00       13
20          29.00      491
21          30.00       82
22          32.00        5
23          33.00      116
24          34.00       70
25          35.00      219
26          36.00      113
27          37.00       72
28          38.00      141
29          39.00       70
...           ...      ...
837963 1567106.00        1
837964 1567107.00        1
837965 1567108.00        1
837966 1567109.00        2
837967 1567112.00        1
837968 1567115.00        1
837969 1567122.00        1
837970 1567123.00        1
837971 1567124.00        1
837972 1567130.00        1
837973 1567132.00        1
837974 1567134.00        1
837975 1567138.00        1
837976 1567142.00        1
837977 1567145.00        1
837978 1567149.00        1
837979 1567150.00        1
837980 1567164.00        1
837981 1567166.00        1
837982 1567168.00        1
837983 1567169.00        1
837984 1567170.00        1
837985 1567174.00        1
837986 1567175.00        1
837987 1567179.00        1
837988 1567186.00        1
837989 1567187.00        1
837990 1567194.00        1
837991 1567195.00        1
837992 1567202.00        1

[837993 rows x 2 columns]

In [52]:
a_users_posts=m_users_posts[(m_users_posts['PostTypeId']==2)].groupby('id').size().reset_index(name='noAns')
a_users_posts

               id  noAns
0            1.00    143
1            2.00      5
2            3.00     32
3            4.00    167
4            5.00    298
5            9.00     40
6           13.00   1279
7           16.00      9
8           17.00    580
9           19.00     12
10          20.00     91
11          22.00    173
12          23.00      4
13          24.00     13
14          25.00     49
15          26.00    232
16          27.00      9
17          29.00    434
18          30.00     72
19          32.00      3
20          33.00     81
21          34.00     65
22          35.00    199
23          36.00    107
24          37.00     48
25          38.00     40
26          39.00     54
27          40.00     82
28          41.00     13
29          42.00    213
...           ...    ...
443330 1566944.00      1
443331 1566946.00      1
443332 1566963.00      1
443333 1566981.00      1
443334 1566983.00      1
443335 1567003.00      1
443336 1567046.00      1
443337 1567047.00      1
443338 1567058.00      1
443339 1567067.00      1
443340 1567080.00      1
443341 1567089.00      1
443342 1567091.00      1
443343 1567100.00      1
443344 1567106.00      1
443345 1567108.00      1
443346 1567112.00      1
443347 1567115.00      1
443348 1567122.00      1
443349 1567132.00      1
443350 1567138.00      1
443351 1567142.00      1
443352 1567145.00      1
443353 1567166.00      1
443354 1567168.00      1
443355 1567169.00      1
443356 1567170.00      1
443357 1567187.00      1
443358 1567195.00      1
443359 1567202.00      1

[443360 rows x 2 columns]

In [53]:
q_users_posts=m_users_posts[(m_users_posts['PostTypeId']==1)].groupby('id').size().reset_index(name='noQues')
q_users_posts

               id  noQues
0            1.00      15
1            2.00       7
2            3.00       6
3            4.00      11
4            5.00      45
5            8.00       1
6            9.00      18
7           11.00       1
8           13.00       8
9           16.00       1
10          17.00      29
11          19.00       2
12          20.00      21
13          22.00      16
14          23.00       6
15          24.00       1
16          25.00      34
17          26.00     118
18          27.00       4
19          29.00      57
20          30.00      10
21          32.00       2
22          33.00      35
23          34.00       5
24          35.00      20
25          36.00       6
26          37.00      24
27          38.00     101
28          39.00      16
29          40.00      29
...           ...     ...
625080 1567060.00       1
625081 1567062.00       1
625082 1567063.00       1
625083 1567068.00       1
625084 1567069.00       1
625085 1567070.00       1
625086 1567072.00       1
625087 1567078.00       1
625088 1567079.00       1
625089 1567083.00       1
625090 1567087.00       1
625091 1567088.00       2
625092 1567094.00       1
625093 1567095.00       1
625094 1567097.00       1
625095 1567103.00       1
625096 1567107.00       1
625097 1567109.00       2
625098 1567123.00       1
625099 1567124.00       1
625100 1567130.00       1
625101 1567134.00       1
625102 1567149.00       1
625103 1567150.00       1
625104 1567164.00       1
625105 1567174.00       1
625106 1567175.00       1
625107 1567179.00       1
625108 1567186.00       1
625109 1567194.00       1

[625110 rows x 2 columns]

In [54]:
pq = p_users_posts.merge(q_users_posts, on='id', how='outer')
pq

               id  noPosts  noQues
0           -1.00    26355     nan
1            1.00      158   15.00
2            2.00       12    7.00
3            3.00       38    6.00
4            4.00      178   11.00
5            5.00      343   45.00
6            8.00        1    1.00
7            9.00       58   18.00
8           11.00        1    1.00
9           13.00     1288    8.00
10          16.00       10    1.00
11          17.00      609   29.00
12          19.00       14    2.00
13          20.00      112   21.00
14          22.00      189   16.00
15          23.00       10    6.00
16          24.00       14    1.00
17          25.00       83   34.00
18          26.00      350  118.00
19          27.00       13    4.00
20          29.00      491   57.00
21          30.00       82   10.00
22          32.00        5    2.00
23          33.00      116   35.00
24          34.00       70    5.00
25          35.00      219   20.00
26          36.00      113    6.00
27          37.00       72   24.00
28          38.00      141  101.00
29          39.00       70   16.00
...           ...      ...     ...
837963 1567106.00        1     nan
837964 1567107.00        1    1.00
837965 1567108.00        1     nan
837966 1567109.00        2    2.00
837967 1567112.00        1     nan
837968 1567115.00        1     nan
837969 1567122.00        1     nan
837970 1567123.00        1    1.00
837971 1567124.00        1    1.00
837972 1567130.00        1    1.00
837973 1567132.00        1     nan
837974 1567134.00        1    1.00
837975 1567138.00        1     nan
837976 1567142.00        1     nan
837977 1567145.00        1     nan
837978 1567149.00        1    1.00
837979 1567150.00        1    1.00
837980 1567164.00        1    1.00
837981 1567166.00        1     nan
837982 1567168.00        1     nan
837983 1567169.00        1     nan
837984 1567170.00        1     nan
837985 1567174.00        1    1.00
837986 1567175.00        1    1.00
837987 1567179.00        1    1.00
837988 1567186.00        1    1.00
837989 1567187.00        1     nan
837990 1567194.00        1    1.00
837991 1567195.00        1     nan
837992 1567202.00        1     nan

[837993 rows x 3 columns]

In [55]:
qap = pq.merge(a_users_posts, on='id', how='outer')
qap

               id  noPosts  noQues   noAns
0           -1.00    26355     nan     nan
1            1.00      158   15.00  143.00
2            2.00       12    7.00    5.00
3            3.00       38    6.00   32.00
4            4.00      178   11.00  167.00
5            5.00      343   45.00  298.00
6            8.00        1    1.00     nan
7            9.00       58   18.00   40.00
8           11.00        1    1.00     nan
9           13.00     1288    8.00 1279.00
10          16.00       10    1.00    9.00
11          17.00      609   29.00  580.00
12          19.00       14    2.00   12.00
13          20.00      112   21.00   91.00
14          22.00      189   16.00  173.00
15          23.00       10    6.00    4.00
16          24.00       14    1.00   13.00
17          25.00       83   34.00   49.00
18          26.00      350  118.00  232.00
19          27.00       13    4.00    9.00
20          29.00      491   57.00  434.00
21          30.00       82   10.00   72.00
22          32.00        5    2.00    3.00
23          33.00      116   35.00   81.00
24          34.00       70    5.00   65.00
25          35.00      219   20.00  199.00
26          36.00      113    6.00  107.00
27          37.00       72   24.00   48.00
28          38.00      141  101.00   40.00
29          39.00       70   16.00   54.00
...           ...      ...     ...     ...
837963 1567106.00        1     nan    1.00
837964 1567107.00        1    1.00     nan
837965 1567108.00        1     nan    1.00
837966 1567109.00        2    2.00     nan
837967 1567112.00        1     nan    1.00
837968 1567115.00        1     nan    1.00
837969 1567122.00        1     nan    1.00
837970 1567123.00        1    1.00     nan
837971 1567124.00        1    1.00     nan
837972 1567130.00        1    1.00     nan
837973 1567132.00        1     nan    1.00
837974 1567134.00        1    1.00     nan
837975 1567138.00        1     nan    1.00
837976 1567142.00        1     nan    1.00
837977 1567145.00        1     nan    1.00
837978 1567149.00        1    1.00     nan
837979 1567150.00        1    1.00     nan
837980 1567164.00        1    1.00     nan
837981 1567166.00        1     nan    1.00
837982 1567168.00        1     nan    1.00
837983 1567169.00        1     nan    1.00
837984 1567170.00        1     nan    1.00
837985 1567174.00        1    1.00     nan
837986 1567175.00        1    1.00     nan
837987 1567179.00        1    1.00     nan
837988 1567186.00        1    1.00     nan
837989 1567187.00        1     nan    1.00
837990 1567194.00        1    1.00     nan
837991 1567195.00        1     nan    1.00
837992 1567202.00        1     nan    1.00

[837993 rows x 4 columns]

In [56]:
qap=qap.fillna(0)

In [57]:
qap

               id  noPosts  noQues   noAns
0           -1.00    26355    0.00    0.00
1            1.00      158   15.00  143.00
2            2.00       12    7.00    5.00
3            3.00       38    6.00   32.00
4            4.00      178   11.00  167.00
5            5.00      343   45.00  298.00
6            8.00        1    1.00    0.00
7            9.00       58   18.00   40.00
8           11.00        1    1.00    0.00
9           13.00     1288    8.00 1279.00
10          16.00       10    1.00    9.00
11          17.00      609   29.00  580.00
12          19.00       14    2.00   12.00
13          20.00      112   21.00   91.00
14          22.00      189   16.00  173.00
15          23.00       10    6.00    4.00
16          24.00       14    1.00   13.00
17          25.00       83   34.00   49.00
18          26.00      350  118.00  232.00
19          27.00       13    4.00    9.00
20          29.00      491   57.00  434.00
21          30.00       82   10.00   72.00
22          32.00        5    2.00    3.00
23          33.00      116   35.00   81.00
24          34.00       70    5.00   65.00
25          35.00      219   20.00  199.00
26          36.00      113    6.00  107.00
27          37.00       72   24.00   48.00
28          38.00      141  101.00   40.00
29          39.00       70   16.00   54.00
...           ...      ...     ...     ...
837963 1567106.00        1    0.00    1.00
837964 1567107.00        1    1.00    0.00
837965 1567108.00        1    0.00    1.00
837966 1567109.00        2    2.00    0.00
837967 1567112.00        1    0.00    1.00
837968 1567115.00        1    0.00    1.00
837969 1567122.00        1    0.00    1.00
837970 1567123.00        1    1.00    0.00
837971 1567124.00        1    1.00    0.00
837972 1567130.00        1    1.00    0.00
837973 1567132.00        1    0.00    1.00
837974 1567134.00        1    1.00    0.00
837975 1567138.00        1    0.00    1.00
837976 1567142.00        1    0.00    1.00
837977 1567145.00        1    0.00    1.00
837978 1567149.00        1    1.00    0.00
837979 1567150.00        1    1.00    0.00
837980 1567164.00        1    1.00    0.00
837981 1567166.00        1    0.00    1.00
837982 1567168.00        1    0.00    1.00
837983 1567169.00        1    0.00    1.00
837984 1567170.00        1    0.00    1.00
837985 1567174.00        1    1.00    0.00
837986 1567175.00        1    1.00    0.00
837987 1567179.00        1    1.00    0.00
837988 1567186.00        1    1.00    0.00
837989 1567187.00        1    0.00    1.00
837990 1567194.00        1    1.00    0.00
837991 1567195.00        1    0.00    1.00
837992 1567202.00        1    0.00    1.00

[837993 rows x 4 columns]

In [58]:
qap['sum']=qap['noQues']+qap['noAns']

In [59]:
qap

               id  noPosts  noQues   noAns     sum
0           -1.00    26355    0.00    0.00    0.00
1            1.00      158   15.00  143.00  158.00
2            2.00       12    7.00    5.00   12.00
3            3.00       38    6.00   32.00   38.00
4            4.00      178   11.00  167.00  178.00
5            5.00      343   45.00  298.00  343.00
6            8.00        1    1.00    0.00    1.00
7            9.00       58   18.00   40.00   58.00
8           11.00        1    1.00    0.00    1.00
9           13.00     1288    8.00 1279.00 1287.00
10          16.00       10    1.00    9.00   10.00
11          17.00      609   29.00  580.00  609.00
12          19.00       14    2.00   12.00   14.00
13          20.00      112   21.00   91.00  112.00
14          22.00      189   16.00  173.00  189.00
15          23.00       10    6.00    4.00   10.00
16          24.00       14    1.00   13.00   14.00
17          25.00       83   34.00   49.00   83.00
18          26.00      350  118.00  232.00  350.00
19          27.00       13    4.00    9.00   13.00
20          29.00      491   57.00  434.00  491.00
21          30.00       82   10.00   72.00   82.00
22          32.00        5    2.00    3.00    5.00
23          33.00      116   35.00   81.00  116.00
24          34.00       70    5.00   65.00   70.00
25          35.00      219   20.00  199.00  219.00
26          36.00      113    6.00  107.00  113.00
27          37.00       72   24.00   48.00   72.00
28          38.00      141  101.00   40.00  141.00
29          39.00       70   16.00   54.00   70.00
...           ...      ...     ...     ...     ...
837963 1567106.00        1    0.00    1.00    1.00
837964 1567107.00        1    1.00    0.00    1.00
837965 1567108.00        1    0.00    1.00    1.00
837966 1567109.00        2    2.00    0.00    2.00
837967 1567112.00        1    0.00    1.00    1.00
837968 1567115.00        1    0.00    1.00    1.00
837969 1567122.00        1    0.00    1.00    1.00
837970 1567123.00        1    1.00    0.00    1.00
837971 1567124.00        1    1.00    0.00    1.00
837972 1567130.00        1    1.00    0.00    1.00
837973 1567132.00        1    0.00    1.00    1.00
837974 1567134.00        1    1.00    0.00    1.00
837975 1567138.00        1    0.00    1.00    1.00
837976 1567142.00        1    0.00    1.00    1.00
837977 1567145.00        1    0.00    1.00    1.00
837978 1567149.00        1    1.00    0.00    1.00
837979 1567150.00        1    1.00    0.00    1.00
837980 1567164.00        1    1.00    0.00    1.00
837981 1567166.00        1    0.00    1.00    1.00
837982 1567168.00        1    0.00    1.00    1.00
837983 1567169.00        1    0.00    1.00    1.00
837984 1567170.00        1    0.00    1.00    1.00
837985 1567174.00        1    1.00    0.00    1.00
837986 1567175.00        1    1.00    0.00    1.00
837987 1567179.00        1    1.00    0.00    1.00
837988 1567186.00        1    1.00    0.00    1.00
837989 1567187.00        1    0.00    1.00    1.00
837990 1567194.00        1    1.00    0.00    1.00
837991 1567195.00        1    0.00    1.00    1.00
837992 1567202.00        1    0.00    1.00    1.00

[837993 rows x 5 columns]

In [60]:
qap.loc[~(qap['noPosts'] == qap['sum'])]

               id  noPosts  noQues    noAns      sum
0           -1.00    26355    0.00     0.00     0.00
9           13.00     1288    8.00  1279.00  1287.00
210        267.00     1978  253.00  1724.00  1977.00
329        419.00     1228  144.00  1083.00  1227.00
838       1114.00      426   30.00   394.00   424.00
1865      2598.00      776   44.00   730.00   774.00
2089      2915.00      734  107.00   626.00   733.00
2121      2961.00      407   40.00   366.00   406.00
2360      3312.00      349    4.00   344.00   348.00
3812      5640.00      268   12.00   255.00   267.00
4319      6521.00     1197   18.00  1178.00  1196.00
4755      7412.00     1362   53.00  1307.00  1360.00
5744      9536.00      278   47.00   230.00   277.00
6938     11995.00      630   52.00   577.00   629.00
6966     12048.00      630   65.00   564.00   629.00
7012     12178.00      965   45.00   919.00   964.00
7522     13279.00     1430   47.00  1382.00  1429.00
7876     14065.00     2125   52.00  2072.00  2124.00
8347     15245.00     1144   29.00  1114.00  1143.00
8945     16587.00      557   33.00   521.00   554.00
10292    19679.00     1327    9.00  1315.00  1324.00
11919    23528.00     2431  148.00  2282.00  2430.00
12632    25300.00      781   64.00   716.00   780.00
13089    26414.00      647  162.00   484.00   646.00
15855    34397.00    10281   52.00 10228.00 10280.00
17684    40322.00      444  191.00   252.00   443.00
18565    42979.00      182   31.00   150.00   181.00
20801    50049.00      670   32.00   637.00   669.00
21024    50776.00     1248   10.00  1236.00  1246.00
22140    54200.00      431   11.00   419.00   430.00
...           ...      ...     ...      ...      ...
138011  309308.00      549   10.00   537.00   547.00
141332  314488.00     1674   24.00  1649.00  1673.00
145765  321468.00      491    8.00   482.00   490.00
150036  328193.00     1318   41.00  1276.00  1317.00
155725  337227.00      760    2.00   757.00   759.00
156586  338665.00      962   14.00   947.00   961.00
161030  345708.00      500   10.00   489.00   499.00
166153  353790.00     1034   96.00   937.00  1033.00
182717  379693.00      920   88.00   831.00   919.00
192086  394167.00      100    4.00    95.00    99.00
193577  396458.00      727   33.00   693.00   726.00
195244  399037.00      660   17.00   642.00   659.00
200599  407418.00       49   45.00     3.00    48.00
207458  418183.00      399    5.00   393.00   398.00
211461  424413.00      157   37.00   119.00   156.00
220002  437768.00      536   33.00   502.00   535.00
236092  463065.00      353  121.00   231.00   352.00
247135  481154.00      256    6.00   249.00   255.00
274402  525868.00       38    1.00    36.00    37.00
292294  555384.00      573   71.00   500.00   571.00
293908  558021.00      615    6.00   608.00   614.00
296156  561731.00     2080   76.00  2002.00  2078.00
347523  646382.00      294    2.00   291.00   293.00
355602  659804.00     1557    2.00  1554.00  1556.00
383444  707111.00     1866   44.00  1820.00  1864.00
417454  764846.00     1854   62.00  1791.00  1853.00
499284  900873.00      414    2.00   411.00   413.00
528238  950430.00      207    3.00   203.00   206.00
553427  996493.00      371   28.00   342.00   370.00
754541 1386886.00     1621   42.00  1578.00  1620.00

[118 rows x 5 columns]

In [65]:
qap['z-score_denominator']=qap[['noAns','noQues']].sum(axis=1).pow(1./2)

In [67]:
qap['z-score_numerator']=qap['noAns']-qap['noQues']

In [68]:
qap

,id,noPosts,noQues,noAns,sum,z-score_denominator,z-score_numerator
0,-1.00,26355,0.00,0.00,0.00,0.00,0.00
1,1.00,158,15.00,143.00,158.00,12.57,128.00
2,2.00,12,7.00,5.00,12.00,3.46,-2.00
3,3.00,38,6.00,32.00,38.00,6.16,26.00
4,4.00,178,11.00,167.00,178.00,13.34,156.00
5,5.00,343,45.00,298.00,343.00,18.52,253.00
6,8.00,1,1.00,0.00,1.00,1.00,-1.00
7,9.00,58,18.00,40.00,58.00,7.62,22.00
8,11.00,1,1.00,0.00,1.00,1.00,-1.00
9,13.00,1288,8.00,1279.00,1287.00,35.87,1271.00
10,16.00,10,1.00,9.00,10.00,3.16,8.00
11,17.00,609,29.00,580.00,609.00,24.68,551.00
12,19.00,14,2.00,12.00,14.00,3.74,10.00
13,20.00,112,21.00,91.00,112.00,10.58,70.00
14,22.00,189,16.00,173.00,189.00,13.75,157.00
15,23.00,10,6.00,4.00,10.00,3.16,-2.00
16,24.00,14,1.00,13.00,14.00,3.74,12.00
17,25.00,83,34.00,49.00,83.00,9.11,15.00
18,26.00,350,118.00,232.00,350.00,18.71,114.00
19,27.00,13,4.00,9.00,13.00,3.61,5.00
20,29.00,491,57.00,434.00,491.00,22.16,377.00
21,30.00,82,10.00,72.00,82.00,9.06,62.00
22,32.00,5,2.00,3.00,5.00,2.24,1.00
23,33.00,116,35.00,81.00,116.00,10.77,46.00
24,34.00,70,5.00,65.00,70.00,8.37,60.00
25,35.00,219,20.00,199.00,219.00,14.80,179.00
26,36.00,113,6.00,107.00,113.00,10.63,101.00
27,37.00,72,24.00,48.00,72.00,8.49,24.00
28,38.00,141,101.00,40.00,141.00,11.87,-61.00
29,39.00,70,16.00,54.00,70.00,8.37,38.00
...,...,...,...,...,...,...,...
837963,1567106.00,1,0.00,1.00,1.00,1.00,1.00
837964,1567107.00,1,1.00,0.00,1.00,1.00,-1.00
837965,1567108.00,1,0.00,1.00,1.00,1.00,1.00
837966,1567109.00,2,2.00,0.00,2.00,1.41,-2.00
837967,1567112.00,1,0.00,1.00,1.00,1.00,1.00
837968,1567115.00,1,0.00,1.00,1.00,1.00,1.00
837969,1567122.00,1,0.00,1.00,1.00,1.00,1.00
837970,1567123.00,1,1.00,0.00,1.00,1.00,-1.00
837971,1567124.00,1,1.00,0.00,1.00,1.00,-1.00
837972,1567130.00,1,1.00,0.00,1.00,1.00,-1.00
837973,1567132.00,1,0.00,1.00,1.00,1.00,1.00
837974,1567134.00,1,1.00,0.00,1.00,1.00,-1.00
837975,1567138.00,1,0.00,1.00,1.00,1.00,1.00
837976,1567142.00,1,0.00,1.00,1.00,1.00,1.00
837977,1567145.00,1,0.00,1.00,1.00,1.00,1.00
837978,1567149.00,1,1.00,0.00,1.00,1.00,-1.00
837979,1567150.00,1,1.00,0.00,1.00,1.00,-1.00
837980,1567164.00,1,1.00,0.00,1.00,1.00,-1.00
837981,1567166.00,1,0.00,1.00,1.00,1.00,1.00
837982,1567168.00,1,0.00,1.00,1.00,1.00,1.00
837983,1567169.00,1,0.00,1.00,1.00,1.00,1.00
837984,1567170.00,1,0.00,1.00,1.00,1.00,1.00
837985,1567174.00,1,1.00,0.00,1.00,1.00,-1.00
837986,1567175.00,1,1.00,0.00,1.00,1.00,-1.00
837987,1567179.00,1,1.00,0.00,1.00,1.00,-1.00
837988,1567186.00,1,1.00,0.00,1.00,1.00,-1.00
837989,1567187.00,1,0.00,1.00,1.00,1.00,1.00
837990,1567194.00,1,1.00,0.00,1.00,1.00,-1.00
837991,1567195.00,1,0.00,1.00,1.00,1.00,1.00
837992,1567202.00,1,0.00,1.00,1.00,1.00,1.00

In [69]:
qap['z-score']= (qap['z-score_numerator'])/(qap['z-score_denominator'])

In [70]:
qap

,id,noPosts,noQues,noAns,sum,z-score_denominator,z-score_numerator,z-score
0,-1.00,26355,0.00,0.00,0.00,0.00,0.00,nan
1,1.00,158,15.00,143.00,158.00,12.57,128.00,10.18
2,2.00,12,7.00,5.00,12.00,3.46,-2.00,-0.58
3,3.00,38,6.00,32.00,38.00,6.16,26.00,4.22
4,4.00,178,11.00,167.00,178.00,13.34,156.00,11.69
5,5.00,343,45.00,298.00,343.00,18.52,253.00,13.66
6,8.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
7,9.00,58,18.00,40.00,58.00,7.62,22.00,2.89
8,11.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
9,13.00,1288,8.00,1279.00,1287.00,35.87,1271.00,35.43
10,16.00,10,1.00,9.00,10.00,3.16,8.00,2.53
11,17.00,609,29.00,580.00,609.00,24.68,551.00,22.33
12,19.00,14,2.00,12.00,14.00,3.74,10.00,2.67
13,20.00,112,21.00,91.00,112.00,10.58,70.00,6.61
14,22.00,189,16.00,173.00,189.00,13.75,157.00,11.42
15,23.00,10,6.00,4.00,10.00,3.16,-2.00,-0.63
16,24.00,14,1.00,13.00,14.00,3.74,12.00,3.21
17,25.00,83,34.00,49.00,83.00,9.11,15.00,1.65
18,26.00,350,118.00,232.00,350.00,18.71,114.00,6.09
19,27.00,13,4.00,9.00,13.00,3.61,5.00,1.39
20,29.00,491,57.00,434.00,491.00,22.16,377.00,17.01
21,30.00,82,10.00,72.00,82.00,9.06,62.00,6.85
22,32.00,5,2.00,3.00,5.00,2.24,1.00,0.45
23,33.00,116,35.00,81.00,116.00,10.77,46.00,4.27
24,34.00,70,5.00,65.00,70.00,8.37,60.00,7.17
25,35.00,219,20.00,199.00,219.00,14.80,179.00,12.10
26,36.00,113,6.00,107.00,113.00,10.63,101.00,9.50
27,37.00,72,24.00,48.00,72.00,8.49,24.00,2.83
28,38.00,141,101.00,40.00,141.00,11.87,-61.00,-5.14
29,39.00,70,16.00,54.00,70.00,8.37,38.00,4.54
...,...,...,...,...,...,...,...,...
837963,1567106.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837964,1567107.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837965,1567108.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837966,1567109.00,2,2.00,0.00,2.00,1.41,-2.00,-1.41
837967,1567112.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837968,1567115.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837969,1567122.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837970,1567123.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837971,1567124.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837972,1567130.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837973,1567132.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837974,1567134.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837975,1567138.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837976,1567142.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837977,1567145.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837978,1567149.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837979,1567150.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837980,1567164.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837981,1567166.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837982,1567168.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837983,1567169.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837984,1567170.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837985,1567174.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837986,1567175.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837987,1567179.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837988,1567186.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837989,1567187.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837990,1567194.00,1,1.00,0.00,1.00,1.00,-1.00,-1.00
837991,1567195.00,1,0.00,1.00,1.00,1.00,1.00,1.00
837992,1567202.00,1,0.00,1.00,1.00,1.00,1.00,1.00

In [71]:
qap.to_csv('qap_z-score.csv')

In [62]:
NUMpostsNOTequalTOsum = qap.loc[~(qap['noPosts'] == qap['sum'])]

In [63]:
NUMpostsNOTequalTOsum

               id  noPosts  noQues    noAns      sum
0           -1.00    26355    0.00     0.00     0.00
9           13.00     1288    8.00  1279.00  1287.00
210        267.00     1978  253.00  1724.00  1977.00
329        419.00     1228  144.00  1083.00  1227.00
838       1114.00      426   30.00   394.00   424.00
1865      2598.00      776   44.00   730.00   774.00
2089      2915.00      734  107.00   626.00   733.00
2121      2961.00      407   40.00   366.00   406.00
2360      3312.00      349    4.00   344.00   348.00
3812      5640.00      268   12.00   255.00   267.00
4319      6521.00     1197   18.00  1178.00  1196.00
4755      7412.00     1362   53.00  1307.00  1360.00
5744      9536.00      278   47.00   230.00   277.00
6938     11995.00      630   52.00   577.00   629.00
6966     12048.00      630   65.00   564.00   629.00
7012     12178.00      965   45.00   919.00   964.00
7522     13279.00     1430   47.00  1382.00  1429.00
7876     14065.00     2125   52.00  2072.00  2124.00
8347     15245.00     1144   29.00  1114.00  1143.00
8945     16587.00      557   33.00   521.00   554.00
10292    19679.00     1327    9.00  1315.00  1324.00
11919    23528.00     2431  148.00  2282.00  2430.00
12632    25300.00      781   64.00   716.00   780.00
13089    26414.00      647  162.00   484.00   646.00
15855    34397.00    10281   52.00 10228.00 10280.00
17684    40322.00      444  191.00   252.00   443.00
18565    42979.00      182   31.00   150.00   181.00
20801    50049.00      670   32.00   637.00   669.00
21024    50776.00     1248   10.00  1236.00  1246.00
22140    54200.00      431   11.00   419.00   430.00
...           ...      ...     ...      ...      ...
138011  309308.00      549   10.00   537.00   547.00
141332  314488.00     1674   24.00  1649.00  1673.00
145765  321468.00      491    8.00   482.00   490.00
150036  328193.00     1318   41.00  1276.00  1317.00
155725  337227.00      760    2.00   757.00   759.00
156586  338665.00      962   14.00   947.00   961.00
161030  345708.00      500   10.00   489.00   499.00
166153  353790.00     1034   96.00   937.00  1033.00
182717  379693.00      920   88.00   831.00   919.00
192086  394167.00      100    4.00    95.00    99.00
193577  396458.00      727   33.00   693.00   726.00
195244  399037.00      660   17.00   642.00   659.00
200599  407418.00       49   45.00     3.00    48.00
207458  418183.00      399    5.00   393.00   398.00
211461  424413.00      157   37.00   119.00   156.00
220002  437768.00      536   33.00   502.00   535.00
236092  463065.00      353  121.00   231.00   352.00
247135  481154.00      256    6.00   249.00   255.00
274402  525868.00       38    1.00    36.00    37.00
292294  555384.00      573   71.00   500.00   571.00
293908  558021.00      615    6.00   608.00   614.00
296156  561731.00     2080   76.00  2002.00  2078.00
347523  646382.00      294    2.00   291.00   293.00
355602  659804.00     1557    2.00  1554.00  1556.00
383444  707111.00     1866   44.00  1820.00  1864.00
417454  764846.00     1854   62.00  1791.00  1853.00
499284  900873.00      414    2.00   411.00   413.00
528238  950430.00      207    3.00   203.00   206.00
553427  996493.00      371   28.00   342.00   370.00
754541 1386886.00     1621   42.00  1578.00  1620.00

[118 rows x 5 columns]

## number of post edits

## Inner Join on user id and LastEditorUserId

In [72]:
m_users1 = users[['id','creationDate','name','lastAccess']]
m_users1

,id,creationDate,name,lastAccess
0,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810
1,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447
2,2.00,2008-07-31T14:22:31.287,Geoff Dalgas,2012-07-31T23:38:17.330
3,3.00,2008-07-31T14:22:31.287,Jarrod Dixon,2012-07-31T22:49:53.213
4,4.00,2008-07-31T14:22:31.317,Joel Spolsky,2012-08-01T03:37:02.227
5,5.00,2008-07-31T14:22:31.317,Jon Galloway,2012-07-31T22:31:50.930
6,8.00,2008-07-31T21:33:24.057,Eggs McLaren,2012-07-20T18:25:48.217
7,9.00,2008-07-31T21:35:26.517,Kevin Dente,2012-07-31T23:07:18.440
8,10.00,2008-07-31T21:57:06.240,Sneakers O'Toole,2012-06-19T19:35:43.433
9,11.00,2008-08-01T00:59:11.147,Anonymous User,2008-08-01T00:59:11.147
10,13.00,2008-08-01T04:18:04.943,Chris Jester-Young,2012-07-31T22:48:22.820
11,16.00,2008-08-01T12:01:53.023,Rodrigo Sieiro,2012-08-01T03:21:30.773
12,17.00,2008-08-01T12:02:21.617,Nick Berardi,2012-08-01T02:00:20.007
13,19.00,2008-08-01T12:05:14.233,Mads Kristiansen,2012-03-12T13:10:34.120
14,20.00,2008-08-01T12:09:11.010,Tom,2012-07-24T15:29:32.373
15,22.00,2008-08-01T12:11:11.897,maclema,2012-07-31T18:57:39.533
16,23.00,2008-08-01T12:11:43.703,Jax,2012-07-31T20:57:47.477
17,24.00,2008-08-01T12:12:53.453,braklet,2012-07-26T21:55:13.853
18,25.00,2008-08-01T12:15:23.243,CodingWithoutComments,2012-05-20T22:46:32.797
19,26.00,2008-08-01T12:18:14.520,Shawn,2012-07-31T00:14:51.510
20,27.00,2008-08-01T12:21:40.020,denny,2012-07-30T16:20:09.330
21,29.00,2008-08-01T12:24:53.820,Michael Haren,2012-08-01T03:23:28.853
22,30.00,2008-08-01T12:25:44.817,Grant,2012-07-31T20:37:07.323
23,32.00,2008-08-01T12:31:17.783,TimM,2011-10-09T22:12:56.320
24,33.00,2008-08-01T12:32:10.963,John,2012-07-31T15:26:21.493
25,34.00,2008-08-01T12:39:52.493,Karl Seguin,2012-02-04T00:55:28.387
26,35.00,2008-08-01T12:43:07.713,Greg Hurlman,2012-07-30T15:47:20.363
27,36.00,2008-08-01T12:43:55.683,Pat,2012-07-31T22:16:20.847
28,37.00,2008-08-01T12:44:00.723,Wally Lawless,2012-07-30T19:45:03.893
29,38.00,2008-08-01T12:44:28.833,blcArmadillo,2012-07-31T18:15:49.997
...,...,...,...,...
1295590,1567174.00,2012-07-31T23:37:24.897,Raja,2012-07-31T23:37:24.897
1295591,1567175.00,2012-07-31T23:37:38.583,Brandon,2012-07-31T23:37:38.583
1295592,1567176.00,2012-07-31T23:38:45.880,alfonsob,2012-07-31T23:38:45.880
1295593,1567177.00,2012-07-31T23:39:35.303,Tomas Valettini,2012-07-31T23:39:35.303
1295594,1567178.00,2012-07-31T23:40:04.807,Derek Knox,2012-07-31T23:40:04.807
1295595,1567179.00,2012-07-31T23:40:09.717,Blake took,2012-08-01T00:36:09.313
1295596,1567180.00,2012-07-31T23:40:16.787,Alejo Hinestrosa,2012-07-31T23:40:16.787
1295597,1567181.00,2012-07-31T23:41:18.453,user1567181,2012-08-01T01:23:06.057
1295598,1567182.00,2012-07-31T23:41:45.597,user1567182,2012-07-31T23:57:15.510
1295599,1567183.00,2012-07-31T23:42:07.960,Nic Dahlquist,2012-08-01T00:48:53.443
1295600,1567184.00,2012-07-31T23:44:12.433,user1567184,2012-08-01T00:48:39.963
1295601,1567185.00,2012-07-31T23:44:38.447,user1567185,2012-08-01T01:03:15.960
1295602,1567186.00,2012-07-31T23:45:06.600,user1567186,2012-08-01T01:42:14.800
1295603,1567187.00,2012-07-31T23:49:08.307,Troy,2012-08-01T03:57:45.660
1295604,1567188.00,2012-07-31T23:50:16.980,Mazin SW,2012-08-01T03:24:15.943
1295605,1567189.00,2012-07-31T23:50:47.993,yonathanhalim,2012-08-01T02:28:52.707
1295606,1567190.00,2012-07-31T23:50:55.447,Dan,2012-07-31T23:50:55.447
1295607,1567191.00,2012-07-31T23:51:47.147,user1567191,2012-07-31T23:51:47.147
1295608,1567192.00,2012-07-31T23:52:08.227,user1567192,2012-08-01T00:59:43.577
1295609,1567193.00,2012-07-31T23:52:45.777,Chris Webb,2012-08-01T04:47:50.533
1295610,1567194.00,2012-07-31T23:53:14.933,user1567194,2012-08-01T04:07:34.423
1295611,1567195.00,2012-07-31T23:53:26.197,SummerDew,2012-07-31T23:53:26.197
1295612,1567196.00,2012-07-31T23:53:40.033,Garrett Miller,2012-07-31T23:53:40.033
1295613,1567197.00,2012-07-31T23:54:27.930,Konnah Sharp,2012-07-31T23:54:27.930
1295614,1567198.00,2012-07-31T23:56:27.913,jibreel,2012-08-01T02:10:31.753
1295615,1567199.00,2012-07-31T23:56:39.270,Eduardo Yayo Mancilla Rodrigue,2012-07-31T23:56:39.270
1295616,1567200.00,2012-07-31T23:57:57.770,user1567200,2012-08-01T00:55:12.953
1295617,1567201.00,2012-07-31T23:58:49.450,Joe Griffin,2012-08-01T02:47:51.793
1295618,1567202.00,2012-07-31T23:59:25.083,Chris Wendt,2012-07-31T23:59:25.083
1295619,1567203.00,2012-07-31T23:59:52.773,Sarah Rose,2012-07-31T23:59:52.773

In [73]:
m_posts1 = posts[['Id','PostTypeId','CreationDate', 'OwnerUserId', 'LastEditorUserId','LastEditorDisplayName','LastEditDate']]

In [74]:
m_posts1

,Id,PostTypeId,CreationDate,OwnerUserId,LastEditorUserId,LastEditorDisplayName,LastEditDate
0,4,1,2008-07-31T21:42:52.667,8.00,1039608.00,Rich B,2012-05-04T08:55:46.677
1,6,1,2008-07-31T22:08:08.620,9.00,483731.00,Rich B,2012-02-26T13:47:20.073
2,7,2,2008-07-31T22:17:57.883,9.00,1.00,NaN,2010-02-02T19:38:14.493
3,8,1,2008-07-31T23:33:19.290,9.00,1039608.00,Rich B,2012-05-04T08:56:59.720
4,9,1,2008-07-31T23:40:59.743,1.00,861565.00,Rich B,2012-07-30T12:23:37.267
5,11,1,2008-07-31T23:55:37.967,1.00,1039608.00,Rich B,2012-05-04T08:57:39.843
6,12,2,2008-07-31T23:56:41.303,1.00,159270.00,GateKiller,2011-08-08T01:14:13.453
7,13,1,2008-08-01T00:42:38.903,9.00,1039608.00,Rich B,2012-05-04T08:58:19.547
8,14,1,2008-08-01T00:59:11.177,11.00,1039608.00,Rich B,2012-05-04T09:00:49.407
9,16,1,2008-08-01T04:59:33.643,2.00,1039608.00,Chris Fournier,2012-05-04T09:01:26.053
10,17,1,2008-08-01T05:09:55.993,2.00,546051.00,NaN,2011-10-21T21:29:17.160
11,18,2,2008-08-01T05:12:44.193,nan,6068.00,Jeff Atwood,2009-05-28T11:40:35.210
12,19,1,2008-08-01T05:21:22.257,13.00,13.00,Chris Jester-Young,2009-08-07T11:45:50.333
13,20,2,2008-08-01T07:25:22.443,5.00,nan,NaN,NaN
14,21,2,2008-08-01T08:57:27.280,13.00,13.00,Chris Jester-Young,2008-08-01T12:35:11.707
15,22,2,2008-08-01T12:07:19.500,17.00,17.00,Nick,2008-08-01T15:26:37.087
16,23,1,2008-08-01T12:09:41.947,48.00,367456.00,Mat Scales,2012-06-02T17:39:22.287
17,24,1,2008-08-01T12:12:19.350,22.00,63550.00,Jim Anderson,2012-05-25T20:50:23.130
18,25,1,2008-08-01T12:13:50.207,23.00,13531.00,NaN,2012-05-25T21:48:23.387
19,26,2,2008-08-01T12:16:22.167,48.00,48.00,Geoff Dalgas,2012-06-11T15:07:58.813
20,27,2,2008-08-01T12:17:19.357,17.00,17.00,Nick Berardi,2008-08-01T13:16:49.127
21,29,2,2008-08-01T12:19:17.417,19.00,nan,NaN,NaN
22,30,2,2008-08-01T12:22:40.797,13.00,nan,NaN,NaN
23,31,2,2008-08-01T12:22:51.593,nan,842480.00,NaN,2012-06-04T23:35:58.177
24,33,2,2008-08-01T12:26:39.773,13.00,13.00,NaN,2009-10-14T02:09:03.030
25,34,1,2008-08-01T12:30:57.630,nan,63550.00,NaN,2012-05-25T21:06:10.223
26,36,1,2008-08-01T12:35:56.917,32.00,419.00,Mark Harrison,2012-05-25T23:43:47.697
27,37,2,2008-08-01T12:36:00.957,23.00,23.00,Jax,2008-08-01T12:42:32.113
28,39,1,2008-08-01T12:43:11.503,33.00,63550.00,Jim Anderson,2012-05-25T20:55:43.157
29,41,2,2008-08-01T12:49:12.413,34.00,31671.00,NaN,2010-02-20T23:26:24.063
...,...,...,...,...,...,...,...
10338331,11750729,1,2012-07-31T23:55:24.683,731901.00,731901.00,NaN,2012-08-01T00:24:12.690
10338332,11750730,2,2012-07-31T23:55:26.770,1330275.00,nan,NaN,NaN
10338333,11750731,2,2012-07-31T23:55:29.207,409167.00,nan,NaN,NaN
10338334,11750732,1,2012-07-31T23:55:30.050,1318705.00,1318705.00,NaN,2012-08-01T00:02:53.887
10338335,11750733,1,2012-07-31T23:55:35.260,770038.00,nan,NaN,NaN
10338336,11750735,2,2012-07-31T23:55:48.533,984335.00,nan,NaN,NaN
10338337,11750736,2,2012-07-31T23:55:52.110,1398245.00,nan,NaN,NaN
10338338,11750738,1,2012-07-31T23:56:18.193,900747.00,nan,NaN,NaN
10338339,11750739,1,2012-07-31T23:56:24.543,1261355.00,nan,NaN,NaN
10338340,11750740,1,2012-07-31T23:56:54.217,841626.00,nan,NaN,NaN
10338341,11750741,1,2012-07-31T23:56:58.567,1472467.00,nan,NaN,NaN
10338342,11750742,1,2012-07-31T23:57:18.710,1567186.00,nan,NaN,NaN
10338343,11750743,1,2012-07-31T23:57:30.063,539273.00,nan,NaN,NaN
10338344,11750744,2,2012-07-31T23:57:56.600,491094.00,nan,NaN,NaN
10338345,11750745,2,2012-07-31T23:58:02.943,1504644.00,nan,NaN,NaN
10338346,11750746,1,2012-07-31T23:58:04.573,595437.00,nan,NaN,NaN
10338347,11750747,1,2012-07-31T23:58:07.160,1567194.00,1567194.00,NaN,2012-08-01T02:11:19.287
10338348,11750748,2,2012-07-31T23:58:11.440,775184.00,nan,NaN,NaN
10338349,11750749,2,2012-07-31T23:58:50.220,686733.00,nan,NaN,NaN
10338350,11750750,2,2012-07-31T23:58:56.213,517781.00,nan,NaN,NaN
10338351,11750751,2,2012-07-31T23:59:03.527,898266.00,898266.00,NaN,2012-08-01T00:13:55.030
10338352,11750752,2,2012-07-31T23:59:12.620,1478722.00,nan,NaN,NaN
10338353,11750753,2,2012-07-31T23:59:25.083,1567202.00,nan,NaN,NaN
10338354,11750755,1,2012-07-31T23:59:26.430,173630.00,nan,NaN,NaN
10338355,11750756,2,2012-07-31T23:59:29.873,582.00,nan,NaN,NaN
10338356,11750757,2,2012-07-31T23:59:38.263,141172.00,nan,NaN,NaN
10338357,11750758,2,2012-07-31T23:59:41.953,729881.00,nan,NaN,NaN
10338358,11750759,1,2012-07-31T23:59:41.970,1492051.00,nan,NaN,NaN
10338359,11750760,2,2012-07-31T23:59:49.843,898258.00,nan,NaN,NaN
10338360,11750761,1,2012-07-31T23:59:57.380,1513192.00,nan,NaN,NaN

In [75]:
merged_users_posts_LastEditorUserId = pd.merge(left=m_users1,right=m_posts1,how='inner', left_on='id', right_on='LastEditorUserId')
merged_users_posts_LastEditorUserId.shape

(3137078, 11)

In [76]:
merged_users_posts_LastEditorUserId

,id,creationDate,name,lastAccess,Id,PostTypeId,CreationDate,OwnerUserId,LastEditorUserId,LastEditorDisplayName,LastEditDate
0,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,292,2,2008-08-02T00:47:48.797,91.00,-1.00,NaN,2012-01-05T11:50:33.263
1,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,382,1,2008-08-02T08:58:27.540,122.00,-1.00,NaN,2008-09-09T21:13:49.330
2,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,610,1,2008-08-03T03:01:47.840,145.00,-1.00,NaN,2008-09-10T18:13:53.390
3,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,742,1,2008-08-03T15:55:28.633,189.00,-1.00,NaN,2008-09-11T20:14:02.330
4,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,1241,1,2008-08-04T13:52:25.090,194.00,-1.00,NaN,2008-09-14T15:14:35.597
5,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,1313,1,2008-08-04T15:08:13.143,65.00,-1.00,NaN,2008-09-10T00:13:41.210
6,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,1323,1,2008-08-04T15:14:47.517,65.00,-1.00,NaN,2008-09-10T00:13:45.560
7,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,1644,1,2008-08-04T22:17:08.503,91.00,-1.00,Michael Stum,2011-01-20T07:33:24.433
8,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,1908,1,2008-08-05T04:55:28.683,79.00,-1.00,NaN,2008-09-10T05:13:45.747
9,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,2131,1,2008-08-05T11:58:47.503,227.00,-1.00,NaN,2008-09-09T21:13:42.810
10,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,2540,1,2008-08-05T16:30:37.377,136.00,-1.00,NaN,2008-09-10T18:13:55.543
11,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,2735,2,2008-08-05T19:31:46.730,444.00,-1.00,NaN,2011-05-03T07:32:51.730
12,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,2896,1,2008-08-05T21:41:18.483,271.00,-1.00,NaN,2008-09-10T02:13:41.997
13,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,2942,1,2008-08-05T22:40:25.073,100.00,-1.00,NaN,2008-09-10T00:13:46.137
14,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,2988,1,2008-08-06T00:56:05.937,861.00,-1.00,NaN,2008-09-09T21:13:48.987
15,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3112,1,2008-08-06T05:56:00.933,219.00,-1.00,NaN,2008-09-09T23:13:45.940
16,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3164,1,2008-08-06T08:34:13.983,192.00,-1.00,NaN,2008-09-10T18:13:54.340
17,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3231,1,2008-08-06T09:51:06.153,381.00,-1.00,NaN,2008-09-10T18:13:56.557
18,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3255,1,2008-08-06T10:18:16.067,46.00,-1.00,Lance Roberts,2011-02-24T07:56:01.937
19,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3281,1,2008-08-06T11:02:20.597,484.00,-1.00,NaN,2008-09-10T05:13:44.217
20,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3776,2,2008-08-06T18:02:31.480,82.00,-1.00,Duncan,2011-12-27T15:06:10.133
21,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,3868,1,2008-08-06T19:08:19.290,163.00,-1.00,NaN,2008-09-09T21:13:53.060
22,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,4664,1,2008-08-07T12:53:19.217,nan,-1.00,NaN,2008-09-09T23:13:49.653
23,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,4913,1,2008-08-07T16:21:59.280,626.00,-1.00,NaN,2008-09-09T22:13:50.263
24,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,4941,1,2008-08-07T16:41:58.180,288.00,-1.00,NaN,2008-09-09T23:13:51.383
25,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,5027,1,2008-08-07T17:38:09.143,681.00,-1.00,NaN,2008-09-09T22:13:45.303
26,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,5136,1,2008-08-07T18:47:58.487,676.00,-1.00,NaN,2008-09-10T18:13:55.387
27,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,5425,1,2008-08-07T22:30:25.357,219.00,-1.00,NaN,2008-09-09T21:13:45.073
28,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,5618,1,2008-08-08T03:38:38.697,668.00,-1.00,NaN,2008-09-10T18:13:52.080
29,-1.00,2008-07-31T00:00:00.000,Community,2008-08-26T00:16:53.810,5833,1,2008-08-08T12:25:27.253,287.00,-1.00,NaN,2008-09-11T02:13:57.277
...,...,...,...,...,...,...,...,...,...,...,...
3137048,1566626.00,2012-07-31T18:31:19.567,user1566626,2012-07-31T21:29:34.880,11746891,1,2012-07-31T18:45:31.393,1566626.00,1566626.00,NaN,2012-07-31T19:57:00.620
3137049,1566628.00,2012-07-31T18:32:48.807,Usko,2012-07-31T19:44:53.010,11746883,1,2012-07-31T18:44:54.507,1566628.00,1566628.00,NaN,2012-07-31T19:08:28.400
3137050,1566629.00,2012-07-31T18:32:59.097,user1566629,2012-07-31T23:22:33.373,11746811,1,2012-07-31T18:40:22.573,1566629.00,1566629.00,NaN,2012-07-31T20:57:45.790
3137051,1566638.00,2012-07-31T18:34:21.813,user1566638,2012-07-31T21:44:46.290,11746791,1,2012-07-31T18:38:57.973,1566638.00,1566638.00,NaN,2012-07-31T21:46:23.650
3137052,1566639.00,2012-07-31T18:34:25.350,user1566639,2012-07-31T20:45:40.503,11746950,1,2012-07-31T18:48:57.037,1566639.00,1566639.00,NaN,2012-07-31T19:06:41.650
3137053,1566654.00,2012-07-31T18:39:52.000,Tucker Watts,2012-07-31T20:14:12.730,11746973,1,2012-07-31T18:50:31.460,1566654.00,1566654.00,NaN,2012-07-31T19:18:57.067
3137054,1566682.00,2012-07-31T18:51:50.493,Bill,2012-07-31T21:34:40.553,11747252,2,2012-07-31T19:09:39.157,1566682.00,1566682.00,NaN,2012-07-31T19:40:18.570
3137055,1566732.00,2012-07-31T19:15:09.480,SimonH,2012-08-01T05:00:17.410,11747646,2,2012-07-31T19:33:24.077,1566732.00,1566732.00,NaN,2012-07-31T19:38:24.260
3137056,1566733.00,2012-07-31T19:15:58.390,user142852,2012-08-01T02:56:16.503,11747439,1,2012-07-31T19:20:42.397,1566733.00,1566733.00,NaN,2012-08-01T02:20:05.880
3137057,1566783.00,2012-07-31T19:37:25.950,user1566783,2012-07-31T21:52:44.367,11747852,1,2012-07-31T19:47:23.943,1566783.00,1566783.00,NaN,2012-07-31T21:46:38.503
3137058,1566809.00,2012-07-31T19:51:24.190,Leward,2012-07-31T20:49:31.737,10177163,2,2012-04-16T15:33:34.767,1336670.00,1566809.00,NaN,2012-07-31T20:08:49.820
3137059,1566828.00,2012-07-31T20:05:13.900,tommat,2012-07-31T23:48:37.240,11748621,1,2012-07-31T20:37:45.733,1566828.00,1566828.00,NaN,2012-07-31T20:46:31.290
3137060,1566849.00,2012-07-31T20:15:34.073,PyNew,2012-07-31T20:15:34.073,11748404,1,2012-07-31T20:23:43.530,1566849.00,1566849.00,NaN,2012-07-31T20:29:08.553
3137061,1566857.00,2012-07-31T20:20:05.877,roaro,2012-07-31T21:49:32.200,11748535,1,2012-07-31T20:32:33.420,1566857.00,1566857.00,NaN,2012-07-31T20:55:51.350
3137062,1566871.00,2012-07-31T20:25:46.840,FinBoWa,2012-07-31T21:46:28.923,11748537,2,2012-07-31T20:32:42.517,1566871.00,1566871.00,NaN,2012-07-31T21:00:15.963
3137063,1566878.00,2010-10-10T01:03:21.427,Cristian Gruita,2012-08-01T02:07:25.377,5082735,1,2011-02-22T19:14:32.783,1566878.00,1566878.00,NaN,2011-02-22T21:20:16.750
3137064,1566957.00,2012-07-31T21:08:17.573,user1566957,2012-08-01T04:02:02.447,11749098,1,2012-07-31T21:14:02.453,1566957.00,1566957.00,NaN,2012-07-31T22:06:32.897
3137065,1566968.00,2012-07-31T21:14:25.963,user1566968,2012-07-31T23:10:50.383,11749269,1,2012-07-31T21:27:56.643,1566968.00,1566968.00,NaN,2012-07-31T22:21:52.343
3137066,1566969.00,2012-07-31T21:14:36.957,Dario Gomez,2012-08-01T04:45:42.803,11749166,1,2012-07-31T21:19:01.413,1566969.00,1566969.00,NaN,2012-08-01T03:57:55.547
3137067,1566985.00,2012-07-31T21:22:36.513,thomas rampley,2012-07-31T21:57:43.753,11749245,1,2012-07-31T21:26:36.180,1566985.00,1566985.00,NaN,2012-07-31T21:32:33.570
3137068,1567010.00,2012-07-31T21:34:52.393,Biggest,2012-07-31T22:24:04.460,11749742,1,2012-07-31T22:09:05.170,1567010.00,1567010.00,NaN,2012-07-31T22:14:18.833
3137069,1567014.00,2012-07-31T21:36:33.927,user1567014,2012-07-31T22:14:17.947,11749464,1,2012-07-31T21:45:19.200,1567014.00,1567014.00,NaN,2012-07-31T21:52:46.253
3137070,1567063.00,2012-07-31T22:13:15.667,Wai Chin,2012-07-31T22:44:03.680,11749983,1,2012-07-31T22:31:18.870,1567063.00,1567063.00,NaN,2012-07-31T22:42:28.593
3137071,1567088.00,2012-07-31T22:31:23.807,Keith Miller,2012-07-31T23:58:33.200,11750261,1,2012-07-31T23:00:56.137,1567088.00,1567088.00,NaN,2012-07-31T23:06:02.200
3137072,1567123.00,2012-07-31T22:56:42.513,Eric Philmore,2012-08-01T04:18:03.683,11750312,1,2012-07-31T23:06:09.733,1567123.00,1567123.00,NaN,2012-07-31T23:13:15.250
3137073,1567142.00,2012-07-31T23:11:26.800,knockoutrose,2012-08-01T04:45:03.227,11750357,2,2012-07-31T23:11:26.800,1567142.00,1567142.00,NaN,2012-07-31T23:21:35.713
3137074,1567170.00,2012-07-31T23:33:50.723,Hellius666,2012-07-31T23:33:50.723,11750566,2,2012-07-31T23:33:50.723,1567170.00,1567170.00,NaN,2012-07-31T23:39:34.870
3137075,1567179.00,2012-07-31T23:40:09.717,Blake took,2012-08-01T00:36:09.313,11750719,1,2012-07-31T23:54:29.380,1567179.00,1567179.00,NaN,2012-08-01T00:03:40.397
3137076,1567187.00,2012-07-31T23:49:08.307,Troy,2012-08-01T03:57:45.660,11750685,2,2012-07-31T23:49:08.307,1567187.00,1567187.00,NaN,2012-08-01T00:13:03.960
3137077,1567194.00,2012-07-31T23:53:14.933,user1567194,2012-08-01T04:07:34.423,11750747,1,2012-07-31T23:58:07.160,1567194.00,1567194.00,NaN,2012-08-01T02:11:19.287

In [77]:
merged_users_posts_LastEditorUserId.to_csv("merged_users_posts_LastEditorUserId.csv")

In [78]:
e_users_posts=merged_users_posts_LastEditorUserId.groupby('id').size().reset_index(name='noPostEdits')
e_users_posts

               id  noPostEdits
0           -1.00         8119
1            1.00         1112
2            2.00           25
3            3.00          101
4            4.00          123
5            5.00          105
6            8.00            1
7            9.00            4
8           13.00          496
9           17.00          142
10          19.00            1
11          20.00           62
12          22.00           20
13          23.00            5
14          24.00            2
15          25.00           25
16          26.00           52
17          27.00            5
18          29.00          252
19          30.00           31
20          33.00          139
21          34.00            3
22          35.00           74
23          36.00           18
24          37.00            8
25          38.00           22
26          39.00           27
27          40.00           17
28          41.00            1
29          42.00           90
...           ...          ...
277893 1566626.00            1
277894 1566628.00            1
277895 1566629.00            1
277896 1566638.00            1
277897 1566639.00            1
277898 1566654.00            1
277899 1566682.00            1
277900 1566732.00            1
277901 1566733.00            1
277902 1566783.00            1
277903 1566809.00            1
277904 1566828.00            1
277905 1566849.00            1
277906 1566857.00            1
277907 1566871.00            1
277908 1566878.00            1
277909 1566957.00            1
277910 1566968.00            1
277911 1566969.00            1
277912 1566985.00            1
277913 1567010.00            1
277914 1567014.00            1
277915 1567063.00            1
277916 1567088.00            1
277917 1567123.00            1
277918 1567142.00            1
277919 1567170.00            1
277920 1567179.00            1
277921 1567187.00            1
277922 1567194.00            1

[277923 rows x 2 columns]

In [79]:
merged_qap_edits = pd.merge(left=qap,right=e_users_posts,how='outer', left_on='id', right_on='id')
#merged_qap_edits = merged_qap_edits.fillna(0)
merged_qap_edits.shape

(838779, 9)

In [80]:

merged_qap_edits

,id,noPosts,noQues,noAns,sum,z-score_denominator,z-score_numerator,z-score,noPostEdits
0,-1.00,26355.00,0.00,0.00,0.00,0.00,0.00,nan,8119.00
1,1.00,158.00,15.00,143.00,158.00,12.57,128.00,10.18,1112.00
2,2.00,12.00,7.00,5.00,12.00,3.46,-2.00,-0.58,25.00
3,3.00,38.00,6.00,32.00,38.00,6.16,26.00,4.22,101.00
4,4.00,178.00,11.00,167.00,178.00,13.34,156.00,11.69,123.00
5,5.00,343.00,45.00,298.00,343.00,18.52,253.00,13.66,105.00
6,8.00,1.00,1.00,0.00,1.00,1.00,-1.00,-1.00,1.00
7,9.00,58.00,18.00,40.00,58.00,7.62,22.00,2.89,4.00
8,11.00,1.00,1.00,0.00,1.00,1.00,-1.00,-1.00,nan
9,13.00,1288.00,8.00,1279.00,1287.00,35.87,1271.00,35.43,496.00
10,16.00,10.00,1.00,9.00,10.00,3.16,8.00,2.53,nan
11,17.00,609.00,29.00,580.00,609.00,24.68,551.00,22.33,142.00
12,19.00,14.00,2.00,12.00,14.00,3.74,10.00,2.67,1.00
13,20.00,112.00,21.00,91.00,112.00,10.58,70.00,6.61,62.00
14,22.00,189.00,16.00,173.00,189.00,13.75,157.00,11.42,20.00
15,23.00,10.00,6.00,4.00,10.00,3.16,-2.00,-0.63,5.00
16,24.00,14.00,1.00,13.00,14.00,3.74,12.00,3.21,2.00
17,25.00,83.00,34.00,49.00,83.00,9.11,15.00,1.65,25.00
18,26.00,350.00,118.00,232.00,350.00,18.71,114.00,6.09,52.00
19,27.00,13.00,4.00,9.00,13.00,3.61,5.00,1.39,5.00
20,29.00,491.00,57.00,434.00,491.00,22.16,377.00,17.01,252.00
21,30.00,82.00,10.00,72.00,82.00,9.06,62.00,6.85,31.00
22,32.00,5.00,2.00,3.00,5.00,2.24,1.00,0.45,nan
23,33.00,116.00,35.00,81.00,116.00,10.77,46.00,4.27,139.00
24,34.00,70.00,5.00,65.00,70.00,8.37,60.00,7.17,3.00
25,35.00,219.00,20.00,199.00,219.00,14.80,179.00,12.10,74.00
26,36.00,113.00,6.00,107.00,113.00,10.63,101.00,9.50,18.00
27,37.00,72.00,24.00,48.00,72.00,8.49,24.00,2.83,8.00
28,38.00,141.00,101.00,40.00,141.00,11.87,-61.00,-5.14,22.00
29,39.00,70.00,16.00,54.00,70.00,8.37,38.00,4.54,27.00
...,...,...,...,...,...,...,...,...,...
838749,1525562.00,nan,nan,nan,nan,nan,nan,nan,1.00
838750,1525722.00,nan,nan,nan,nan,nan,nan,nan,1.00
838751,1526667.00,nan,nan,nan,nan,nan,nan,nan,1.00
838752,1527249.00,nan,nan,nan,nan,nan,nan,nan,1.00
838753,1531507.00,nan,nan,nan,nan,nan,nan,nan,1.00
838754,1531638.00,nan,nan,nan,nan,nan,nan,nan,1.00
838755,1533364.00,nan,nan,nan,nan,nan,nan,nan,1.00
838756,1534514.00,nan,nan,nan,nan,nan,nan,nan,1.00
838757,1534826.00,nan,nan,nan,nan,nan,nan,nan,1.00
838758,1535535.00,nan,nan,nan,nan,nan,nan,nan,1.00
838759,1536125.00,nan,nan,nan,nan,nan,nan,nan,1.00
838760,1539223.00,nan,nan,nan,nan,nan,nan,nan,1.00
838761,1539300.00,nan,nan,nan,nan,nan,nan,nan,1.00
838762,1539574.00,nan,nan,nan,nan,nan,nan,nan,1.00
838763,1540223.00,nan,nan,nan,nan,nan,nan,nan,1.00
838764,1540356.00,nan,nan,nan,nan,nan,nan,nan,1.00
838765,1540369.00,nan,nan,nan,nan,nan,nan,nan,1.00
838766,1541024.00,nan,nan,nan,nan,nan,nan,nan,1.00
838767,1541586.00,nan,nan,nan,nan,nan,nan,nan,1.00
838768,1545880.00,nan,nan,nan,nan,nan,nan,nan,1.00
838769,1546364.00,nan,nan,nan,nan,nan,nan,nan,1.00
838770,1547603.00,nan,nan,nan,nan,nan,nan,nan,1.00
838771,1549330.00,nan,nan,nan,nan,nan,nan,nan,1.00
838772,1553227.00,nan,nan,nan,nan,nan,nan,nan,1.00
838773,1553377.00,nan,nan,nan,nan,nan,nan,nan,1.00
838774,1553877.00,nan,nan,nan,nan,nan,nan,nan,1.00
838775,1558212.00,nan,nan,nan,nan,nan,nan,nan,1.00
838776,1562048.00,nan,nan,nan,nan,nan,nan,nan,2.00
838777,1564304.00,nan,nan,nan,nan,nan,nan,nan,1.00
838778,1566809.00,nan,nan,nan,nan,nan,nan,nan,1.00

In [81]:
del merged_qap_edits['sum']

In [82]:
del merged_qap_edits['z-score_denominator']
del merged_qap_edits['z-score_numerator']
merged_qap_edits

               id  noPosts  noQues   noAns  z-score  noPostEdits
0           -1.00 26355.00    0.00    0.00      nan      8119.00
1            1.00   158.00   15.00  143.00    10.18      1112.00
2            2.00    12.00    7.00    5.00    -0.58        25.00
3            3.00    38.00    6.00   32.00     4.22       101.00
4            4.00   178.00   11.00  167.00    11.69       123.00
5            5.00   343.00   45.00  298.00    13.66       105.00
6            8.00     1.00    1.00    0.00    -1.00         1.00
7            9.00    58.00   18.00   40.00     2.89         4.00
8           11.00     1.00    1.00    0.00    -1.00          nan
9           13.00  1288.00    8.00 1279.00    35.43       496.00
10          16.00    10.00    1.00    9.00     2.53          nan
11          17.00   609.00   29.00  580.00    22.33       142.00
12          19.00    14.00    2.00   12.00     2.67         1.00
13          20.00   112.00   21.00   91.00     6.61        62.00
14          22.00   189.00   16.00  173.00    11.42        20.00
15          23.00    10.00    6.00    4.00    -0.63         5.00
16          24.00    14.00    1.00   13.00     3.21         2.00
17          25.00    83.00   34.00   49.00     1.65        25.00
18          26.00   350.00  118.00  232.00     6.09        52.00
19          27.00    13.00    4.00    9.00     1.39         5.00
20          29.00   491.00   57.00  434.00    17.01       252.00
21          30.00    82.00   10.00   72.00     6.85        31.00
22          32.00     5.00    2.00    3.00     0.45          nan
23          33.00   116.00   35.00   81.00     4.27       139.00
24          34.00    70.00    5.00   65.00     7.17         3.00
25          35.00   219.00   20.00  199.00    12.10        74.00
26          36.00   113.00    6.00  107.00     9.50        18.00
27          37.00    72.00   24.00   48.00     2.83         8.00
28          38.00   141.00  101.00   40.00    -5.14        22.00
29          39.00    70.00   16.00   54.00     4.54        27.00
...           ...      ...     ...     ...      ...          ...
838749 1525562.00      nan     nan     nan      nan         1.00
838750 1525722.00      nan     nan     nan      nan         1.00
838751 1526667.00      nan     nan     nan      nan         1.00
838752 1527249.00      nan     nan     nan      nan         1.00
838753 1531507.00      nan     nan     nan      nan         1.00
838754 1531638.00      nan     nan     nan      nan         1.00
838755 1533364.00      nan     nan     nan      nan         1.00
838756 1534514.00      nan     nan     nan      nan         1.00
838757 1534826.00      nan     nan     nan      nan         1.00
838758 1535535.00      nan     nan     nan      nan         1.00
838759 1536125.00      nan     nan     nan      nan         1.00
838760 1539223.00      nan     nan     nan      nan         1.00
838761 1539300.00      nan     nan     nan      nan         1.00
838762 1539574.00      nan     nan     nan      nan         1.00
838763 1540223.00      nan     nan     nan      nan         1.00
838764 1540356.00      nan     nan     nan      nan         1.00
838765 1540369.00      nan     nan     nan      nan         1.00
838766 1541024.00      nan     nan     nan      nan         1.00
838767 1541586.00      nan     nan     nan      nan         1.00
838768 1545880.00      nan     nan     nan      nan         1.00
838769 1546364.00      nan     nan     nan      nan         1.00
838770 1547603.00      nan     nan     nan      nan         1.00
838771 1549330.00      nan     nan     nan      nan         1.00
838772 1553227.00      nan     nan     nan      nan         1.00
838773 1553377.00      nan     nan     nan      nan         1.00
838774 1553877.00      nan     nan     nan      nan         1.00
838775 1558212.00      nan     nan     nan      nan         1.00
838776 1562048.00      nan     nan     nan      nan         2.00
838777 1564304.00      nan     nan     nan      nan         1.00
838778 1566809.00      nan     nan     nan      nan         1.00

[838779 rows x 6 columns]

## Number of Comments per user

In [83]:
comments

,Id,PostId,Score,Text,CreationDate,UserId
0,1,35314,9.00,not sure why this is getting downvoted -- it i...,2008-09-06T08:07:10.730,1.00
1,2,35314,5.00,"Yeah, I didn't believe it until I created a co...",2008-09-06T08:09:52.330,3.00
2,4,35195,nan,"I don't see an accepted answer now, I wonder h...",2008-09-06T08:42:16.980,380.00
3,8,12755,1.00,"It has to be said, pair programming is an exce...",2008-09-06T11:51:50.207,4642.00
4,9,47239,nan,"Jonathan: Wow! Thank you for all of that, you...",2008-09-06T12:26:30.060,4550.00
5,10,45651,2.00,It will help if you give some details of which...,2008-09-06T13:38:23.647,242.00
6,12,47428,2.00,One of the things that make a url user-friendl...,2008-09-06T13:51:47.843,4642.00
7,14,47481,nan,"I agree, both CodeRush and RefactorPro are vis...",2008-09-06T14:15:46.897,4642.00
8,15,47373,nan,Just wanted to mention that this is an excelle...,2008-09-06T14:30:40.217,2495.00
9,16,47497,nan,"Indeed, the only way to do this is get the ser...",2008-09-06T14:42:35.303,4642.00
10,18,47513,1.00,"This advice goes against the spirit of CSS, wh...",2008-09-06T15:02:40.980,2515.00
11,19,47466,1.00,It was bad when people used table for everythi...,2008-09-06T15:11:11.227,2515.00
12,20,1517,nan,"In the interests of tact, this is the kind of ...",2008-09-06T15:44:39.477,199.00
13,21,47527,1.00,The Digg link was the first one I came across ...,2008-09-06T16:00:35.147,658.00
14,22,47626,nan,concat infact doesn't do that. I've edited my...,2008-09-06T16:46:31.450,292.00
15,24,46538,nan,Why did I receive a downvote? The enhancement ...,2008-09-06T17:33:30.417,4213.00
16,25,47626,3.00,infact it does. Look a the first lines of your...,2008-09-06T17:37:35.757,4213.00
17,26,47464,nan,Yep. I have been thinking about that and will ...,2008-09-06T19:15:41.277,4585.00
18,27,47624,1.00,"""Currently + is implemented using StringBuffer...",2008-09-06T19:25:04.703,4064.00
19,28,47290,nan,"You should not have to say that you are ""not a...",2008-09-06T19:40:51.123,4064.00
20,30,36050,nan,I am assuming that this will work *only* if th...,2008-09-06T20:14:30.777,4906.00
21,31,47777,4.00,That code will fail as .Distinct() returns an ...,2008-09-06T20:21:55.457,3394.00
22,33,47513,nan,Bloats the HTML & complicates application of s...,2008-09-06T20:33:10.610,4906.00
23,34,47630,nan,"Yes, saw reCaptcha & looks promising but it's ...",2008-09-06T20:44:00.927,4906.00
24,37,27429,1.00,This is easily the best solution,2008-09-06T21:40:25.923,4213.00
25,38,47631,nan,"Nice article, cic - thanks for sharing!",2008-09-06T22:13:15.563,811.00
26,41,47885,2.00,I don't think that's the magic number he was r...,2008-09-06T22:32:45.003,4213.00
27,44,47885,1.00,"Maybe you should remove the ""file-format"" and ...",2008-09-06T22:42:13.623,1597.00
28,48,47895,nan,Can you be more specific on why eliminating ma...,2008-09-06T23:00:58.880,4213.00
29,49,47857,nan,When the hardware integration gets sufficientl...,2008-09-06T23:11:04.613,4071.00
...,...,...,...,...,...,...
13252424,15599013,11750602,nan,"@Ignacio: Yes, you are right in that. But it's...",2012-07-31T23:56:14.280,344949.00
13252425,15599014,11718081,nan,"You've got a terrible accept rate, Ehsan. Plea...",2012-07-31T23:56:26.337,589259.00
13252426,15599015,11750668,nan,"hmm, I never thought about that. I'll have to ...",2012-07-31T23:56:33.637,669886.00
13252427,15599016,11750632,nan,Well I think so yes. It's seems that this API ...,2012-07-31T23:56:38.787,295342.00
13252428,15599017,9035474,nan,Added a test case and a bounty.,2012-07-31T23:56:43.357,524555.00
13252429,15599019,11750399,nan,@ernie... Fraggin' *edit* feature!! **:-D** Th...,2012-07-31T23:57:05.947,289011.00
13252430,15599020,11750575,1.00,"In addition to @LarsTech answer, familarize yo...",2012-07-31T23:57:09.333,495455.00
13252431,15599021,11750583,nan,"@DanielFischer, is it will be helpful for key ...",2012-07-31T23:57:19.193,772399.00
13252432,15599023,11749200,nan,"Using Batarang, I was exactly right, there was...",2012-07-31T23:57:29.677,135786.00
13252433,15599024,11750563,nan,Well the other option is to check the user age...,2012-07-31T23:57:32.890,140877.00
13252434,15599025,11750368,2.00,@user1553248: `std::vector<std::vector<std::st...,2012-07-31T23:57:41.343,315052.00
13252435,15599026,11748741,2.00,I agree flash on the web is dying (especially ...,2012-07-31T23:57:54.107,1457439.00
13252436,15599027,11750399,nan,"@BorrajaX you see, and I'm a programmer... and...",2012-07-31T23:57:54.170,592212.00
13252437,15599028,11750168,nan,1GB might actually be the default as per http:...,2012-07-31T23:58:08.203,41655.00
13252438,15599029,11750729,1.00,Have you tried? There are some locations you c...,2012-07-31T23:58:08.613,210709.00
13252439,15599030,11750726,nan,Thank you thank you thank you! Just what I was...,2012-07-31T23:58:16.757,1166285.00
13252440,15599031,11750720,nan,"""makes it sound like you don't need to recurse...",2012-07-31T23:58:21.527,1455028.00
13252441,15599033,11749427,nan,Care to explain the downvote?,2012-07-31T23:58:38.687,788260.00
13252442,15599034,11740530,nan,Why's that? The idea would be that a client re...,2012-07-31T23:58:45.243,364.00
13252443,15599035,11750506,nan,I think I see the problem. Try adding `Rewrite...,2012-07-31T23:58:57.710,1563759.00
13252444,15599036,11750726,1.00,"@iight Please check it again, I had a typo :)",2012-07-31T23:59:16.743,57611.00
13252445,15599037,11749849,nan,"@PhillipMills Nevermind, I'm stupid, that work...",2012-07-31T23:59:18.427,1454835.00
13252446,15599038,11749158,1.00,What version of Ember are you using? Can you p...,2012-07-31T23:59:20.173,365865.00
13252447,15599039,11750476,nan,this is THE perfect answer :),2012-07-31T23:59:22.483,592212.00
13252448,15599041,11749408,nan,what do you mean ? cause I lready specified it,2012-07-31T23:59:27.083,1083453.00
13252449,15599042,11750722,nan,Thank you!! Just what I was looking for.,2012-07-31T23:59:57.443,1166285.00
13252450,15599120,5719657,nan,comment out the DllCall - does it still throw ...,2011-04-19T16:39:17.257,9345.00
13252451,15599121,5719657,nan,"No, it's certainly something to do with the ca...",2011-04-20T08:18:39.010,301811.00
13252452,15599394,4746905,nan,I have found that the VisibleChanged event fir...,2011-07-13T19:51:50.070,21727.00
13252453,15599823,175312,nan,"I realize this was asked about a year ago, but...",2009-10-03T07:15:43.297,30301.00

In [84]:
comments.count()

Id              13252454
PostId          13252454
Score            1864845
Text            13252454
CreationDate    13252454
UserId          13167368
dtype: int64

In [85]:
13252454 - 13167368 #number of comments for which userid not given

85086

In [86]:
merged_user_comments = pd.merge(left=m_users1,right=comments,how='inner', left_on='id', right_on='UserId')
merged_user_comments.shape

(13167368, 10)

In [87]:
merged_user_comments

,id,creationDate,name,lastAccess,Id,PostId,Score,Text,CreationDate,UserId
0,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,1,35314,9.00,not sure why this is getting downvoted -- it i...,2008-09-06T08:07:10.730,1.00
1,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,711,50366,4.00,"""Oll Korrect"" is part of the historical deriva...",2008-09-09T08:22:44.863,1.00
2,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,720,50769,nan,we will eventually be able to merge accounts i...,2008-09-09T08:40:45.680,1.00
3,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,721,50907,nan,"I've met Ted, for the record, and I don't agre...",2008-09-09T08:42:04.660,1.00
4,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,723,50967,nan,myopenid.com is my recommendation -- they have...,2008-09-09T08:45:03.080,1.00
5,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4039,60423,3.00,"""use them all the time, unless you have a very...",2008-09-13T09:10:04.623,1.00
6,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4044,58912,14.00,that's hilarious! :),2008-09-13T09:20:15.753,1.00
7,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4124,59932,3.00,"this is a great response, but you should note ...",2008-09-13T14:55:39.863,1.00
8,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4369,34025,4.00,I do not think this is what the question was a...,2008-09-14T10:21:39.047,1.00
9,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4376,61134,3.00,I agree that log4net is a pretty heavy depende...,2008-09-14T10:48:31.883,1.00
10,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4731,61778,nan,"yeah, but the only problem with Markdown is th...",2008-09-15T04:42:29.693,1.00
11,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,4860,62160,13.00,an excellent point -- when *storing* dates in ...,2008-09-15T11:04:46.110,1.00
12,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,6440,68338,8.00,this is how we do it -- deletion is always a d...,2008-09-16T01:11:11.940,1.00
13,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,7175,70706,1.00,I was going to link this! I LOVE LOVE LOVE thi...,2008-09-16T11:01:35.080,1.00
14,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,7189,71271,nan,this is not a very good question -- can you re...,2008-09-16T11:14:24.317,1.00
15,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,9568,79709,nan,I recommend editing this post to include some ...,2008-09-17T03:52:45.397,1.00
16,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,10081,81099,nan,I agree.. why do you need to do it this way? I...,2008-09-17T08:43:58.740,1.00
17,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,10083,81080,1.00,note that you can also kill individual locks f...,2008-09-17T08:45:31.857,1.00
18,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,13865,92835,nan,multiple web servers or just one? that will ch...,2008-09-18T14:07:19.063,1.00
19,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,13950,93077,nan,from Fletch. nice.,2008-09-18T14:34:10.963,1.00
20,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,16901,100106,nan,"not my idea of ""fun"" even a little, but I thin...",2008-09-19T08:39:26.783,1.00
21,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,20623,17032,1.00,mmmmm... dooberries.. delicious!,2008-09-20T17:06:42.287,1.00
22,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,41035,144791,nan,"five different people, you mean",2008-09-28T14:52:55.747,1.00
23,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,41039,144791,nan,"also, you can fix it yourself by rolling back ...",2008-09-28T14:53:52.310,1.00
24,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,44371,140841,1.00,"""reformatting code that is messy creates unusa...",2008-09-29T23:03:27.947,1.00
25,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,44379,128816,1.00,2 offensive votes so far. And we wonder why mo...,2008-09-29T23:06:42.290,1.00
26,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,56847,166573,nan,"also known as ""guard clause""",2008-10-04T19:55:42.860,1.00
27,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,58991,174248,nan,"agree, is this a web app or not?",2008-10-06T13:26:32.253,1.00
28,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,61241,159582,1.00,"hey, cool -- thank you! I will try this!",2008-10-07T08:17:43.767,1.00
29,1.00,2008-07-31T14:22:31.287,Jeff Atwood,2012-08-01T04:46:57.447,61925,178587,4.00,except input.StartsWith() will perform about 1...,2008-10-07T14:04:14.610,1.00
...,...,...,...,...,...,...,...,...,...,...
13167338,1566991.00,2012-07-31T21:26:57.153,user1566991,2012-07-31T22:27:13.177,15597208,11749386,nan,"How do I, for example, combine two memory bloc...",2012-07-31T22:03:10.907,1566991.00
13167339,1567010.00,2012-07-31T21:34:52.393,Biggest,2012-07-31T22:24:04.460,15597617,11749810,nan,Yes! That did it! This doesn't really reflect ...,2012-07-31T22:25:50.090,1567010.00
13167340,1567014.00,2012-07-31T21:36:33.927,user1567014,2012-07-31T22:14:17.947,15597039,11749464,nan,"No errors in Firebug or Chrome show in the JS,...",2012-07-31T21:53:49.907,1567014.00
13167341,1567014.00,2012-07-31T21:36:33.927,user1567014,2012-07-31T22:14:17.947,15597095,11749567,nan,Ok so does that mean that it's disabled becaus...,2012-07-31T21:56:25.100,1567014.00
13167342,1567014.00,2012-07-31T21:36:33.927,user1567014,2012-07-31T22:14:17.947,15597108,11749567,nan,I mean is there another type of script or anot...,2012-07-31T21:57:08.033,1567014.00
13167343,1567014.00,2012-07-31T21:36:33.927,user1567014,2012-07-31T22:14:17.947,15597143,11749567,nan,"Ah I see it, got it. Thanks!",2012-07-31T21:58:50.470,1567014.00
13167344,1567014.00,2012-07-31T21:36:33.927,user1567014,2012-07-31T22:14:17.947,15597407,11749590,nan,"Thanks for the suggestion, I will look into th...",2012-07-31T22:15:01.363,1567014.00
13167345,1567017.00,2012-07-31T21:39:07.957,Valle,2012-07-31T23:48:00.127,15597691,11749941,nan,Thank you! After this change it was the first ...,2012-07-31T22:29:43.753,1567017.00
13167346,1567017.00,2012-07-31T21:39:07.957,Valle,2012-07-31T23:48:00.127,15597812,11749941,nan,"EDIT: I changed the code to\r\n $("".content...",2012-07-31T22:36:21.537,1567017.00
13167347,1567017.00,2012-07-31T21:39:07.957,Valle,2012-07-31T23:48:00.127,15597880,11749686,nan,"Sorry, that doesn't do the trick. But thank yo...",2012-07-31T22:40:24.953,1567017.00
13167348,1567017.00,2012-07-31T21:39:07.957,Valle,2012-07-31T23:48:00.127,15598733,11749941,nan,I don't know what would be the correct thing i...,2012-07-31T23:33:05.510,1567017.00
13167349,1567027.00,2012-07-31T21:45:45.370,Jwlyan,2012-07-31T21:45:45.370,15597245,10891271,nan,I think this link http://www.icapps.be/prevent...,2012-07-31T21:45:45.370,1567027.00
13167350,1567035.00,2012-07-31T21:50:24.507,Michael Bonenfant,2012-08-01T00:49:14.150,15598774,11749783,nan,Great solution! I was headed down the way of u...,2012-07-31T23:36:11.843,1567035.00
13167351,1567042.00,2012-07-31T21:56:39.700,user1567042,2012-07-31T22:48:54.157,15598178,11749886,nan,but the thing is a lot of Android malicious ap...,2012-07-31T22:55:35.267,1567042.00
13167352,1567046.00,2012-07-31T21:59:58.937,Chris X,2012-07-31T23:52:33.877,15598962,11749638,nan,"Though on some terminals, weirdness happens. :...",2012-07-31T23:51:36.917,1567046.00
13167353,1567054.00,2012-07-31T22:03:33.943,LilleCarl,2012-07-31T22:49:40.630,15597454,11749765,nan,"Visual Studio 2008*, it was a typo. And the nu...",2012-07-31T22:17:28.117,1567054.00
13167354,1567054.00,2012-07-31T22:03:33.943,LilleCarl,2012-07-31T22:49:40.630,15597543,11749765,nan,"Partlyl solver problem, i missunderstood the c...",2012-07-31T22:22:11.720,1567054.00
13167355,1567054.00,2012-07-31T22:03:33.943,LilleCarl,2012-07-31T22:49:40.630,15597661,11749765,nan,victimHealth = std::accumulate(m_Damagers.begi...,2012-07-31T22:27:47.893,1567054.00
13167356,1567054.00,2012-07-31T22:03:33.943,LilleCarl,2012-07-31T22:49:40.630,15598061,11749765,nan,Not sure if this is properly done. But im now ...,2012-07-31T22:48:45.763,1567054.00
13167357,1567055.00,2012-07-31T22:05:32.380,Mamick,2012-08-01T00:25:11.317,15597860,11749931,nan,I'm sorry if I wasn't clear enough; I didn't w...,2012-07-31T22:39:37.497,1567055.00
13167358,1567055.00,2012-07-31T22:05:32.380,Mamick,2012-08-01T00:25:11.317,15598150,11750103,nan,"Thanks, this is great! One more question: when...",2012-07-31T22:53:43.560,1567055.00
13167359,1567060.00,2012-07-31T22:09:06.697,user1567060,2012-07-31T22:59:14.313,15597610,11749929,nan,Thank you VERY much. I greatly appreciate it.,2012-07-31T22:25:21.550,1567060.00
13167360,1567063.00,2012-07-31T22:13:15.667,Wai Chin,2012-07-31T22:44:03.680,15597777,11749995,nan,lol thanks it's working. Thank you very much!,2012-07-31T22:34:21.197,1567063.00
13167361,1567078.00,2012-07-31T22:23:27.223,Daniel Troyano,2012-08-01T03:37:34.267,15598711,11750112,nan,I know I was using the same Book it's because ...,2012-07-31T23:31:40.920,1567078.00
13167362,1567078.00,2012-07-31T22:23:27.223,Daniel Troyano,2012-08-01T03:37:34.267,15598743,11750082,nan,"This is exactly what I was looking for, I don'...",2012-07-31T23:33:37.440,1567078.00
13167363,1567088.00,2012-07-31T22:31:23.807,Keith Miller,2012-07-31T23:58:33.200,15597984,11750070,nan,No I didn't down vote it I'm sorry this is my ...,2012-07-31T22:45:00.427,1567088.00
13167364,1567088.00,2012-07-31T22:31:23.807,Keith Miller,2012-07-31T23:58:33.200,15598748,11750261,nan,By efficient I mean is there anyway I should b...,2012-07-31T23:33:46.640,1567088.00
13167365,1567094.00,2012-07-31T22:34:53.473,Ryan Bauer,2012-08-01T02:02:55.210,15598755,11750506,nan,thank you for your prompt response. are you sa...,2012-07-31T23:34:32.227,1567094.00
13167366,1567094.00,2012-07-31T22:34:53.473,Ryan Bauer,2012-08-01T02:02:55.210,15599001,11750506,nan,thank you when I tried doing what you said inc...,2012-07-31T23:55:09.690,1567094.00
13167367,1567095.00,2012-07-31T22:35:43.210,user1567095,2012-07-31T23:17:08.790,15598655,11750200,nan,Thanks for the reply. It's close but it's comp...,2012-07-31T23:27:20.463,1567095.00

In [88]:
c_users_comments=merged_user_comments.groupby('id').size().reset_index(name='noComments')
c_users_comments

               id  noComments
0            1.00         495
1            2.00           6
2            3.00         164
3            4.00         148
4            5.00         154
5            9.00          13
6           13.00        2463
7           16.00           2
8           17.00         371
9           19.00           1
10          20.00          89
11          22.00          90
12          23.00           2
13          24.00          13
14          25.00          58
15          26.00         395
16          27.00           3
17          29.00        1065
18          30.00          71
19          33.00         133
20          34.00           8
21          35.00          85
22          36.00          58
23          37.00          89
24          38.00          78
25          39.00          41
26          40.00          96
27          42.00         131
28          43.00          92
29          44.00           1
...           ...         ...
484797 1566856.00           1
484798 1566857.00           2
484799 1566861.00           5
484800 1566869.00           1
484801 1566878.00           1
484802 1566884.00           4
484803 1566921.00           1
484804 1566925.00           1
484805 1566935.00           1
484806 1566950.00           1
484807 1566957.00           2
484808 1566968.00           2
484809 1566980.00           4
484810 1566985.00           1
484811 1566991.00           1
484812 1567010.00           1
484813 1567014.00           5
484814 1567017.00           4
484815 1567027.00           1
484816 1567035.00           1
484817 1567042.00           1
484818 1567046.00           1
484819 1567054.00           4
484820 1567055.00           2
484821 1567060.00           1
484822 1567063.00           1
484823 1567078.00           2
484824 1567088.00           2
484825 1567094.00           2
484826 1567095.00           1

[484827 rows x 2 columns]

In [89]:
c_users_comments.to_csv("feature_users_comments.csv")

In [90]:
merged_qap_edits_comments = pd.merge(left=merged_qap_edits,right=c_users_comments,how='outer', left_on='id', right_on='id')
#merged_qap_edits_comments = merged_qap_edits_comments.fillna(0)
merged_qap_edits_comments.shape

(841924, 7)

In [91]:
merged_qap_edits_comments

               id  noPosts  noQues   noAns  z-score  noPostEdits  noComments
0           -1.00 26355.00    0.00    0.00      nan      8119.00         nan
1            1.00   158.00   15.00  143.00    10.18      1112.00      495.00
2            2.00    12.00    7.00    5.00    -0.58        25.00        6.00
3            3.00    38.00    6.00   32.00     4.22       101.00      164.00
4            4.00   178.00   11.00  167.00    11.69       123.00      148.00
5            5.00   343.00   45.00  298.00    13.66       105.00      154.00
6            8.00     1.00    1.00    0.00    -1.00         1.00         nan
7            9.00    58.00   18.00   40.00     2.89         4.00       13.00
8           11.00     1.00    1.00    0.00    -1.00          nan         nan
9           13.00  1288.00    8.00 1279.00    35.43       496.00     2463.00
10          16.00    10.00    1.00    9.00     2.53          nan        2.00
11          17.00   609.00   29.00  580.00    22.33       142.00      371.00
12          19.00    14.00    2.00   12.00     2.67         1.00        1.00
13          20.00   112.00   21.00   91.00     6.61        62.00       89.00
14          22.00   189.00   16.00  173.00    11.42        20.00       90.00
15          23.00    10.00    6.00    4.00    -0.63         5.00        2.00
16          24.00    14.00    1.00   13.00     3.21         2.00       13.00
17          25.00    83.00   34.00   49.00     1.65        25.00       58.00
18          26.00   350.00  118.00  232.00     6.09        52.00      395.00
19          27.00    13.00    4.00    9.00     1.39         5.00        3.00
20          29.00   491.00   57.00  434.00    17.01       252.00     1065.00
21          30.00    82.00   10.00   72.00     6.85        31.00       71.00
22          32.00     5.00    2.00    3.00     0.45          nan         nan
23          33.00   116.00   35.00   81.00     4.27       139.00      133.00
24          34.00    70.00    5.00   65.00     7.17         3.00        8.00
25          35.00   219.00   20.00  199.00    12.10        74.00       85.00
26          36.00   113.00    6.00  107.00     9.50        18.00       58.00
27          37.00    72.00   24.00   48.00     2.83         8.00       89.00
28          38.00   141.00  101.00   40.00    -5.14        22.00       78.00
29          39.00    70.00   16.00   54.00     4.54        27.00       41.00
...           ...      ...     ...     ...      ...          ...         ...
841894 1551511.00      nan     nan     nan      nan          nan        1.00
841895 1552370.00      nan     nan     nan      nan          nan        1.00
841896 1552828.00      nan     nan     nan      nan          nan        1.00
841897 1553187.00      nan     nan     nan      nan          nan        1.00
841898 1553198.00      nan     nan     nan      nan          nan        1.00
841899 1554059.00      nan     nan     nan      nan          nan        1.00
841900 1554213.00      nan     nan     nan      nan          nan        1.00
841901 1554349.00      nan     nan     nan      nan          nan        1.00
841902 1554423.00      nan     nan     nan      nan          nan        1.00
841903 1555512.00      nan     nan     nan      nan          nan        1.00
841904 1555630.00      nan     nan     nan      nan          nan        1.00
841905 1555845.00      nan     nan     nan      nan          nan        1.00
841906 1556078.00      nan     nan     nan      nan          nan        1.00
841907 1556306.00      nan     nan     nan      nan          nan        1.00
841908 1556403.00      nan     nan     nan      nan          nan        1.00
841909 1556404.00      nan     nan     nan      nan          nan        1.00
841910 1556772.00      nan     nan     nan      nan          nan        1.00
841911 1557181.00      nan     nan     nan      nan          nan        1.00
841912 1557793.00      nan     nan     nan      nan          nan        1.00
841913 1557905.00      nan     nan     nan      nan          nan        1.00
841914 1558079.00      nan     nan     nan      nan          nan        1.00
841915 1558891.00      nan     nan     nan      nan          nan        1.00
841916 1558936.00      nan     nan     nan      nan          nan        1.00
841917 1560270.00      nan     nan     nan      nan          nan        1.00
841918 1563449.00      nan     nan     nan      nan          nan        1.00
841919 1564068.00      nan     nan     nan      nan          nan        1.00
841920 1564428.00      nan     nan     nan      nan          nan        1.00
841921 1564475.00      nan     nan     nan      nan          nan        1.00
841922 1565958.00      nan     nan     nan      nan          nan        1.00
841923 1567027.00      nan     nan     nan      nan          nan        1.00

[841924 rows x 7 columns]

In [92]:
merged_qap_edits_comments.to_csv("feature_merged_qap_edits_comments.csv")